# Indexing & Selection

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    'Name': ['Ali','Sara','Reza'],
    'Age': [25, 30, 22],
    'Score': [85, 92, 78]
})

## Select One Column

In [3]:
df['Age']

0    25
1    30
2    22
Name: Age, dtype: int64

In [4]:
df.Age

0    25
1    30
2    22
Name: Age, dtype: int64

## Select Multiple Columns

In [5]:
df[['Name', 'Age']]

   Name  Age
0   Ali   25
1  Sara   30
2  Reza   22

## Select Rows with iloc

In [6]:
# Select first row
df.iloc[0]

Name     Ali
Age       25
Score     85
Name: 0, dtype: object

In [7]:
# Select rows 0 to 2
df.iloc[0:3]

   Name  Age  Score
0   Ali   25     85
1  Sara   30     92
2  Reza   22     78

In [8]:
# Select specific rows
df.iloc[[0, 2]]

   Name  Age  Score
0   Ali   25     85
2  Reza   22     78

# Select Rows and Columns with iloc

In [9]:
# Rows 0 to 2, columns 0 and 1
df.iloc[0:2, 0:2]

   Name  Age
0   Ali   25
1  Sara   30

In [10]:
# Specific rows and columns
df.iloc[[0, 2],[1, 2]]

   Age  Score
0   25     85
2   22     78

## Select with loc

In [12]:
# Select row by label
df.loc[0]

Name     Ali
Age       25
Score     85
Name: 0, dtype: object

In [13]:
# Select rows
df.loc[0:2]

   Name  Age  Score
0   Ali   25     85
1  Sara   30     92
2  Reza   22     78

In [14]:
# Select rows and columns
df.loc[0:2, ['Name', 'Age']]

   Name  Age
0   Ali   25
1  Sara   30
2  Reza   22

## iloc vs loc

In [15]:
# Position-based
df.iloc[0,1]

np.int64(25)

In [16]:
# Label-based
df.loc[0,'Age']

np.int64(25)

## Boolean Indexing

In [17]:
# Creat a condition
condition = df['Age'] > 25
condition

0    False
1     True
2    False
Name: Age, dtype: bool

In [18]:
# Filter rows
df[condition]

   Name  Age  Score
1  Sara   30     92

In [19]:
df[df['Age'] > 25]

   Name  Age  Score
1  Sara   30     92

## Multiple Conditions

In [20]:
# AND
df[(df['Age'] > 25) & (df['Score'] > 80)]

   Name  Age  Score
1  Sara   30     92

In [24]:
# OR
df[(df['Age'] > 25) | (df['Score'] < 80)]

   Name  Age  Score
1  Sara   30     92
2  Reza   22     78

In [26]:
# NOT
df[~(df['Age'] > 25)]

   Name  Age  Score
0   Ali   25     85
2  Reza   22     78

## isin()

In [28]:
# Select specific values
df[df['Name'].isin(['Ali', 'Sara'])]

   Name  Age  Score
0   Ali   25     85
1  Sara   30     92

## between()

In [29]:
df[df['Age'].between(20, 30)]

   Name  Age  Score
0   Ali   25     85
1  Sara   30     92
2  Reza   22     78

## Select Specific Columns After Filtering

In [30]:
# df.loc[condition, columns]

In [31]:
df.loc[df['Age'] > 25, ['Name', 'Score' ]]

   Name  Score
1  Sara     92

## Chane a Value with loc

In [33]:
df.loc[df['Name'] == 'Ali', 'Score'] = 90
df

   Name  Age  Score
0   Ali   25     90
1  Sara   30     92
2  Reza   22     78

## Change Multiple Values

In [36]:
df.loc[df['Score'] < 80, 'Passed'] = False
df

   Name  Age  Score Passed
0   Ali   25     90    NaN
1  Sara   30     92    NaN
2  Reza   22     78  False

## Reset Index

In [40]:
df = df.reset_index(drop = True)
df.to_pickle('df03.pkl')
df

   Name  Age  Score Passed
0   Ali   25     90    NaN
1  Sara   30     92    NaN
2  Reza   22     78  False