# Data Cleaning

In [27]:
import numpy as np
import pandas as pd

## Check Missing Values

In [28]:
df = pd.read_pickle('df03.pkl')
df

   Name  Age  Score Passed
0   Ali   25     90    NaN
1  Sara   30     92    NaN
2  Reza   22     78  False

In [29]:
# Check missing values
df.isna()

    Name    Age  Score  Passed
0  False  False  False    True
1  False  False  False    True
2  False  False  False   False

In [30]:
df.isna().sum()

Name      0
Age       0
Score     0
Passed    2
dtype: int64

## Check Missing Values as Percentage

In [31]:
# Missing percentage
df.isna().mean() * 100

Name       0.000000
Age        0.000000
Score      0.000000
Passed    66.666667
dtype: float64

In [32]:
# Sort missing percentage
df.isna().mean().sort_values(ascending = False) * 100

Passed    66.666667
Name       0.000000
Age        0.000000
Score      0.000000
dtype: float64

## Check if Missing Values Exist

In [33]:
# Check in columns
df.isna().any()

Name      False
Age       False
Score     False
Passed     True
dtype: bool

In [34]:
# Check in whole DataFrame
df.isna().any().any()

np.True_

## Select Rows with Missing Values

In [35]:
# Select rows with missing Passed
df[df['Passed'].isna()]

   Name  Age  Score Passed
0   Ali   25     90    NaN
1  Sara   30     92    NaN

In [36]:
# Select rows without missing Passed
df[df['Passed'].notna()]

   Name  Age  Score Passed
2  Reza   22     78  False

In [38]:
# Remove rows with any missing value
df1 = df.copy()
df1.dropna()
# Apply changes
df1.dropna(inplace = True)

In [39]:
df1

   Name  Age  Score Passed
2  Reza   22     78  False

In [40]:
df1 = df.copy()

In [41]:
# Remove rows missing Passed values
df.dropna(subset = ['Passed', 'Score'])

   Name  Age  Score Passed
2  Reza   22     78  False

## Drop Columns with Missing Values

In [42]:
df.dropna(axis = 1)

   Name  Age  Score
0   Ali   25     90
1  Sara   30     92
2  Reza   22     78

In [44]:
# axis = 0 --> rows
# axis = 1 --> columns

## Fill Missing Values

In [45]:
# Fill missing values by 0
df1['Passed'] = df['Passed'].fillna(0)

In [46]:
df1

   Name  Age  Score Passed
0   Ali   25     90      0
1  Sara   30     92      0
2  Reza   22     78  False

## Fill with Mean

In [47]:
df1 = df.copy()

In [49]:
df1['Passed'] = df['Passed'].fillna(df['Passed'].mean())

In [50]:
df1

   Name  Age  Score Passed
0   Ali   25     90    0.0
1  Sara   30     92    0.0
2  Reza   22     78  False

## Fill with Median

In [51]:
df1['Passed'] = df['Passed'].fillna(df['Passed'].median())

## Fill with Mode

In [52]:
df1['Passed'] = df['Passed'].fillna(df['Passed'].mode())

## Forward Fill

In [56]:
# Fill using previuos value
df1['Passed'] = df['Passed'].ffill()

In [ ]:
# 10 - 20 - NAN - 40 --> 10 - 20 - 20 - 40

## Backward Fill

In [54]:
# Fill using next value
df1['Passed'] = df['Passed'].bfill()

In [57]:
# 10 - 20 - NAN - 40 --> 10 - 20 - 40 - 40

## eplace Specific Values

In [58]:
# Replace specific values
df['Age'] = df['Age'].replace(0, np.nan)

In [59]:
# Replace text value
df['Name'] = df['Name'].replace('Unknown', np.nan)

## Remove Duplicate Rows

In [61]:
# Check duplicated rows
df.duplicated()

0    False
1    False
2    False
dtype: bool

In [63]:
# Count duplicate rws
df.duplicated().sum()

np.int64(0)

In [65]:
# Remove duplicated rows
df = df.drop_duplicates()

## Duplicate Based on Specific Column

In [66]:
# Check duplicates based on Name
df.duplicated(subset = ['Name'])

0    False
1    False
2    False
dtype: bool

In [67]:
# Remove duplicated names
df = df.drop_duplicates(subset = ['Name'])