# Data Types & Conversion

In [8]:
import numpy as np
import pandas as pd
df = pd.read_pickle('df03.pkl')
df

   Name  Age  Score Passed
0   Ali   25     90    NaN
1  Sara   30     92    NaN
2  Reza   22     78  False

## Check Data Types

In [9]:
# Check data types
df.dtypes

Name         str
Age        int64
Score      int64
Passed    object
dtype: object

In [10]:
# Check one column type
df["Age"].dtype

dtype('int64')

## Common Pandas Data Types

In [11]:
# int64    -->  Integer
# float64  -->  Decimal
# object   --> Text / mixed
# string   --> Text
# datatime --> Data and time

## Convert with astype()

In [12]:
# Convert to integer
df['Age'] = df['Age'].astype(int)
df['Age'].dtype

dtype('int64')

In [13]:
# Convert to float
df['Age'] = df['Age'].astype(float)
df['Age'].dtype

dtype('float64')

In [14]:
# Convert to string
df['Age'] = df['Age'].astype(str)
df['Age'].dtype

In [15]:
# Convert to bpplean
df['Age'] = df['Age'].astype(bool)
df['Age'].dtype

dtype('bool')

## Convert Multiple Columns

In [17]:
df = df.astype({
    'Age': 'int64',
    'Score': 'float64'
})

## pd.to_numeric()

In [19]:
# Convert to numeric
df['Age'] = pd.to_numeric(df['Age'])
df

   Name  Age  Score Passed
0   Ali    1   90.0    NaN
1  Sara    1   92.0    NaN
2  Reza    1   78.0  False

In [21]:
# Conveert invalid values to NaN
# Convert to numeric
df['Age'] = pd.to_numeric(df['Age'], errors = 'coerce')
df

   Name  Age  Score Passed
0   Ali    1   90.0    NaN
1  Sara    1   92.0    NaN
2  Reza    1   78.0  False

## Convert to DateTime

In [26]:
df['Date'] = ['2025-01-15', '2024-02-20', '2025-04-25']
df['Date'] = pd.to_datetime(df['Date'])
df

   Name  Age  Score Passed       Date
0   Ali    1   90.0    NaN 2025-01-15
1  Sara    1   92.0    NaN 2024-02-20
2  Reza    1   78.0  False 2025-04-25

In [27]:
# Convert invalid dates to NaN
df['Date'] = pd.to_datetime(df['Date'], errors = 'coerce')
df

   Name  Age  Score Passed       Date
0   Ali    1   90.0    NaN 2025-01-15
1  Sara    1   92.0    NaN 2024-02-20
2  Reza    1   78.0  False 2025-04-25

## Extract Data Components

In [28]:
# Extract year
df['Year'] = df['Date'].dt.year
df

   Name  Age  Score Passed       Date  Year
0   Ali    1   90.0    NaN 2025-01-15  2025
1  Sara    1   92.0    NaN 2024-02-20  2024
2  Reza    1   78.0  False 2025-04-25  2025

In [29]:
# Extract month
df['Month'] = df['Date'].dt.month
df

   Name  Age  Score Passed       Date  Year  Month
0   Ali    1   90.0    NaN 2025-01-15  2025      1
1  Sara    1   92.0    NaN 2024-02-20  2024      2
2  Reza    1   78.0  False 2025-04-25  2025      4

In [30]:
# Extract day
df['Day'] = df['Date'].dt.day
df

   Name  Age  Score Passed       Date  Year  Month  Day
0   Ali    1   90.0    NaN 2025-01-15  2025      1   15
1  Sara    1   92.0    NaN 2024-02-20  2024      2   20
2  Reza    1   78.0  False 2025-04-25  2025      4   25

In [32]:
# Extract weekday
df['Weekday'] = df['Date'].dt.day_name()
df

   Name  Age  Score Passed       Date  Year  Month  Day    Weekday
0   Ali    1   90.0    NaN 2025-01-15  2025      1   15  Wednesday
1  Sara    1   92.0    NaN 2024-02-20  2024      2   20    Tuesday
2  Reza    1   78.0  False 2025-04-25  2025      4   25     Friday

In [33]:
# Extract hour
df['Hour'] = df['Date'].dt.hour
df

   Name  Age  Score Passed       Date  Year  Month  Day    Weekday  Hour
0   Ali    1   90.0    NaN 2025-01-15  2025      1   15  Wednesday     0
1  Sara    1   92.0    NaN 2024-02-20  2024      2   20    Tuesday     0
2  Reza    1   78.0  False 2025-04-25  2025      4   25     Friday     0

## String Data

In [35]:
# Convert text to lowercase
df['Name'] = df['Name'].str.lower()
df

   Name  Age  Score Passed       Date  Year  Month  Day    Weekday  Hour
0   ali    1   90.0    NaN 2025-01-15  2025      1   15  Wednesday     0
1  sara    1   92.0    NaN 2024-02-20  2024      2   20    Tuesday     0
2  reza    1   78.0  False 2025-04-25  2025      4   25     Friday     0

In [36]:
# Convert text to Uppercase
df['Name'] = df['Name'].str.upper()
df

   Name  Age  Score Passed       Date  Year  Month  Day    Weekday  Hour
0   ALI    1   90.0    NaN 2025-01-15  2025      1   15  Wednesday     0
1  SARA    1   92.0    NaN 2024-02-20  2024      2   20    Tuesday     0
2  REZA    1   78.0  False 2025-04-25  2025      4   25     Friday     0

In [37]:
# Remove extra spaces
df['Name'] = df['Name'].str.strip()
df

   Name  Age  Score Passed       Date  Year  Month  Day    Weekday  Hour
0   ALI    1   90.0    NaN 2025-01-15  2025      1   15  Wednesday     0
1  SARA    1   92.0    NaN 2024-02-20  2024      2   20    Tuesday     0
2  REZA    1   78.0  False 2025-04-25  2025      4   25     Friday     0

## String Contains

In [38]:
# Check if text contains 'ALI'
df['Name'].str.contains('ALI')

0     True
1    False
2    False
Name: Name, dtype: bool

In [39]:
# Filter rows containing 'ALI'
df[df['Name'].str.contains('ALI')]

  Name  Age  Score Passed       Date  Year  Month  Day    Weekday  Hour
0  ALI    1   90.0    NaN 2025-01-15  2025      1   15  Wednesday     0

In [40]:
# Treat missing values as False
df[df['Name'].str.contains('ALI', na = False)]

  Name  Age  Score Passed       Date  Year  Month  Day    Weekday  Hour
0  ALI    1   90.0    NaN 2025-01-15  2025      1   15  Wednesday     0

## Replace text

In [43]:
df['Name'] = df['Name'].str.replace('ALI','Ali')
df['Name'] = df['Name'].str.replace('SARA','Sara')
df['Name'] = df['Name'].str.replace('REZA','Reza')
df

   Name  Age  Score Passed       Date  Year  Month  Day    Weekday  Hour
0   Ali    1   90.0    NaN 2025-01-15  2025      1   15  Wednesday     0
1  Sara    1   92.0    NaN 2024-02-20  2024      2   20    Tuesday     0
2  Reza    1   78.0  False 2025-04-25  2025      4   25     Friday     0

In [45]:
# Convert to category --> reducing memory useage
df['Name'] = df['Name'].astype('category')