# Dorting and Ranking

## Creat a DataFrame

In [48]:
import pandas as pd
df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Reza', 'Mina', 'Omid'],
    'Age': [25, 30, 22, 28, 25],
    'Score': [85, 92, 78, 92, 88],
    'City': ['Baku', 'Tehran', 'Baku', 'Tabriz', 'Tehran']
})
df

   Name  Age  Score    City
0   Ali   25     85    Baku
1  Sara   30     92  Tehran
2  Reza   22     78    Baku
3  Mina   28     92  Tabriz
4  Omid   25     88  Tehran

## Sorting by One Column

In [49]:
# Sort by Age
df.sort_values('Age')

   Name  Age  Score    City
2  Reza   22     78    Baku
0   Ali   25     85    Baku
4  Omid   25     88  Tehran
3  Mina   28     92  Tabriz
1  Sara   30     92  Tehran

## Descending Order

In [50]:
df.sort_values('Age', ascending = False)

   Name  Age  Score    City
1  Sara   30     92  Tehran
3  Mina   28     92  Tabriz
0   Ali   25     85    Baku
4  Omid   25     88  Tehran
2  Reza   22     78    Baku

## Sorting bu Multiple Columns

In [51]:
## Sort by Age, than Score
df.sort_values(['Age', 'Score'])

   Name  Age  Score    City
2  Reza   22     78    Baku
0   Ali   25     85    Baku
4  Omid   25     88  Tehran
3  Mina   28     92  Tabriz
1  Sara   30     92  Tehran

## Different Order for Each Column

In [52]:
df.sort_values(['Age', 'Score'], ascending = [True, False])

   Name  Age  Score    City
2  Reza   22     78    Baku
4  Omid   25     88  Tehran
0   Ali   25     85    Baku
3  Mina   28     92  Tabriz
1  Sara   30     92  Tehran

In [53]:
# Age   --> Ascending
# Score --> Descending

## Inplace

In [54]:
df.sort_values('Score', ascending = False, inplace = True)
df

   Name  Age  Score    City
1  Sara   30     92  Tehran
3  Mina   28     92  Tabriz
4  Omid   25     88  Tehran
0   Ali   25     85    Baku
2  Reza   22     78    Baku

## Sort by Index

In [55]:
# Sort by index
df.sort_index()

   Name  Age  Score    City
0   Ali   25     85    Baku
1  Sara   30     92  Tehran
2  Reza   22     78    Baku
3  Mina   28     92  Tabriz
4  Omid   25     88  Tehran

In [56]:
# Sort by index descending
df.sort_index(ascending = False)

   Name  Age  Score    City
4  Omid   25     88  Tehran
3  Mina   28     92  Tabriz
2  Reza   22     78    Baku
1  Sara   30     92  Tehran
0   Ali   25     85    Baku

## Reset Index After Sorting

In [59]:
df.reset_index(drop = True)

   Name  Age  Score    City
0  Sara   30     92  Tehran
1  Mina   28     92  Tabriz
2  Omid   25     88  Tehran
3   Ali   25     85    Baku
4  Reza   22     78    Baku

## Ranking

In [61]:
# Creat ranks
df['Rank'] = df['Score'].rank()
df

   Name  Age  Score    City  Rank
1  Sara   30     92  Tehran   4.5
3  Mina   28     92  Tabriz   4.5
4  Omid   25     88  Tehran   3.0
0   Ali   25     85    Baku   2.0
2  Reza   22     78    Baku   1.0

## Descending Rank

In [62]:
df['Rank'] = df['Score'].rank(ascending = False)
df

   Name  Age  Score    City  Rank
1  Sara   30     92  Tehran   1.5
3  Mina   28     92  Tabriz   1.5
4  Omid   25     88  Tehran   3.0
0   Ali   25     85    Baku   4.0
2  Reza   22     78    Baku   5.0

## Ranking with method

In [63]:
# Average rank for ties
df['Rank'] = df['Score'].rank(ascending = False, method = 'average')
df

   Name  Age  Score    City  Rank
1  Sara   30     92  Tehran   1.5
3  Mina   28     92  Tabriz   1.5
4  Omid   25     88  Tehran   3.0
0   Ali   25     85    Baku   4.0
2  Reza   22     78    Baku   5.0

In [66]:
# min / max rank for ties
df['Rank'] = df['Score'].rank(ascending = False, method = 'min')
df

   Name  Age  Score    City  Rank
1  Sara   30     92  Tehran   1.0
3  Mina   28     92  Tabriz   1.0
4  Omid   25     88  Tehran   3.0
0   Ali   25     85    Baku   4.0
2  Reza   22     78    Baku   5.0

In [67]:
# Dense ranking
df['Rank'] = df['Score'].rank(ascending = False, method = 'dense')
df

   Name  Age  Score    City  Rank
1  Sara   30     92  Tehran   1.0
3  Mina   28     92  Tabriz   1.0
4  Omid   25     88  Tehran   2.0
0   Ali   25     85    Baku   3.0
2  Reza   22     78    Baku   4.0

## Find Top Values

In [68]:
# Top 3 Scores
df.nlargest(3, 'Score')

   Name  Age  Score    City  Rank
1  Sara   30     92  Tehran   1.0
3  Mina   28     92  Tabriz   1.0
4  Omid   25     88  Tehran   2.0

## Find Bottom Values

In [70]:
# Bottom 3 scores
df.nsmallest(3, 'Score')

   Name  Age  Score    City  Rank
2  Reza   22     78    Baku   4.0
0   Ali   25     85    Baku   3.0
4  Omid   25     88  Tehran   2.0