# Groupby and Aggregation

In [1]:
import pandas as pd

# Creat a DataFrame
df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Reza', 'Mina', 'Omid', 'Neda', 'Amir', 'Maryam'],
    'City': ['Baku', 'Tehran', 'Baku', 'Tehran', 'Baku', 'Tabriz', 'Tehran', 'Tabriz'],
    'Department': ['Sales', 'IT', 'Sales', 'HR', 'IT', 'Sales', 'IT', 'HR'],
    'Age': [25, 30, 22, 28, 25, 32, 27, 29],
    'Salary': [2500, 4200, 2800, 3500, 4000, 3000, 4500, 3200],
    'Score': [85, 92, 78, 88, 90, 75, 95, 82]
})
df

     Name    City Department  Age  Salary  Score
0     Ali    Baku      Sales   25    2500     85
1    Sara  Tehran         IT   30    4200     92
2    Reza    Baku      Sales   22    2800     78
3    Mina  Tehran         HR   28    3500     88
4    Omid    Baku         IT   25    4000     90
5    Neda  Tabriz      Sales   32    3000     75
6    Amir  Tehran         IT   27    4500     95
7  Maryam  Tabriz         HR   29    3200     82

## Basic groupby

In [2]:
# Average salary by city
df.groupby('City')['Salary'].mean()

City
Baku      3100.000000
Tabriz    3100.000000
Tehran    4066.666667
Name: Salary, dtype: float64

## GroupBy wuth sum()

In [3]:
# Total salary by city
df.groupby('City')['Salary'].sum()

City
Baku       9300
Tabriz     6200
Tehran    12200
Name: Salary, dtype: int64

## GroupBy with count()

In [8]:
# Count employees by city
df.groupby('City')['Name'].count()
# Count not NaN values

City
Baku      3
Tabriz    2
Tehran    3
Name: Name, dtype: int64

## GroupBy with size()

In [9]:
# Count rows in each group
df.groupby('City').size()
# Count all values even NaN

City
Baku      3
Tabriz    2
Tehran    3
dtype: int64

## Other Aggregation Functions

In [10]:
# Minimum salary by city
df.groupby('City')['Salary'].min()

City
Baku      2500
Tabriz    3000
Tehran    3500
Name: Salary, dtype: int64

In [11]:
# Maximum salary by city
df.groupby('City')['Salary'].max()

City
Baku      4000
Tabriz    3200
Tehran    4500
Name: Salary, dtype: int64

In [12]:
# Median salary by city
df.groupby('City')['Salary'].median()

City
Baku      2800.0
Tabriz    3100.0
Tehran    4200.0
Name: Salary, dtype: float64

In [13]:
# Standard diviation by city
df.groupby('City')['Salary'].std()

City
Baku      793.725393
Tabriz    141.421356
Tehran    513.160144
Name: Salary, dtype: float64

## Multiple aggregations

In [16]:
df.groupby('City')['Salary'].agg(['min', 'max', 'mean'])

         min   max         mean
City
Baku    2500  4000  3100.000000
Tabriz  3000  3200  3100.000000
Tehran  3500  4500  4066.666667

## .agg() with Named Results

In [17]:
df.groupby('City')['Salary'].agg(Average_Salary = 'mean', Maximum_Salary = 'max', Minimum_Salary = 'min')

        Average_Salary  Maximum_Salary  Minimum_Salary
City
Baku       3100.000000            4000            2500
Tabriz     3100.000000            3200            3000
Tehran     4066.666667            4500            3500

## Group Multiple Columns

In [19]:
# Average age ang salary by city
df.groupby('City')[['Age', 'Salary']].mean()

              Age       Salary
City
Baku    24.000000  3100.000000
Tabriz  30.500000  3100.000000
Tehran  28.333333  4066.666667

## Multiple Aggregations on Multiple Columns

In [20]:
df.groupby('City')[['Age', 'Salary']].agg(['min', 'max', 'mean', 'median', 'std'])

       Age                                 Salary                             \
       min max       mean median       std    min   max         mean  median
City
Baku    22  25  24.000000   25.0  1.732051   2500  4000  3100.000000  2800.0
Tabriz  29  32  30.500000   30.5  2.121320   3000  3200  3100.000000  3100.0
Tehran  27  30  28.333333   28.0  1.527525   3500  4500  4066.666667  4200.0


               std
City
Baku    793.725393
Tabriz  141.421356
Tehran  513.160144

## GroupBy Two Columns

In [21]:
df.groupby(['City', 'Department'])['Salary'].mean()

City    Department
Baku    IT            4000.0
        Sales         2650.0
Tabriz  HR            3200.0
        Sales         3000.0
Tehran  HR            3500.0
        IT            4350.0
Name: Salary, dtype: float64

## Count Groups

In [23]:
# Count employees by city and department
df.groupby(['City', 'Department']).size()

City    Department
Baku    IT            1
        Sales         2
Tabriz  HR            1
        Sales         1
Tehran  HR            1
        IT            2
dtype: int64

## Reset Index

In [24]:
result = df.groupby('City')['Salary'].mean()
result

City
Baku      3100.000000
Tabriz    3100.000000
Tehran    4066.666667
Name: Salary, dtype: float64

In [25]:
# Cnvert index back to column
result = result.reset_index()
result

     City       Salary
0    Baku  3100.000000
1  Tabriz  3100.000000
2  Tehran  4066.666667

## GroupBy + Sort

In [27]:
# Average salary by city
result = df.groupby('City')['Salary'].mean().sort_values(ascending = False)
result

City
Tehran    4066.666667
Baku      3100.000000
Tabriz    3100.000000
Name: Salary, dtype: float64

## GroupBy + Filter

In [29]:
# Calculate average salary
avg_salary = df.groupby('City')['Salary'].mean()
avg_salary[avg_salary > 3500]

City
Tehran    4066.666667
Name: Salary, dtype: float64

## groupby().filter()

In [30]:
# Keep groups with at least 3 employees
df.groupby('City').filter(lambda x: len(x) >= 3 )

   Name    City Department  Age  Salary  Score
0   Ali    Baku      Sales   25    2500     85
1  Sara  Tehran         IT   30    4200     92
2  Reza    Baku      Sales   22    2800     78
3  Mina  Tehran         HR   28    3500     88
4  Omid    Baku         IT   25    4000     90
6  Amir  Tehran         IT   27    4500     95

## GroupBy with Diffrenr Functions

In [31]:
# Multiple metrics by department
df.groupby('Department').agg({
    'Age': 'mean',
    'Salary': 'mean',
    'Score': 'max'
})

                  Age       Salary  Score
Department
HR          28.500000  3350.000000     88
IT          27.333333  4233.333333     95
Sales       26.333333  2766.666667     85

## Named Aggregation

In [33]:
# Craet custom output names
result = df.groupby('Department').agg(
    Average_Name = ('Age', 'mean'),
    Average_Salary = ('Salary', 'mean'),
    Highest_Score = ('Score', 'max')
)
result

            Average_Name  Average_Salary  Highest_Score
Department
HR             28.500000     3350.000000             88
IT             27.333333     4233.333333             95
Sales          26.333333     2766.666667             85

## GroupBy with nunique()

In [38]:
# Count unique cities by department
df.groupby('Department')['City'].nunique()

Department
HR       2
IT       2
Sales    2
Name: City, dtype: int64

## GroupBy with unique()

In [39]:
# Count unique cities
df.groupby('Department')['City'].unique()

Department
HR       [Tehran, Tabriz]
IT         [Tehran, Baku]
Sales      [Baku, Tabriz]
Name: City, dtype: object

## GroupBy +  value_counts()

In [42]:
# Count city occurences by department
df.groupby('Department')['City'].value_counts()

Department  City
HR          Tehran    1
            Tabriz    1
IT          Tehran    2
            Baku      1
Sales       Baku      2
            Tabriz    1
Name: count, dtype: int64

## A Real Data Analysis Example

In [45]:
# Creat department summary
summary = df.groupby('Department').agg(Employees = ('Name','count'),
                                      Average_Age = ('Age', 'mean'),
                                      Average_Salary = ('Salary', 'mean'),
                                      Maximum_Saslary = ('Salary', 'max'),
                                      Average_Score = ('Score','mean')
                                      )
summary

,Employees,Average_Age,Average_Salary,Maximum_Saslary,Average_Score
Department,,,,,
HR,2,28.500000,3350.000000,3500,85.000000
IT,3,27.333333,4233.333333,4500,92.333333
Sales,3,26.333333,2766.666667,3000,79.333333

## as_index = False

In [48]:
# Keep group column as a normal column
df.groupby('City', as_index = False)['Salary'].mean()

     City       Salary
0    Baku  3100.000000
1  Tabriz  3100.000000
2  Tehran  4066.666667

In [49]:
# Creat plotting-ready data
city_salary = df.groupby('City', as_index = False)['Salary'].mean()
city_salary

     City       Salary
0    Baku  3100.000000
1  Tabriz  3100.000000
2  Tehran  4066.666667

## groupby() Mental Model

df.groupby('Column')['Value'].mean

Group by Column --> Select Value --> Calculate Mean

or

df.groupby('GroupColumn').agg(NewName = ('Column', 'Function'))

In [52]:
df.groupby('Department').agg(Average_Salary = ('Salary' , 'mean'), Maximum_Score = ('Score', 'max'), Employees = ('Name', 'count'))

            Average_Salary  Maximum_Score  Employees
Department
HR             3350.000000             88          2
IT             4233.333333             95          3
Sales          2766.666667             85          3