# Merg, Join and Concatenation

## Creat DataFrame

In [1]:
import pandas as pd
customers = pd.DataFrame({
    'Customer_ID': [101, 102, 103, 104, 105],
    'Name': ['Ali', 'Sara', 'Reza', 'Mina', 'Omid'],
    'City': ['Baku', 'Tehran', 'Baku', 'Tabriz', 'Tehran']
})
customers

   Customer_ID  Name    City
0          101   Ali    Baku
1          102  Sara  Tehran
2          103  Reza    Baku
3          104  Mina  Tabriz
4          105  Omid  Tehran

In [13]:
orders = pd.DataFrame({
    'Order_Id': [1, 2, 3, 5],
    'Customer_ID': [101, 102, 103, 105],
    'Amount': [250, 400, 150, 200]
})
orders

   Order_Id  Customer_ID  Amount
0         1          101     250
1         2          102     400
2         3          103     150
3         5          105     200

## merge()

In [14]:
df = pd.merge(customers, orders, on = 'Customer_ID')
df

   Customer_ID  Name    City  Order_Id  Amount
0          101   Ali    Baku         1     250
1          102  Sara  Tehran         2     400
2          103  Reza    Baku         3     150
3          105  Omid  Tehran         5     200

## Inner Join

In [15]:
## Inner marge --> Default merge --> Customers_Id in both Tables

In [16]:
df = pd.merge(customers, orders, on = 'Customer_ID', how = 'inner')
df

   Customer_ID  Name    City  Order_Id  Amount
0          101   Ali    Baku         1     250
1          102  Sara  Tehran         2     400
2          103  Reza    Baku         3     150
3          105  Omid  Tehran         5     200

## Left Join

In [17]:
## Save all the rows in left table

In [18]:
df = pd.merge(customers, orders, on = 'Customer_ID', how = 'left')
df

   Customer_ID  Name    City  Order_Id  Amount
0          101   Ali    Baku       1.0   250.0
1          102  Sara  Tehran       2.0   400.0
2          103  Reza    Baku       3.0   150.0
3          104  Mina  Tabriz       NaN     NaN
4          105  Omid  Tehran       5.0   200.0

## Right Join

In [19]:
## Save all the rows in right table

In [20]:
df = pd.merge(customers, orders, on = 'Customer_ID', how = 'right')
df

   Customer_ID  Name    City  Order_Id  Amount
0          101   Ali    Baku         1     250
1          102  Sara  Tehran         2     400
2          103  Reza    Baku         3     150
3          105  Omid  Tehran         5     200

## Outer join

In [21]:
## Save all the records in both tables --> NaN for not matched rows

In [22]:
df = pd.merge(customers, orders, on = 'Customer_ID', how = 'outer')
df

   Customer_ID  Name    City  Order_Id  Amount
0          101   Ali    Baku       1.0   250.0
1          102  Sara  Tehran       2.0   400.0
2          103  Reza    Baku       3.0   150.0
3          104  Mina  Tabriz       NaN     NaN
4          105  Omid  Tehran       5.0   200.0

## Visualizing Joint Types

In [23]:
# INNER   --> matching A and B
# LEFT    --> A + matching B
# Right   --> B + matching A
# OUTER   --> A + B

## Merge on Multiple Columns

In [24]:
sales = pd.DataFrame({
    "Year": [2025, 2025, 2026],
    "Product_ID": [1, 2, 1],
    "Sales": [500, 700, 900]
})

targets = pd.DataFrame({
    "Year": [2025, 2025, 2026],
    "Product_ID": [1, 2, 1],
    "Target": [450, 800, 850]
})

In [25]:
df = pd.merge(sales, targets, on = ['Year', 'Product_ID'])
df

   Year  Product_ID  Sales  Target
0  2025           1    500     450
1  2025           2    700     800
2  2026           1    900     850

## suffixes

In [26]:
employees = pd.DataFrame({
    "Employee_ID": [1, 2, 3],
    "Name": ["Ali", "Sara", "Reza"],
    "Score": [80, 90, 85]
})

reviews = pd.DataFrame({
    "Employee_ID": [1, 2, 3],
    "Score": [85, 88, 92]
})

In [29]:
df = pd.merge(employees, reviews, on ='Employee_ID', suffixes = ('_Employees', '_Reviews'))
df

   Employee_ID  Name  Score_Employees  Score_Reviews
0            1   Ali               80             85
1            2  Sara               90             88
2            3  Reza               85             92

## concat()

In [30]:
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Score": [85, 92]
})

df2 = pd.DataFrame({
    "Name": ["Reza", "Mina"],
    "Score": [78, 88]
})

In [32]:
df = pd.concat([df1, df2])
df

   Name  Score
0   Ali     85
1  Sara     92
0  Reza     78
1  Mina     88

## Reset Index After concat()

In [33]:
df = pd.concat([df1, df2], ignore_index = True)
df

   Name  Score
0   Ali     85
1  Sara     92
2  Reza     78
3  Mina     88

## Concatenate Columns

In [34]:
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara", "Reza"]
})

df2 = pd.DataFrame({
    "Score": [85, 92, 78]
})

In [37]:
df = pd.concat([df1, df2], ignore_index = True, axis = 1)
df

      0   1
0   Ali  85
1  Sara  92
2  Reza  78

## Concatenate Diffrent Columns

In [39]:
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Score": [85, 92]
})

df2 = pd.DataFrame({
    "Name": ["Reza", "Mina"],
    "Age": [78, 88]
})

In [40]:
df = pd.concat([df1, df2], ignore_index = True)
df

   Name  Score   Age
0   Ali   85.0   NaN
1  Sara   92.0   NaN
2  Reza    NaN  78.0
3  Mina    NaN  88.0

## join()

In [41]:
left = pd.DataFrame({
    "Name": ["Ali", "Sara", "Reza"]
}, index=[101, 102, 103])

right = pd.DataFrame({
    "Score": [85, 92, 78]
}, index=[101, 102, 103])

In [42]:
df = left.join(right)
df

     Name  Score
101   Ali     85
102  Sara     92
103  Reza     78

## Left Join with join()

In [43]:
df = left.join(right, how = 'left')
df

     Name  Score
101   Ali     85
102  Sara     92
103  Reza     78

## Outer Join with join()

In [44]:
right = pd.DataFrame({
    "Score": [85, 92, 78, 95]
}, index=[101, 102, 103, 104])

In [45]:
df = left.join(right, how = 'outer')
df

     Name  Score
101   Ali     85
102  Sara     92
103  Reza     78
104   NaN     95

## merge() VS join() VS concat()

In [46]:
# merge()  --> Connect using columns
# join()   --> Connect using index
# concat() --> Stack / combine DtaFrames

## Real Data Analysis Example

In [47]:
# Merge customers and orders
customer_orders = pd.merge(
    customers,
    orders,
    on="Customer_ID",
    how="left"
)

customer_orders

   Customer_ID  Name    City  Order_Id  Amount
0          101   Ali    Baku       1.0   250.0
1          102  Sara  Tehran       2.0   400.0
2          103  Reza    Baku       3.0   150.0
3          104  Mina  Tabriz       NaN     NaN
4          105  Omid  Tehran       5.0   200.0

In [48]:
# Calculate total spending
summary = customer_orders.groupby(
    ["Customer_ID", "Name"]
)["Amount"].sum()

summary

Customer_ID  Name
101          Ali     250.0
102          Sara    400.0
103          Reza    150.0
104          Mina      0.0
105          Omid    200.0
Name: Amount, dtype: float64

In [49]:
# Create customer summary
summary = customer_orders.groupby(
    ["Customer_ID", "Name"],
    as_index=False
)["Amount"].sum()

summary

   Customer_ID  Name  Amount
0          101   Ali   250.0
1          102  Sara   400.0
2          103  Reza   150.0
3          104  Mina     0.0
4          105  Omid   200.0

In [50]:
# Sort by total spending
summary.sort_values(
    "Amount",
    ascending=False
)

   Customer_ID  Name  Amount
1          102  Sara   400.0
0          101   Ali   250.0
4          105  Omid   200.0
2          103  Reza   150.0
3          104  Mina     0.0