# Pivot Tables and Crosstab

## Creat DataFrame

In [1]:
import pandas as pd

df = pd.DataFrame({
    "City": ["Baku", "Baku", "Tehran", "Tehran", "Tabriz", "Tabriz", "Baku", "Tehran"],
    "Department": ["Sales", "IT", "Sales", "IT", "Sales", "HR", "HR", "HR"],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female", "Female", "Male"],
    "Sales": [250, 400, 300, 500, 200, 350, 450, 280],
    "Score": [85, 90, 78, 92, 75, 88, 95, 82]
})

df

     City Department  Gender  Sales  Score
0    Baku      Sales    Male    250     85
1    Baku         IT  Female    400     90
2  Tehran      Sales    Male    300     78
3  Tehran         IT  Female    500     92
4  Tabriz      Sales    Male    200     75
5  Tabriz         HR  Female    350     88
6    Baku         HR  Female    450     95
7  Tehran         HR    Male    280     82

## Basic pivot_table

In [3]:
df.pivot_table(values = 'Sales', index = 'City', aggfunc = 'mean')

             Sales
City
Baku    366.666667
Tabriz  275.000000
Tehran  360.000000

## Important Parameters

In [4]:
df.pivot_table(values = 'Sales', index = 'City', columns = 'Department', aggfunc = 'mean')

Department     HR     IT  Sales
City
Baku        450.0  400.0  250.0
Tabriz      350.0    NaN  200.0
Tehran      280.0  500.0  300.0

## Different Aggregation Functions

In [5]:
df.pivot_table(values = 'Sales', index = 'City', aggfunc = ['mean', 'sum', 'count'])

              mean   sum count
             Sales Sales Sales
City
Baku    366.666667  1100     3
Tabriz  275.000000   550     2
Tehran  360.000000  1080     3

## Multiple Values

In [8]:
df.pivot_table(values = ['Sales', 'Score'], aggfunc = 'mean', index = 'City')

             Sales  Score
City
Baku    366.666667   90.0
Tabriz  275.000000   81.5
Tehran  360.000000   84.0

## Two-Dimentional Pivot Table

In [11]:
df.pivot_table(values = 'Sales', index = 'City', columns = 'Department', aggfunc ='sum')

Department     HR     IT  Sales
City
Baku        450.0  400.0  250.0
Tabriz      350.0    NaN  200.0
Tehran      280.0  500.0  300.0

## fill_value

In [12]:
df.pivot_table(values = 'Sales', index = 'City', columns = 'Department', aggfunc ='sum', fill_value = 0  )

Department   HR   IT  Sales
City
Baku        450  400    250
Tabriz      350    0    200
Tehran      280  500    300

## multiple Indexes

In [13]:
df.pivot_table(values = 'Sales', index = ['City', 'Gender'], aggfunc = 'max')

               Sales
City   Gender
Baku   Female    450
       Male      250
Tabriz Female    350
       Male      200
Tehran Female    500
       Male      300

## margins

In [15]:
df.pivot_table(values = 'Sales', index = 'City', columns = 'Department', aggfunc ='sum', fill_value = 0 , margins = True )

Department    HR   IT  Sales   All
City
Baku         450  400    250  1100
Tabriz       350    0    200   550
Tehran       280  500    300  1080
All         1080  900    750  2730

## margins_name

In [17]:
df.pivot_table(values = 'Sales',
               index = 'City',
               columns = 'Department',
               aggfunc ='sum', fill_value = 0,
               margins = True,
              margins_name = 'Total')

Department    HR   IT  Sales  Total
City
Baku         450  400    250   1100
Tabriz       350    0    200    550
Tehran       280  500    300   1080
Total       1080  900    750   2730

## Crosstab --> count values

In [20]:
pd.crosstab(df['City'], df['Department'])

Department  HR  IT  Sales
City
Baku         1   1      1
Tabriz       1   0      1
Tehran       1   1      1

## Croostab with Normalize

In [23]:
pd.crosstab(df['City'], df['Department'], normalize= 'index' ) * 100

Department         HR         IT      Sales
City
Baku        33.333333  33.333333  33.333333
Tabriz      50.000000   0.000000  50.000000
Tehran      33.333333  33.333333  33.333333

## Crosstab with margins

In [24]:
pd.crosstab(df['City'], df['Department'], margins = True )

Department  HR  IT  Sales  All
City
Baku         1   1      1    3
Tabriz       1   0      1    2
Tehran       1   1      1    3
All          3   2      3    8

## Data Analysis Example

In [26]:
summary = df.pivot_table(
    values = 'Sales',
    index ='City',
    columns = 'Department',
    aggfunc = 'sum',
    fill_value = 0
)
summary

Department   HR   IT  Sales
City
Baku        450  400    250
Tabriz      350    0    200
Tehran      280  500    300

In [27]:
summary.max(axis = 1)

City
Baku      450
Tabriz    350
Tehran    500
dtype: int64