# Apply Map and Lambda

## Creat DataFrame

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ali", "Sara", "Reza", "Mina", "Omid"],
    "Age": [25, 30, 22, 28, 35],
    "Score": [85, 92, 78, 88, 95],
    "City": ["Baku", "Tehran", "Baku", "Tabriz", "Tehran"]
})

df

   Name  Age  Score    City
0   Ali   25     85    Baku
1  Sara   30     92  Tehran
2  Reza   22     78    Baku
3  Mina   28     88  Tabriz
4  Omid   35     95  Tehran

In [2]:
square = lambda x: x**2
square(5)

25

In [3]:
add_10 = lambda x : x+ 10
add_10(10)

20

## apply() on a Series

In [5]:
df['New_Score'] = df['Score'].apply(lambda x : x+ 5)
df

   Name  Age  Score    City  New_Score
0   Ali   25     85    Baku         90
1  Sara   30     92  Tehran         97
2  Reza   22     78    Baku         83
3  Mina   28     88  Tabriz         93
4  Omid   35     95  Tehran        100

## apply() with Function

In [7]:
def level(score):
    if score >= 90:
        return 'Execllent'
    elif score >= 80:
        return 'Good'
    else:
        return 'Average'

df['Level'] = df['Score'].apply(level)


df

   Name  Age  Score    City  New_Score      Level
0   Ali   25     85    Baku         90       Good
1  Sara   30     92  Tehran         97  Execllent
2  Reza   22     78    Baku         83    Average
3  Mina   28     88  Tabriz         93       Good
4  Omid   35     95  Tehran        100  Execllent

In [9]:
def age(age):
    if age < 25:
        return 'Young'
    elif age < 35:
        return 'Adult'
    else:
        return 'Senior'

df['Age_Group'] = df['Age'].apply(age)

df

   Name  Age  Score    City  New_Score      Level Age_Group
0   Ali   25     85    Baku         90       Good     Adult
1  Sara   30     92  Tehran         97  Execllent     Adult
2  Reza   22     78    Baku         83    Average     Young
3  Mina   28     88  Tabriz         93       Good     Adult
4  Omid   35     95  Tehran        100  Execllent    Senior

## map()

In [11]:
df['City'].map(lambda x : x.upper())

0      BAKU
1    TEHRAN
2      BAKU
3    TABRIZ
4    TEHRAN
Name: City, dtype: str

In [13]:
df['Name'].map(lambda x : x.upper())

0     ALI
1    SARA
2    REZA
3    MINA
4    OMID
Name: Name, dtype: str

In [14]:
df['Name_upper'] = df['Name'].map(lambda x : x.upper())
df

   Name  Age  Score    City  New_Score      Level Age_Group Name_upper
0   Ali   25     85    Baku         90       Good     Adult        ALI
1  Sara   30     92  Tehran         97  Execllent     Adult       SARA
2  Reza   22     78    Baku         83    Average     Young       REZA
3  Mina   28     88  Tabriz         93       Good     Adult       MINA
4  Omid   35     95  Tehran        100  Execllent    Senior       OMID

## map() with Dictionary

In [15]:
city = {
    'Baku': 'BAK',
    'Tehran': 'THR',
    'Tabriz': 'TAB'
}

df['City_Code'] = df['City'].map(city)

df

,Name,Age,Score,City,New_Score,Level,Age_Group,Name_upper,City_Code
0,Ali,25,85,Baku,90,Good,Adult,ALI,BAK
1,Sara,30,92,Tehran,97,Execllent,Adult,SARA,THR
2,Reza,22,78,Baku,83,Average,Young,REZA,BAK
3,Mina,28,88,Tabriz,93,Good,Adult,MINA,TAB
4,Omid,35,95,Tehran,100,Execllent,Senior,OMID,THR

## apply() Multiple Cplumns

In [17]:
df[['Age', 'Score']].apply(lambda x : x.mean())

Age      28.0
Score    87.6
dtype: float64

## apply() with axis

In [18]:
df[['Age', 'Score']].apply(lambda x : x.mean(), axis = 1)

0    55.0
1    61.0
2    50.0
3    58.0
4    65.0
dtype: float64

## Creat a New Column with Multiple Columns

In [19]:
df['Final'] = df.apply(
    lambda row: row['Score'] * .08 + row['Age'] * .02, axis = 1
)
df

,Name,Age,Score,City,New_Score,Level,Age_Group,Name_upper,City_Code,Final
0,Ali,25,85,Baku,90,Good,Adult,ALI,BAK,7.30
1,Sara,30,92,Tehran,97,Execllent,Adult,SARA,THR,7.96
2,Reza,22,78,Baku,83,Average,Young,REZA,BAK,6.68
3,Mina,28,88,Tabriz,93,Good,Adult,MINA,TAB,7.60
4,Omid,35,95,Tehran,100,Execllent,Senior,OMID,THR,8.30