# Datetime Operations

## Creat DataFrame

In [8]:
import pandas as pd
df = pd.DataFrame({
    'Order': [101, 102, 103, 104],
    'Date': [
        '2025-01-15',
        '2025-02-20',
        '2025-03-10',
        '2025-04-25'
    ],
    'Sales': [1200, 1800, 1500, 2200]
})
df

   Order        Date  Sales
0    101  2025-01-15   1200
1    102  2025-02-20   1800
2    103  2025-03-10   1500
3    104  2025-04-25   2200

## Conveert to Datetime

In [9]:
df['Date'].dtypes

In [11]:
df['Date'] = pd.to_datetime(df['Date'])

df.dtypes

Order             int64
Date     datetime64[us]
Sales             int64
dtype: object

## Extract Year, Month and Day

In [12]:
df['Year'] = df['Date'].dt.year 
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df

   Order       Date  Sales  Year  Month  Day
0    101 2025-01-15   1200  2025      1   15
1    102 2025-02-20   1800  2025      2   20
2    103 2025-03-10   1500  2025      3   10
3    104 2025-04-25   2200  2025      4   25

## Extract Day of Week

In [13]:
df['Day_Name'] = df['Date'].dt.day_name()
df

   Order       Date  Sales  Year  Month  Day   Day_Name
0    101 2025-01-15   1200  2025      1   15  Wednesday
1    102 2025-02-20   1800  2025      2   20   Thursday
2    103 2025-03-10   1500  2025      3   10     Monday
3    104 2025-04-25   2200  2025      4   25     Friday

## Filter by Date

In [14]:
df[(df['Date'] >= '2025-02-01') & (df['Date'] <= '2025-03-31')]

   Order       Date  Sales  Year  Month  Day  Day_Name
1    102 2025-02-20   1800  2025      2   20  Thursday
2    103 2025-03-10   1500  2025      3   10    Monday

## Sort by Date

In [15]:
df.sort_values('Date', ascending = False)

   Order       Date  Sales  Year  Month  Day   Day_Name
3    104 2025-04-25   2200  2025      4   25     Friday
2    103 2025-03-10   1500  2025      3   10     Monday
1    102 2025-02-20   1800  2025      2   20   Thursday
0    101 2025-01-15   1200  2025      1   15  Wednesday

## Gruop by Month

In [17]:
monthly_sales = df.groupby(df['Date'].dt.month)['Sales'].sum()
monthly_sales

Date
1    1200
2    1800
3    1500
4    2200
Name: Sales, dtype: int64

## Creat a Date Range

In [19]:
dates = pd.date_range(
    start ='2025-01-01',
    end = '2025-01-10'
)
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[us]', freq='D')