# Group by Aggregation

## Create DataFrame

In [4]:
import pandas as pd
df = pd.DataFrame({
    'Department': ['IT', 'IT', 'Sales', 'Sales', 'HR', 'HR'],
    'Employees': ['Ali', 'Sara', 'Reza', 'Nima', 'Mina', 'Omid'],
    'Salary': [3000, 3500, 2800, 3200, 2500, 2700],
    'Experience': [2, 4, 3, 5, 2, 6]
})
df

  Department Employees  Salary  Experience
0         IT       Ali    3000           2
1         IT      Sara    3500           4
2      Sales      Reza    2800           3
3      Sales      Nima    3200           5
4         HR      Mina    2500           2
5         HR      Omid    2700           6

## Group by One Column

In [5]:
df.groupby('Department')

In [6]:
# average salary 
df.groupby('Department')['Salary'].mean()

Department
HR       2600.0
IT       3250.0
Sales    3000.0
Name: Salary, dtype: float64

In [7]:
# Total salary
df.groupby('Department')['Salary'].sum()

Department
HR       5200
IT       6500
Sales    6000
Name: Salary, dtype: int64

## Multiple Aggregations

In [9]:
df.groupby('Department')['Salary'].agg(['mean', 'max', 'min', 'sum', 'count'])

              mean   max   min   sum  count
Department
HR          2600.0  2700  2500  5200      2
IT          3250.0  3500  3000  6500      2
Sales       3000.0  3200  2800  6000      2

## Group Multiple Columns

In [12]:
df.groupby(['Department', 'Experience'])['Salary'].mean()

Department  Experience
HR          2             2500.0
            6             2700.0
IT          2             3000.0
            4             3500.0
Sales       3             2800.0
            5             3200.0
Name: Salary, dtype: float64

## Aggregation on Multiple Columns

In [14]:
df.groupby('Department').agg({
    'Salary': ['min', 'max'],
'Experience': ['mean', 'count']})

           Salary       Experience
              min   max       mean count
Department
HR           2500  2700        4.0     2
IT           3000  3500        3.0     2
Sales        2800  3200        4.0     2

## Named Aggregation

In [15]:
df.groupby('Department').agg(Avg = ('Salary', 'mean'),
                            maxi = ('Salary', 'max'),
                            mini = ('Salary', 'min'),
                            sumi = ('Salary', 'sum'))

               Avg  maxi  mini  sumi
Department
HR          2600.0  2700  2500  5200
IT          3250.0  3500  3000  6500
Sales       3000.0  3200  2800  6000

## GroupBy + Sort

In [17]:
result = (df.groupby('Department')['Salary'].mean().sort_values(ascending = False))
result

Department
IT       3250.0
Sales    3000.0
HR       2600.0
Name: Salary, dtype: float64