# Merge, Join and Concatenation

## Creat DataFrame

In [1]:
import pandas as pd

customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4],
    "Name": ["Ali", "Sara", "Reza", "Mina"]
})

orders = pd.DataFrame({
    "Customer_ID": [1, 2, 2, 4],
    "Product": ["Laptop", "Phone", "Mouse", "Keyboard"],
    "Amount": [1200, 800, 50, 100]
})

customers

   Customer_ID  Name
0            1   Ali
1            2  Sara
2            3  Reza
3            4  Mina

## Inner Merge

In [2]:
merged = pd.merge(
    customers,
    orders,
    on = 'Customer_ID',
    how = 'inner'
)
merged

   Customer_ID  Name   Product  Amount
0            1   Ali    Laptop    1200
1            2  Sara     Phone     800
2            2  Sara     Mouse      50
3            4  Mina  Keyboard     100

## Left Merge - Right Merge

In [4]:
# Left merge keep all the left values
left = pd.merge(
    customers,
    orders,
    on = 'Customer_ID',
    how= 'left'
) 
left

   Customer_ID  Name   Product  Amount
0            1   Ali    Laptop  1200.0
1            2  Sara     Phone   800.0
2            2  Sara     Mouse    50.0
3            3  Reza       NaN     NaN
4            4  Mina  Keyboard   100.0

In [5]:
# right merge keep all the right values
right = pd.merge(
    customers,
    orders,
    on = 'Customer_ID',
    how= 'right'
) 
right

   Customer_ID  Name   Product  Amount
0            1   Ali    Laptop    1200
1            2  Sara     Phone     800
2            2  Sara     Mouse      50
3            4  Mina  Keyboard     100

## Outer Merge

In [6]:
# outer keep all the values in both dataframes

merged = pd.merge(
    customers,
    orders,
    on = 'Customer_ID',
    how = 'outer'
)
merged

   Customer_ID  Name   Product  Amount
0            1   Ali    Laptop  1200.0
1            2  Sara     Phone   800.0
2            2  Sara     Mouse    50.0
3            3  Reza       NaN     NaN
4            4  Mina  Keyboard   100.0

## Merge with Diffrent Column Names

In [8]:
# New Data
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4],
    "Name": ["Ali", "Sara", "Reza", "Mina"]
})

orders = pd.DataFrame({
    "Client_ID": [1, 2, 2, 4],
    "Product": ["Laptop", "Phone", "Mouse", "Keyboard"],
    "Amount": [1200, 800, 50, 100]
})

merged = pd.merge(
    customers,
    orders,
    left_on = 'Customer_ID',
    right_on = 'Client_ID',
    how = 'inner'
)
merged

   Customer_ID  Name  Client_ID   Product  Amount
0            1   Ali          1    Laptop    1200
1            2  Sara          2     Phone     800
2            2  Sara          2     Mouse      50
3            4  Mina          4  Keyboard     100

## Concatenate Rows

In [11]:
df1 = pd.DataFrame({
    'Name': ['Ali', 'Sara'],
    'Sales': [1000, 1500]
})

df2 = pd.DataFrame({
    'Name': ['Reza', 'Mina'],
    'Sales': [1200, 1800]
})

result = pd.concat([df1, df2], ignore_index = True)

result

   Name  Sales
0   Ali   1000
1  Sara   1500
2  Reza   1200
3  Mina   1800

## Concatenate Clumns

In [12]:
result = pd.concat([df1, df2], axis = 1)

result

   Name  Sales  Name  Sales
0   Ali   1000  Reza   1200
1  Sara   1500  Mina   1800