# Pivot Table and Crosstab

In [1]:
import pandas as pd

## Creat DataFrame

In [2]:
df = pd.DataFrame({
    "Department": ["IT", "IT", "Sales", "Sales", "HR", "HR", "IT", "Sales"],
    "Gender": ["Male", "Female", "Male", "Female", "Female", "Male", "Male", "Female"],
    "Salary": [3000, 3500, 2800, 3200, 2500, 2700, 3300, 3100],
    "Experience": [2, 4, 3, 5, 2, 6, 4, 3]
})

df

  Department  Gender  Salary  Experience
0         IT    Male    3000           2
1         IT  Female    3500           4
2      Sales    Male    2800           3
3      Sales  Female    3200           5
4         HR  Female    2500           2
5         HR    Male    2700           6
6         IT    Male    3300           4
7      Sales  Female    3100           3

## Basic Pivot Table

In [3]:
pd.pivot_table(
    df,
    values = 'Salary',
    index = 'Department',
    aggfunc = 'mean'
)

                 Salary
Department
HR          2600.000000
IT          3266.666667
Sales       3033.333333

## Multiple Aggregations

In [4]:
pd.pivot_table(
    df,
    values = 'Salary',
    index = 'Department',
    aggfunc = ['mean', 'max', 'min']
)

                   mean    max    min
                 Salary Salary Salary
Department
HR          2600.000000   2700   2500
IT          3266.666667   3500   3000
Sales       3033.333333   3200   2800

## Add Columns

In [5]:
pd.pivot_table(
    df,
    values = 'Salary',
    columns = 'Gender',
    index = 'Department',
    aggfunc = 'mean'
)

Gender      Female    Male
Department
HR          2500.0  2700.0
IT          3500.0  3150.0
Sales       3150.0  2800.0

## Multiple Values

In [8]:
pd.pivot_table(
    df,
    values = ['Salary', 'Experience'],
    index = 'Department',
    aggfunc = 'mean'
)

            Experience       Salary
Department
HR            4.000000  2600.000000
IT            3.333333  3266.666667
Sales         3.666667  3033.333333

## Fill Missing Values

In [9]:
pd.pivot_table(
    df,
    values = ['Salary', 'Experience'],
    columns = 'Gender',
    index = 'Department',
    aggfunc = 'mean',
    fill_value = 0
)

           Experience       Salary
Gender         Female Male  Female    Male
Department
HR                2.0  6.0  2500.0  2700.0
IT                4.0  3.0  3500.0  3150.0
Sales             4.0  3.0  3150.0  2800.0

## Crosstab

In [11]:
pd.crosstab(
    df['Department'],
    df['Gender']
)

Gender      Female  Male
Department
HR               1     1
IT               1     2
Sales            2     1

## Crosstab wuth Percentage

In [15]:
pd.crosstab(
    df['Department'],
    df['Gender'],
    normalize = 'index'
) *100

Gender         Female       Male
Department
HR          50.000000  50.000000
IT          33.333333  66.666667
Sales       66.666667  33.333333

## Pivot Table with Multiple Indexes

In [16]:
pd.pivot_table(
    df,
    values = 'Salary',
    index = ['Department', 'Gender'],
    aggfunc = 'mean'
)

                   Salary
Department Gender
HR         Female  2500.0
           Male    2700.0
IT         Female  3500.0
           Male    3150.0
Sales      Female  3150.0
           Male    2800.0