# Missing Data

In [31]:
import pandas as pd
import numpy as np

## Creat DataFrame

In [32]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Ali", "Sara", "Reza", "Mina", "Omid"],
    "Age": [25, np.nan, 30, 28, np.nan],
    "Salary": [3000, 3500, np.nan, 2800, 3200],
    "City": ["Tehran", "Mashhad", np.nan, "Tabriz", "Tehran"]
})

df

   Name   Age  Salary     City
0   Ali  25.0  3000.0   Tehran
1  Sara   NaN  3500.0  Mashhad
2  Reza  30.0     NaN      NaN
3  Mina  28.0  2800.0   Tabriz
4  Omid   NaN  3200.0   Tehran

## Detect Missing Values

In [33]:
df.isna()

    Name    Age  Salary   City
0  False  False   False  False
1  False   True   False  False
2  False  False    True   True
3  False  False   False  False
4  False   True   False  False

In [34]:
df.isnull()

    Name    Age  Salary   City
0  False  False   False  False
1  False   True   False  False
2  False  False    True   True
3  False  False   False  False
4  False   True   False  False

## Count Missing Values

In [35]:
df.isna().sum()

Name      0
Age       2
Salary    1
City      1
dtype: int64

## Check if DataFrame Has Missing Values

In [36]:
df.isna().any()

Name      False
Age        True
Salary     True
City       True
dtype: bool

In [37]:
df.isna().any().any()

np.True_

## Remove Rows with Misiing Values

In [38]:
df_clean = df.dropna()

df_clean

   Name   Age  Salary    City
0   Ali  25.0  3000.0  Tehran
3  Mina  28.0  2800.0  Tabriz

## Remove Rows Based on Specific Column

In [39]:
df_clean = df.dropna(subset = ['Salary'])

df_clean

   Name   Age  Salary     City
0   Ali  25.0  3000.0   Tehran
1  Sara   NaN  3500.0  Mashhad
3  Mina  28.0  2800.0   Tabriz
4  Omid   NaN  3200.0   Tehran

## Fill Missing Values

In [40]:
df['Age_new'] = df['Age'].fillna(0)
df

   Name   Age  Salary     City  Age_new
0   Ali  25.0  3000.0   Tehran     25.0
1  Sara   NaN  3500.0  Mashhad      0.0
2  Reza  30.0     NaN      NaN     30.0
3  Mina  28.0  2800.0   Tabriz     28.0
4  Omid   NaN  3200.0   Tehran      0.0

## Fill with Mean

In [41]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df

   Name   Age  Salary     City  Age_new
0   Ali  25.0  3000.0   Tehran     25.0
1  Sara   NaN  3500.0  Mashhad      0.0
2  Reza  30.0  3125.0      NaN     30.0
3  Mina  28.0  2800.0   Tabriz     28.0
4  Omid   NaN  3200.0   Tehran      0.0

## Fill with Median

In [42]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df

   Name   Age  Salary     City  Age_new
0   Ali  25.0  3000.0   Tehran     25.0
1  Sara  28.0  3500.0  Mashhad      0.0
2  Reza  30.0  3125.0      NaN     30.0
3  Mina  28.0  2800.0   Tabriz     28.0
4  Omid  28.0  3200.0   Tehran      0.0

## Fill Categorical Data

In [43]:
df['city_un'] = df['City'].fillna('Unknown')
df

   Name   Age  Salary     City  Age_new  city_un
0   Ali  25.0  3000.0   Tehran     25.0   Tehran
1  Sara  28.0  3500.0  Mashhad      0.0  Mashhad
2  Reza  30.0  3125.0      NaN     30.0  Unknown
3  Mina  28.0  2800.0   Tabriz     28.0   Tabriz
4  Omid  28.0  3200.0   Tehran      0.0   Tehran

## Forward Fill

In [44]:
df['City'] = df['City'].ffill()
df

   Name   Age  Salary     City  Age_new  city_un
0   Ali  25.0  3000.0   Tehran     25.0   Tehran
1  Sara  28.0  3500.0  Mashhad      0.0  Mashhad
2  Reza  30.0  3125.0  Mashhad     30.0  Unknown
3  Mina  28.0  2800.0   Tabriz     28.0   Tabriz
4  Omid  28.0  3200.0   Tehran      0.0   Tehran

## Backward Fill

In [45]:
df['City'] = df['City'].bfill()
df

   Name   Age  Salary     City  Age_new  city_un
0   Ali  25.0  3000.0   Tehran     25.0   Tehran
1  Sara  28.0  3500.0  Mashhad      0.0  Mashhad
2  Reza  30.0  3125.0  Mashhad     30.0  Unknown
3  Mina  28.0  2800.0   Tabriz     28.0   Tabriz
4  Omid  28.0  3200.0   Tehran      0.0   Tehran