# Duplicate Data

In [1]:
import pandas as pd

## Creat DataFrame

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ali", "Sara", "Reza", "Ali", "Mina", "Sara"],
    "Age": [25, 30, 28, 25, 32, 30],
    "City": ["Tehran", "Mashhad", "Tabriz", "Tehran", "Shiraz", "Mashhad"],
    "Salary": [3000, 3500, 2800, 3000, 4000, 3500]
})

df

   Name  Age     City  Salary
0   Ali   25   Tehran    3000
1  Sara   30  Mashhad    3500
2  Reza   28   Tabriz    2800
3   Ali   25   Tehran    3000
4  Mina   32   Shiraz    4000
5  Sara   30  Mashhad    3500

## Detect Duplicates

In [3]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

## Count Duplicates

In [5]:
df.duplicated().sum()

np.int64(2)

## Show Duplicate Rows

In [6]:
df[df.duplicated()]

   Name  Age     City  Salary
3   Ali   25   Tehran    3000
5  Sara   30  Mashhad    3500

## Remove Duplicates

In [10]:
df_clean = df.drop_duplicates()
df_clean

   Name  Age     City  Salary
0   Ali   25   Tehran    3000
1  Sara   30  Mashhad    3500
2  Reza   28   Tabriz    2800
4  Mina   32   Shiraz    4000

## Duplicate Based on Specific Columns

In [11]:
df[df.duplicated('Name', keep = False)]

   Name  Age     City  Salary
0   Ali   25   Tehran    3000
1  Sara   30  Mashhad    3500
3   Ali   25   Tehran    3000
5  Sara   30  Mashhad    3500

## Keep First or Last

In [13]:
df_clean = df.drop_duplicates(
    subset = ['Name'],
    keep = 'first'
)

df_clean

   Name  Age     City  Salary
0   Ali   25   Tehran    3000
1  Sara   30  Mashhad    3500
2  Reza   28   Tabriz    2800
4  Mina   32   Shiraz    4000

In [14]:
df_clean = df.drop_duplicates(
    subset = ['Name'],
    keep = 'last'
)

df_clean

   Name  Age     City  Salary
2  Reza   28   Tabriz    2800
3   Ali   25   Tehran    3000
4  Mina   32   Shiraz    4000
5  Sara   30  Mashhad    3500

## Remove Duplicates Based on Multiple Columns

In [15]:
df_clean = df.drop_duplicates(subset = ['Name', 'Age'])
df_clean

   Name  Age     City  Salary
0   Ali   25   Tehran    3000
1  Sara   30  Mashhad    3500
2  Reza   28   Tabriz    2800
4  Mina   32   Shiraz    4000