# Data Type Conversion

In [1]:
import numpy as np
import pandas as pd

## Checking Data Types

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "name": ["Ali", "Sara", "Reza", "Mina"],
    "age": ["25", "30", "28", "35"],
    "salary": ["4500.5", "5200.0", "4800.75", "6100.25"],
    "active": [1, 0, 1, 1]
})

df

   name age   salary  active
0   Ali  25   4500.5       1
1  Sara  30   5200.0       0
2  Reza  28  4800.75       1
3  Mina  35  6100.25       1

In [3]:
df.dtypes

name        str
age         str
salary      str
active    int64
dtype: object

## Converting to integer

In [4]:
df['age'] = df['age'].astype(int)

df.dtypes

name        str
age       int64
salary      str
active    int64
dtype: object

## Converting to float

In [5]:
df['salary'] = df['salary'].astype(float)

df.dtypes

name          str
age         int64
salary    float64
active      int64
dtype: object

## Using 'pd.to_numeric'

In [6]:
df2 = pd.DataFrame({
    "age": ["25", "30", "unknown", "35"]
})

df2

       age
0       25
1       30
2  unknown
3       35

In [10]:
# Not working because of 'unknown' values
df2['age'] = df2['age'].astype(int)

ValueError: invalid literal for int() with base 10: 'unknown'

In [11]:
# Convert invalid values to NAN

df2['age'] = pd.to_numeric(df2['age'], errors = 'coerce')

df2

    age
0  25.0
1  30.0
2   NaN
3  35.0

## Converting to string

In [12]:
df['age'] = df['age'].astype(str)

## Boolean Converting

In [13]:
df['active']

0    1
1    0
2    1
3    1
Name: active, dtype: int64

In [14]:
df['active'] = df['active'].astype(bool)

df['active']

0     True
1    False
2     True
3     True
Name: active, dtype: bool

## Converting Multiple Columns

In [17]:
df = df.astype({
    'age': int,
    'salary': float
})

df

   name  age   salary  active
0   Ali   25  4500.50    True
1  Sara   30  5200.00   False
2  Reza   28  4800.75    True
3  Mina   35  6100.25    True

## Numeriv Conversion to Real Data

In [18]:
df3 = pd.DataFrame({
    "salary": ["$4,500", "$5,200", "$4,800", "$6,100"]
})

df3

   salary
0  $4,500
1  $5,200
2  $4,800
3  $6,100

In [19]:
# Remove currency symbols and cammas
df3['salary'] = df3['salary'].str.replace('$', '', regex = False)
df3['salary'] = df3['salary'].str.replace(',', '', regex = False)

df3['salary'] = pd.to_numeric(df3['salary'])

df3

   salary
0    4500
1    5200
2    4800
3    6100

## Category Data Type

In [21]:
df4 = pd.DataFrame({
    "city": ["Baku", "Tehran", "Baku", "Baku", "Tehran"]
})

df4

     city
0    Baku
1  Tehran
2    Baku
3    Baku
4  Tehran

In [23]:
# Convert repeated values to category

df4["city"] = df4["city"].astype("category")

df4.dtypes

city    category
dtype: object