# apply() & map()

In [1]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Ali", "Sara", "Reza", "Mina"],
    "age": [25, 30, 28, 35],
    "salary": [4500, 5200, 4800, 6100]
})

df

   name  age  salary
0   Ali   25    4500
1  Sara   30    5200
2  Reza   28    4800
3  Mina   35    6100

## Using map()

In [2]:
df['age'] = df['age'].map(lambda x: x + 1)

df

   name  age  salary
0   Ali   26    4500
1  Sara   31    5200
2  Reza   29    4800
3  Mina   36    6100

## map() with a Function

In [5]:
def tax(salary):
    return salary * 1.1

In [6]:
df['salary'] = df['salary'].map(tax)

df

   name  age  salary
0   Ali   26  5445.0
1  Sara   31  6292.0
2  Reza   29  5808.0
3  Mina   36  7381.0

## map() with Dictionary

In [7]:
df2 = pd.DataFrame({
    "name": ["Ali", "Sara", "Reza", "Mina"],
    "gender": ["M", "F", "M", "F"]
})

df2

   name gender
0   Ali      M
1  Sara      F
2  Reza      M
3  Mina      F

In [8]:
gender = {
    "M": "Male",
    "F": "Female"
}

# Map codes to readable labels
df2["gender"] = df2["gender"].map(gender)

df2

   name  gender
0   Ali    Male
1  Sara  Female
2  Reza    Male
3  Mina  Female

## Using apply()

In [11]:
def salary_level(salary):
    if salary > 5500:
        return 'High'
    else:
        return 'Low'

In [12]:
df['salary_level'] = df['salary'].apply(salary_level)

df

   name  age  salary salary_level
0   Ali   26  5445.0          Low
1  Sara   31  6292.0         High
2  Reza   29  5808.0         High
3  Mina   36  7381.0         High

## apply() with Lambda

In [13]:
df['age_group'] = df['age'].apply(lambda x: 'Young' if x < 30 else 'Adult')

df

   name  age  salary salary_level age_group
0   Ali   26  5445.0          Low     Young
1  Sara   31  6292.0         High     Adult
2  Reza   29  5808.0         High     Young
3  Mina   36  7381.0         High     Adult

## apply() on Rows

In [14]:
def score(row):
    return row['age'] + row['salary'] / 1000

In [16]:
df['score'] = df.apply(score, axis = 1)
df

   name  age  salary salary_level age_group   score
0   Ali   26  5445.0          Low     Young  31.445
1  Sara   31  6292.0         High     Adult  37.292
2  Reza   29  5808.0         High     Young  34.808
3  Mina   36  7381.0         High     Adult  43.381

## axis = 0 VS axis = 1

In [17]:
# axis = 0 --> Down   --> Columns
# axis = 1 --> Across --> Rows

## Practical Example

In [18]:
sales = pd.DataFrame({
    "product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "price": [1200, 25, 80, 300],
    "quantity": [2, 10, 5, 3]
})

sales

    product  price  quantity
0    Laptop   1200         2
1     Mouse     25        10
2  Keyboard     80         5
3   Monitor    300         3

In [19]:
# Calculate Total Sales
sales['total'] = sales.apply(lambda row: row['price'] * row['quantity'], axis = 1)

sales

    product  price  quantity  total
0    Laptop   1200         2   2400
1     Mouse     25        10    250
2  Keyboard     80         5    400
3   Monitor    300         3    900

In [20]:
# OR sales['total'] = sales['price'] * sales['quantity']

## apply() VS Vectorization

In [22]:
df['salary'] * 1.1  # --> better

0    5989.5
1    6921.2
2    6388.8
3    8119.1
Name: salary, dtype: float64

In [23]:
df['salary'].apply(lambda x: x * 1.1)  # --> slower

0    5989.5
1    6921.2
2    6388.8
3    8119.1
Name: salary, dtype: float64