# groupby() and Grouped Analysis

In [1]:
import pandas as pd

df = pd.DataFrame({
    "department": ["IT", "IT", "HR", "HR", "Sales", "Sales"],
    "employee": ["Ali", "Reza", "Sara", "Mina", "John", "David"],
    "salary": [5000, 6000, 4500, 5200, 4000, 5500],
    "age": [25, 30, 28, 35, 24, 32]
})

df

  department employee  salary  age
0         IT      Ali    5000   25
1         IT     Reza    6000   30
2         HR     Sara    4500   28
3         HR     Mina    5200   35
4      Sales     John    4000   24
5      Sales    David    5500   32

## Basic groupby()

In [4]:
df.groupby('department')

In [5]:
# Calculate average salary per department

df.groupby('department')['salary'].mean()

department
HR       4850.0
IT       5500.0
Sales    4750.0
Name: salary, dtype: float64

## sum()

In [8]:
# Calculate total salary per department

df.groupby('department')['salary'].sum()

department
HR        9700
IT       11000
Sales     9500
Name: salary, dtype: int64

## Count()

In [10]:
df.groupby('department')['employee'].count()

department
HR       2
IT       2
Sales    2
Name: employee, dtype: int64

## min() & max()

In [11]:
# Find the minimum salary per department

df.groupby('department')['salary'].min()

department
HR       4500
IT       5000
Sales    4000
Name: salary, dtype: int64

In [12]:
# Find the maximum salary per department

df.groupby('department')['salary'].max()

department
HR       5200
IT       6000
Sales    5500
Name: salary, dtype: int64

## Multiple Aggregations

In [13]:
df.groupby('department')['salary'].agg(['min', 'max', 'count', 'mean', 'sum'])

             min   max  count    mean    sum
department
HR          4500  5200      2  4850.0   9700
IT          5000  6000      2  5500.0  11000
Sales       4000  5500      2  4750.0   9500

## Grouping Multiple Columns

In [14]:
df.groupby('department')[['salary', 'age']].mean()

            salary   age
department
HR          4850.0  31.5
IT          5500.0  27.5
Sales       4750.0  28.0

## Group by Multiple Columns

In [15]:
sales = pd.DataFrame({
    "city": ["Baku", "Baku", "Tehran", "Tehran", "Baku", "Tehran"],
    "product": ["Laptop", "Mouse", "Laptop", "Mouse", "Laptop", "Laptop"],
    "sales": [1200, 300, 1500, 400, 1800, 1300]
})

sales

     city product  sales
0    Baku  Laptop   1200
1    Baku   Mouse    300
2  Tehran  Laptop   1500
3  Tehran   Mouse    400
4    Baku  Laptop   1800
5  Tehran  Laptop   1300

In [16]:
sales.groupby(['city', 'product'])['sales'].sum()

city    product
Baku    Laptop     3000
        Mouse       300
Tehran  Laptop     2800
        Mouse       400
Name: sales, dtype: int64

## reset_index()

In [17]:
result = df.groupby('department')['salary'].mean()
result

department
HR       4850.0
IT       5500.0
Sales    4750.0
Name: salary, dtype: float64

In [18]:
result = result.reset_index()

result

  department  salary
0         HR  4850.0
1         IT  5500.0
2      Sales  4750.0

## Named Aggregations

In [19]:
result = df.groupby('department').agg(avg_salary = ('salary', 'mean'),
                                     max_salary = ('salary', 'max'),
                                     min_salary = ('salary', 'min'),
                                     employee_count = ('employee', 'count'))

result

            avg_salary  max_salary  min_salary  employee_count
department
HR              4850.0        5200        4500               2
IT              5500.0        6000        5000               2
Sales           4750.0        5500        4000               2

## Sorting Grouped Results

In [22]:
result = (
    df.groupby('department')['salary'].mean().sort_values(ascending = False)
)

result

department
IT       5500.0
HR       4850.0
Sales    4750.0
Name: salary, dtype: float64

## groupby() Mental Model

df.groupby('column')['value'].operation()