# Pivot Table

In [1]:
import pandas as pd

sales = pd.DataFrame({
    "city": ["Baku", "Baku", "Baku", "Tehran", "Tehran", "Tehran"],
    "product": ["Laptop", "Mouse", "Laptop", "Laptop", "Mouse", "Mouse"],
    "quantity": [2, 10, 3, 4, 15, 8],
    "revenue": [2400, 300, 3600, 4800, 450, 240]
})

sales

     city product  quantity  revenue
0    Baku  Laptop         2     2400
1    Baku   Mouse        10      300
2    Baku  Laptop         3     3600
3  Tehran  Laptop         4     4800
4  Tehran   Mouse        15      450
5  Tehran   Mouse         8      240

## Basic pivot_table()

In [2]:
pivot = pd.pivot_table(
    sales,
    values = 'revenue',
    index = 'city',
    columns = 'product',
    aggfunc = 'sum'
)
pivot

product  Laptop  Mouse
city
Baku       6000    300
Tehran     4800    690

## Using mean()

In [3]:
pivot = pd.pivot_table(
    sales,
    values = 'revenue',
    index = 'city',
    columns = 'product',
    aggfunc = 'mean'
)
pivot

product  Laptop  Mouse
city
Baku     3000.0  300.0
Tehran   4800.0  345.0

## Using Multiple Aggregations

In [4]:
pivot = pd.pivot_table(
    sales,
    values = 'revenue',
    index = 'city',
    columns = 'product',
    aggfunc = ['min', 'max', 'mean']
)
pivot

           min          max          mean
product Laptop Mouse Laptop Mouse  Laptop  Mouse
city
Baku      2400   300   3600   300  3000.0  300.0
Tehran    4800   240   4800   450  4800.0  345.0

## Multiple Values

In [5]:
pivot = pd.pivot_table(
    sales,
    values = ['revenue', 'quantity'], 
    index = 'city',
    columns = 'product',
    aggfunc = 'sum'
)
pivot

        quantity       revenue
product   Laptop Mouse  Laptop Mouse
city
Baku           5    10    6000   300
Tehran         4    23    4800   690

## Adding Total with margins

In [6]:
# Add grand totals

pivot = pd.pivot_table(
    sales,
    values = 'revenue',
    index = 'city',
    columns = 'product',
    aggfunc = 'sum',
    margins = True
)
pivot

product  Laptop  Mouse    All
city
Baku       6000    300   6300
Tehran     4800    690   5490
All       10800    990  11790

## fill_value

In [7]:
# Replace missing combinations with 'sth'

pivot = pd.pivot_table(
    sales,
    values = 'revenue',
    index = 'city',
    columns = 'product',
    aggfunc = 'sum',
    fill_value = 0
)
pivot

product  Laptop  Mouse
city
Baku       6000    300
Tehran     4800    690

## Practical Analysis

In [8]:
sales = pd.DataFrame({
    "city": ["Baku", "Baku", "Baku", "Tehran", "Tehran", "Tehran"],
    "product": ["Laptop", "Mouse", "Keyboard", "Laptop", "Mouse", "Keyboard"],
    "revenue": [2400, 300, 400, 4800, 450, 600]
})

sales

     city   product  revenue
0    Baku    Laptop     2400
1    Baku     Mouse      300
2    Baku  Keyboard      400
3  Tehran    Laptop     4800
4  Tehran     Mouse      450
5  Tehran  Keyboard      600

In [9]:
report = pd.pivot_table(
    sales,
    values="revenue",
    index="city",
    columns="product",
    aggfunc="sum",
    fill_value=0,
    margins=True
)

report

product  Keyboard  Laptop  Mouse   All
city
Baku          400    2400    300  3100
Tehran        600    4800    450  5850
All          1000    7200    750  8950

## groupby() VS pivot_table()

groupby()
    ↓
Grouped Analysis

pivot_table()
    ↓
Summary Table / Report

## Sorting

In [13]:
report = pd.pivot_table(
    sales,
    values = 'revenue',
    index = 'city',
    columns = 'product',
    aggfunc = 'sum'
).sort_values('Laptop', ascending = False)
report

product  Keyboard  Laptop  Mouse
city
Tehran        600    4800    450
Baku          400    2400    300