# Pandas Basics

In [1]:
# import pandas
import pandas as pd

# Series

In [3]:
# Creat a Series
s = pd.Series([10, 20, 30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
# Custom index
s = pd.Series(
    [1, 2, 3],
    index = ['A','B','C'])
s

A    1
B    2
C    3
dtype: int64

In [5]:
# Accws by labe;
s['B']

np.int64(2)

In [6]:
# Acces by position
s.iloc[1]

np.int64(2)

# DataFrame

In [20]:
# Creat a DataFrame
df = pd.DataFrame({
    'Name': ['Ali','Sara','Reza'],
    'Age': [25, 30, 22],
    'Score': [85, 92, 78]
})
df

   Name  Age  Score
0   Ali   25     85
1  Sara   30     92
2  Reza   22     78

In [21]:
# Show first rows
df.head(2)

   Name  Age  Score
0   Ali   25     85
1  Sara   30     92

In [22]:
# Show last rows
df.tail(2)

   Name  Age  Score
1  Sara   30     92
2  Reza   22     78

# Basic DataFrame Information

In [23]:
# DataFrame shape
df.shape

(3, 3)

In [24]:
# Clomun names
df.columns

Index(['Name', 'Age', 'Score'], dtype='str')

In [25]:
# Data type
df.dtypes

Name       str
Age      int64
Score    int64
dtype: object

In [26]:
# DataFrame information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Score   3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 215.0 bytes

In [27]:
# Statistical information
df.describe()

             Age  Score
count   3.000000    3.0
mean   25.666667   85.0
std     4.041452    7.0
min    22.000000   78.0
25%    23.500000   81.5
50%    25.000000   85.0
75%    27.500000   88.5
max    30.000000   92.0

# Selecting Columns

In [28]:
# select one column
df['Age']

0    25
1    30
2    22
Name: Age, dtype: int64

In [29]:
# select multiple columns
df[['Name','Score']]

   Name  Score
0   Ali     85
1  Sara     92
2  Reza     78

# Selecting Rows

In [34]:
# Select by position
df.iloc[0]

Name     Ali
Age       25
Score     85
Name: 0, dtype: object

In [35]:
# Select multiple rows
df.iloc[0:2]

   Name  Age  Score
0   Ali   25     85
1  Sara   30     92

In [36]:
# Select specific rowa and columns
df.iloc[0:2,0:2]

   Name  Age
0   Ali   25
1  Sara   30

# Basic Filtering

# Filter rows
df[df['Age'] > 24]

In [40]:
# Multiple condition
df[(df['Age'] > 24)&(df['Score'] > 85)]

   Name  Age  Score
1  Sara   30     92

In [42]:
# OR condition
df[(df['Age'] > 24)|(df['Score'] > 90)]

   Name  Age  Score
0   Ali   25     85
1  Sara   30     92

# Adding a column

In [43]:
# creat a new column
df['Passed'] = df['Score'] >= 80
df

   Name  Age  Score  Passed
0   Ali   25     85    True
1  Sara   30     92    True
2  Reza   22     78   False

# Simple Data Analysis

In [45]:
# Average score
df['Score'].mean()

np.float64(85.0)

In [46]:
# Maximum score
df['Score'].max()

np.int64(92)

In [47]:
# Number of rows
len(df)

3