# SELECT & Selecting Columns

In [17]:
import psycopg
import pandas as pd
conn = psycopg.connect(
    host = 'localhost',
    port= 5432,
    dbname ='chinook',
    user = 'postgres',
    password = '231165'
)

In [18]:
cur = conn.cursor()

## Select All Culumns

In [19]:
result = pd.read_sql('''
SELECT *
FROM artist
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_12484\273087948.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

     artist_id                                               name
0            1                                              AC/DC
1            2                                             Accept
2            3                                          Aerosmith
3            4                                  Alanis Morissette
4            5                                    Alice In Chains
..         ...                                                ...
270        271   Mela Tenenbaum, Pro Musica Prague & Richard Kapp
271        272                             Emerson String Quartet
272        273  C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...
273        274                                      Nash Ensemble
274        275                              Philip Glass Ensemble

[275 rows x 2 columns]

## SELECT Specific Columns

In [20]:

result = pd.read_sql('''
SELECT name
FROM artist
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_12484\1101547818.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

                                                  name
0                                                AC/DC
1                                               Accept
2                                            Aerosmith
3                                    Alanis Morissette
4                                      Alice In Chains
..                                                 ...
270   Mela Tenenbaum, Pro Musica Prague & Richard Kapp
271                             Emerson String Quartet
272  C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...
273                                      Nash Ensemble
274                              Philip Glass Ensemble

[275 rows x 1 columns]

## Rename Columns with AS

In [21]:
result = pd.read_sql('''
SELECT artist_id AS ID, name AS Name
FROM artist
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_12484\715413724.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

      id                                               name
0      1                                              AC/DC
1      2                                             Accept
2      3                                          Aerosmith
3      4                                  Alanis Morissette
4      5                                    Alice In Chains
..   ...                                                ...
270  271   Mela Tenenbaum, Pro Musica Prague & Richard Kapp
271  272                             Emerson String Quartet
272  273  C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...
273  274                                      Nash Ensemble
274  275                              Philip Glass Ensemble

[275 rows x 2 columns]

## SELECT Distinct Values

In [22]:
# Select unique values

result = pd.read_sql('''
SELECT DISTINCT country
FROM customer
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_12484\3433196087.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

           country
0        Argentina
1            Spain
2            Italy
3          Hungary
4            India
5          Belgium
6   Czech Republic
7            Chile
8           Sweden
9           Norway
10          France
11             USA
12  United Kingdom
13     Netherlands
14          Brazil
15         Austria
16       Australia
17          Poland
18         Ireland
19         Germany
20         Denmark
21          Canada
22         Finland
23        Portugal

## Combine Multiple Columns

In [23]:
result = pd.read_sql('''
SELECT first_name, last_name, email
FROM customer
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_12484\3107995887.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

   first_name     last_name                          email
0        Luís     Gonçalves           luisg@embraer.com.br
1      Leonie        Köhler          leonekohler@surfeu.de
2    François      Tremblay            ftremblay@gmail.com
3       Bjørn        Hansen          bjorn.hansen@yahoo.no
4   František   Wichterlová       frantisekw@jetbrains.com
5      Helena          Holý                hholy@gmail.com
6      Astrid        Gruber         astrid.gruber@apple.at
7        Daan       Peeters          daan_peeters@apple.be
8        Kara       Nielsen          kara.nielsen@jubii.dk
9     Eduardo       Martins       eduardo@woodstock.com.br
10  Alexandre         Rocha               alero@uol.com.br
11    Roberto       Almeida  roberto.almeida@riotur.gov.br
12   Fernanda         Ramos       fernadaramos4@uol.com.br
13       Mark       Philips             mphilips12@shaw.ca
14   Jennifer      Peterson            jenniferp@rogers.ca
15      Frank        Harris             fharris@google.com
16       Jack         Smith        jacksmith@microsoft.com
17   Michelle        Brooks              michelleb@aol.com
18        Tim         Goyer               tgoyer@apple.com
19        Dan        Miller            dmiller@comcast.com
20      Kathy         Chase            kachase@hotmail.com
21    Heather       Leacock             hleacock@gmail.com
22       John        Gordon         johngordon22@yahoo.com
23      Frank       Ralston             fralston@gmail.com
24     Victor       Stevens             vstevens@yahoo.com
25    Richard    Cunningham       ricunningham@hotmail.com
26    Patrick          Gray           patrick.gray@aol.com
27      Julia       Barnett            jubarnett@gmail.com
28     Robert         Brown               robbrown@shaw.ca
29     Edward       Francis            edfrancis@yachoo.ca
30     Martha          Silk           marthasilk@gmail.com
31      Aaron      Mitchell         aaronmitchell@yahoo.ca
32      Ellie      Sullivan         ellie.sullivan@shaw.ca
33       João     Fernandes            jfernandes@yahoo.pt
34   Madalena       Sampaio              masampaio@sapo.pt
35     Hannah     Schneider      hannah.schneider@yahoo.de
36       Fynn    Zimmermann           fzimmermann@yahoo.de
37     Niklas      Schröder            nschroder@surfeu.de
38    Camille       Bernard       camille.bernard@yahoo.fr
39  Dominique      Lefebvre    dominiquelefebvre@gmail.com
40       Marc        Dubois        marc.dubois@hotmail.com
41      Wyatt        Girard          wyatt.girard@yahoo.fr
42   Isabelle       Mercier      isabelle_mercier@apple.fr
43      Terhi    Hämäläinen      terhi.hamalainen@apple.fi
44   Ladislav        Kovács       ladislav_kovacs@apple.hu
45       Hugh      O'Reilly           hughoreilly@apple.ie
46      Lucas       Mancini         lucas.mancini@yahoo.it
47   Johannes  Van der Berg        johavanderberg@yahoo.nl
48  Stanisław        Wójcik         stanisław.wójcik@wp.pl
49    Enrique         Muñoz         enrique_munoz@yahoo.es
50     Joakim     Johansson      joakim.johansson@yahoo.se
51       Emma         Jones         emma_jones@hotmail.com
52       Phil        Hughes          phil.hughes@gmail.com
53      Steve        Murray          steve.murray@yahoo.uk
54       Mark        Taylor           mark.taylor@yahoo.au
55      Diego     Gutiérrez       diego.gutierrez@yahoo.ar
56       Luis         Rojas             luisrojas@yahoo.cl
57      Manoj        Pareek        manoj.pareek@rediff.com
58       Puja    Srivastava       puja_srivastava@yahoo.in

## Count Rows

In [24]:
result = pd.read_sql('''
SELECT COUNT(*)
FROM customer
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_12484\2983025796.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

   count
0     59

## Close the Cursur

In [25]:
cur.close()