# WHERE & Filtering Data

In [7]:
import psycopg
import pandas as pd
conn = psycopg.connect(
    host = 'localhost',
    port= 5432,
    dbname ='chinook',
    user = 'postgres',
    password = '231165'
)

cur = conn.cursor()

## Basic Filtering with WHERE

In [8]:
# Filter customers by country

result = pd.read_sql('''
SELECT customer_id, first_name, last_name, country
FROM customer
WHERE country = 'USA'
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_6220\3915568401.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

    customer_id first_name   last_name country
0            16      Frank      Harris     USA
1            17       Jack       Smith     USA
2            18   Michelle      Brooks     USA
3            19        Tim       Goyer     USA
4            20        Dan      Miller     USA
5            21      Kathy       Chase     USA
6            22    Heather     Leacock     USA
7            23       John      Gordon     USA
8            24      Frank     Ralston     USA
9            25     Victor     Stevens     USA
10           26    Richard  Cunningham     USA
11           27    Patrick        Gray     USA
12           28      Julia     Barnett     USA

In [9]:
# Filter tracks with a price above 1$

result = pd.read_sql('''
SELECT track_id, name, unit_price
FROM track
WHERE unit_price > 1
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_6220\3239225127.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

     track_id                                    name  unit_price
0        2819  Battlestar Galactica: The Story So Far        1.99
1        2820                  Occupation / Precipice        1.99
2        2821                           Exodus, Pt. 1        1.99
3        2822                           Exodus, Pt. 2        1.99
4        2823                           Collaborators        1.99
..        ...                                     ...         ...
208      3362       There's No Place Like Home, Pt. 1        1.99
209      3363       There's No Place Like Home, Pt. 2        1.99
210      3364       There's No Place Like Home, Pt. 3        1.99
211      3428                          Branch Closing        1.99
212      3429                              The Return        1.99

[213 rows x 3 columns]

## Filtering wuth AND

In [10]:
# Apply multiole conditions with AND

result = pd.read_sql('''
SELECT  name, unit_price, milliseconds
FROM track
WHERE unit_price > 1 AND milliseconds > 300000
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_6220\3047900098.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

                                       name  unit_price  milliseconds
0    Battlestar Galactica: The Story So Far        1.99       2622250
1                    Occupation / Precipice        1.99       5286953
2                             Exodus, Pt. 1        1.99       2621708
3                             Exodus, Pt. 2        1.99       2618000
4                             Collaborators        1.99       2626626
..                                      ...         ...           ...
207       There's No Place Like Home, Pt. 1        1.99       2609526
208       There's No Place Like Home, Pt. 2        1.99       2497956
209       There's No Place Like Home, Pt. 3        1.99       2582957
210                          Branch Closing        1.99       1814855
211                              The Return        1.99       1705080

[212 rows x 3 columns]

## Filtering with OR

In [11]:
# Find customers from USAA or Canada

result = pd.read_sql('''
SELECT customer_id, first_name, last_name, country
FROM customer
WHERE country = 'USA' OR country = 'Canada'
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_6220\1450561915.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

    customer_id first_name   last_name country
0             3   François    Tremblay  Canada
1            14       Mark     Philips  Canada
2            15   Jennifer    Peterson  Canada
3            16      Frank      Harris     USA
4            17       Jack       Smith     USA
5            18   Michelle      Brooks     USA
6            19        Tim       Goyer     USA
7            20        Dan      Miller     USA
8            21      Kathy       Chase     USA
9            22    Heather     Leacock     USA
10           23       John      Gordon     USA
11           24      Frank     Ralston     USA
12           25     Victor     Stevens     USA
13           26    Richard  Cunningham     USA
14           27    Patrick        Gray     USA
15           28      Julia     Barnett     USA
16           29     Robert       Brown  Canada
17           30     Edward     Francis  Canada
18           31     Martha        Silk  Canada
19           32      Aaron    Mitchell  Canada
20           33      Ellie    Sullivan  Canada

## Filtering with BETWEEN

In [12]:
result = pd.read_sql('''
SELECT invoice_id, customer_id, total
FROM invoice
WHERE total BETWEEN 5 AND 10
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_6220\3233023538.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

     invoice_id  customer_id  total
0             3            8   5.94
1             4           14   8.91
2            10           46   5.94
3            11           52   8.91
4            17           25   5.94
..          ...          ...    ...
110         396           18   8.91
111         402           50   5.94
112         403           56   8.91
113         409           29   5.94
114         410           35   8.91

[115 rows x 3 columns]

## Filtering with IN

In [13]:
# Filter using a list of values

result = pd.read_sql('''
SELECT first_name, last_name, country
FROM customer
WHERE country IN ('USA', 'Canada', 'Brazil')
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_6220\1186041974.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

   first_name   last_name country
0        Luís   Gonçalves  Brazil
1    François    Tremblay  Canada
2     Eduardo     Martins  Brazil
3   Alexandre       Rocha  Brazil
4     Roberto     Almeida  Brazil
5    Fernanda       Ramos  Brazil
6        Mark     Philips  Canada
7    Jennifer    Peterson  Canada
8       Frank      Harris     USA
9        Jack       Smith     USA
10   Michelle      Brooks     USA
11        Tim       Goyer     USA
12        Dan      Miller     USA
13      Kathy       Chase     USA
14    Heather     Leacock     USA
15       John      Gordon     USA
16      Frank     Ralston     USA
17     Victor     Stevens     USA
18    Richard  Cunningham     USA
19    Patrick        Gray     USA
20      Julia     Barnett     USA
21     Robert       Brown  Canada
22     Edward     Francis  Canada
23     Martha        Silk  Canada
24      Aaron    Mitchell  Canada
25      Ellie    Sullivan  Canada

## Filtering with LIKE

In [14]:
# Find names starting with a letter

result = pd.read_sql('''
SELECT first_name, last_name
FROM customer
WHERE first_name LIKE 'A%'
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_6220\3292113620.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

  first_name last_name
0     Astrid    Gruber
1  Alexandre     Rocha
2      Aaron  Mitchell

In [15]:
# Find names ending with a letter

result = pd.read_sql('''
SELECT first_name, last_name
FROM customer
WHERE first_name LIKE '%a'
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_6220\151542889.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

  first_name   last_name
0     Helena        Holý
1       Kara     Nielsen
2   Fernanda       Ramos
3      Julia     Barnett
4     Martha        Silk
5   Madalena     Sampaio
6       Emma       Jones
7       Puja  Srivastava

In [16]:
# Perform case-insensitive matching ---> ILIKE

result = pd.read_sql('''
SELECT first_name, last_name
FROM customer
WHERE first_name ILIKE 'a%'
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_6220\2447602366.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

  first_name last_name
0     Astrid    Gruber
1  Alexandre     Rocha
2      Aaron  Mitchell

## Filtering NULL Values

In [17]:
# The ccustomers without a company

result = pd.read_sql('''
SELECT first_name, last_name, company
FROM customer
WHERE company IS NULL
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_6220\829151833.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

   first_name     last_name company
0      Leonie        Köhler    None
1    François      Tremblay    None
2       Bjørn        Hansen    None
3      Helena          Holý    None
4      Astrid        Gruber    None
5        Daan       Peeters    None
6        Kara       Nielsen    None
7    Fernanda         Ramos    None
8    Michelle        Brooks    None
9         Dan        Miller    None
10      Kathy         Chase    None
11    Heather       Leacock    None
12       John        Gordon    None
13      Frank       Ralston    None
14     Victor       Stevens    None
15    Richard    Cunningham    None
16    Patrick          Gray    None
17      Julia       Barnett    None
18     Robert         Brown    None
19     Edward       Francis    None
20     Martha          Silk    None
21      Aaron      Mitchell    None
22      Ellie      Sullivan    None
23       João     Fernandes    None
24   Madalena       Sampaio    None
25     Hannah     Schneider    None
26       Fynn    Zimmermann    None
27     Niklas      Schröder    None
28    Camille       Bernard    None
29  Dominique      Lefebvre    None
30       Marc        Dubois    None
31      Wyatt        Girard    None
32   Isabelle       Mercier    None
33      Terhi    Hämäläinen    None
34   Ladislav        Kovács    None
35       Hugh      O'Reilly    None
36      Lucas       Mancini    None
37   Johannes  Van der Berg    None
38  Stanisław        Wójcik    None
39    Enrique         Muñoz    None
40     Joakim     Johansson    None
41       Emma         Jones    None
42       Phil        Hughes    None
43      Steve        Murray    None
44       Mark        Taylor    None
45      Diego     Gutiérrez    None
46       Luis         Rojas    None
47      Manoj        Pareek    None
48       Puja    Srivastava    None

In [18]:
# The customers with a company

result = pd.read_sql('''
SELECT first_name, last_name, company
FROM customer
WHERE company IS NOT NULL
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_6220\3557225881.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

  first_name    last_name                                           company
0       Luís    Gonçalves  Embraer - Empresa Brasileira de Aeronáutica S.A.
1  František  Wichterlová                                  JetBrains s.r.o.
2    Eduardo      Martins                                  Woodstock Discos
3  Alexandre        Rocha                              Banco do Brasil S.A.
4    Roberto      Almeida                                            Riotur
5       Mark      Philips                                             Telus
6   Jennifer     Peterson                                     Rogers Canada
7      Frank       Harris                                       Google Inc.
8       Jack        Smith                             Microsoft Corporation
9        Tim        Goyer                                        Apple Inc.

## Combine Filtering with COUNT

In [19]:
result = pd.read_sql('''
SELECT COUNT(*)
FROM customer
WHERE country = 'USA'
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_6220\2891447293.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

   count
0     13