# ORDER BY & LIMIT

In [24]:
import psycopg
import pandas as pd
conn = psycopg.connect(
    host = 'localhost',
    port= 5432,
    dbname ='chinook',
    user = 'postgres',
    password = '231165'
)

cur = conn.cursor()

## Introduction to ORDER BY

### Basic ORDER BY

In [25]:
result = pd.read_sql('''
SELECT name
FROM track
ORDER BY name
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_9688\2579985664.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

                                                   name
0                                       'Round Midnight
1                                                   "?"
2                                                  "40"
3     "Eine Kleine Nachtmusik" Serenade In G, K. 525...
4                                               #1 Zero
...                                                 ...
3498                                        ZeroVinteUm
3499                                             Zither
3500                                      Zombie Eaters
3501                                        Zoo Station
3502                                            Zooropa

[3503 rows x 1 columns]

In [26]:
result = pd.read_sql('''
SELECT name
FROM track
ORDER BY name DESC
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_9688\3119951777.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

                                                   name
0                                               Zooropa
1                                           Zoo Station
2                                         Zombie Eaters
3                                                Zither
4                                           ZeroVinteUm
...                                                 ...
3498                                            #1 Zero
3499  "Eine Kleine Nachtmusik" Serenade In G, K. 525...
3500                                               "40"
3501                                                "?"
3502                                    'Round Midnight

[3503 rows x 1 columns]

### Sorting numbers

In [27]:
result = pd.read_sql('''
SELECT name, unit_price
FROM track
ORDER BY unit_price ASC
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_9688\921954137.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

                           name  unit_price
0                 Koyaanisqatsi        0.99
1             Balls to the Wall        0.99
2               Fast As a Shark        0.99
3             Restless and Wild        0.99
4          Princess of the Dawn        0.99
...                         ...         ...
3498              Fire In Space        1.99
3499     War of the Gods, Pt. 1        1.99
3500     War of the Gods, Pt. 2        1.99
3501    The Man With Nine Lives        1.99
3502  Murder On the Rising Star        1.99

[3503 rows x 2 columns]

### Sorting Dates

In [28]:
result = pd.read_sql('''
SELECT invoice_date, total
FROM invoice
ORDER BY invoice_date DESC
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_9688\1222318988.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

    invoice_date  total
0     2025-12-22   1.99
1     2025-12-14  13.86
2     2025-12-09   8.91
3     2025-12-06   5.94
4     2025-12-05   3.96
..           ...    ...
407   2021-01-11  13.86
408   2021-01-06   8.91
409   2021-01-03   5.94
410   2021-01-02   3.96
411   2021-01-01   1.98

[412 rows x 2 columns]

## Sorting by Multiple Columns

In [29]:
result = pd.read_sql('''
SELECT name, unit_price
FROM track
ORDER BY unit_price DESC, name ASC
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_9688\2405170450.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

                                  name  unit_price
0                                  "?"        1.99
1                         ...And Found        1.99
2                    ...In Translation        1.99
3                                 .07%        1.99
4     A Benihana Christmas, Pts. 1 & 2        1.99
...                                ...         ...
3498                       ZeroVinteUm        0.99
3499                            Zither        0.99
3500                     Zombie Eaters        0.99
3501                       Zoo Station        0.99
3502                           Zooropa        0.99

[3503 rows x 2 columns]

## Introduction to LIMIT

In [30]:
result = pd.read_sql('''
SELECT name, unit_price
FROM track
ORDER BY unit_price DESC, name ASC
LIMIT 10
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_9688\180052044.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

                               name  unit_price
0                               "?"        1.99
1                      ...And Found        1.99
2                 ...In Translation        1.99
3                              .07%        1.99
4  A Benihana Christmas, Pts. 1 & 2        1.99
5                 A Day In the Life        1.99
6            A Measure of Salvation        1.99
7              A Tale of Two Cities        1.99
8                         Abandoned        1.99
9                            Adrift        1.99

## Using OFFSET for Pagination

In [31]:
result = pd.read_sql('''
SELECT name, unit_price
FROM track
ORDER BY unit_price DESC, name ASC
LIMIT 10 OFFSET 5
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_9688\2895261309.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

                                     name  unit_price
0                       A Day In the Life        1.99
1                  A Measure of Salvation        1.99
2                    A Tale of Two Cities        1.99
3                               Abandoned        1.99
4                                  Adrift        1.99
5  All the Best Cowboys Have Daddy Issues        1.99
6                      Back from Vacation        1.99
7                         Baltar's Escape        1.99
8                              Basketball        1.99
9             Battlestar Galactica, Pt. 1        1.99

## Handling NULL Values in ORDER BY

In [32]:
result = pd.read_sql('''
SELECT name
FROM track
ORDER BY name ASC NULLS FIRST
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_9688\821441053.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

                                                   name
0                                       'Round Midnight
1                                                   "?"
2                                                  "40"
3     "Eine Kleine Nachtmusik" Serenade In G, K. 525...
4                                               #1 Zero
...                                                 ...
3498                                        ZeroVinteUm
3499                                             Zither
3500                                      Zombie Eaters
3501                                        Zoo Station
3502                                            Zooropa

[3503 rows x 1 columns]

In [33]:
result = pd.read_sql('''
SELECT name
FROM track
ORDER BY name ASC NULLS LAST
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_9688\1681580857.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

                                                   name
0                                       'Round Midnight
1                                                   "?"
2                                                  "40"
3     "Eine Kleine Nachtmusik" Serenade In G, K. 525...
4                                               #1 Zero
...                                                 ...
3498                                        ZeroVinteUm
3499                                             Zither
3500                                      Zombie Eaters
3501                                        Zoo Station
3502                                            Zooropa

[3503 rows x 1 columns]