# Aggregate Functions

In [35]:
import psycopg
import pandas as pd
conn = psycopg.connect(
    host = 'localhost',
    port= 5432,
    dbname ='chinook',
    user = 'postgres',
    password = '231165'
)

cur = conn.cursor()

## COUNT()

In [36]:
# Count all tracks

result = pd.read_sql('''
SELECT COUNT(*) AS total_tracks
FROM track
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_2060\1447565094.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

   total_tracks
0          3503

## COUNT(*) vs COUNT(column)

In [37]:
# Compare total rows with not-NULL values

result = pd.read_sql('''
SELECT COUNT(*) AS total_rows, COUNT(composer) AS track_with_composer
FROM track
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_2060\26043190.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

   total_rows  track_with_composer
0        3503                 2526

## SUM()

In [38]:
result = pd.read_sql('''
SELECT SUM(total) AS total_revenue
FROM invoice
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_2060\1108750030.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

   total_revenue
0         2328.6

## AVG()

In [39]:
result = pd.read_sql('''
SELECT AVG(total) AS total_average
FROM invoice
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_2060\70938604.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

   total_average
0       5.651942

## MIN() and MAX()

In [40]:
result = pd.read_sql('''
SELECT MIN(unit_price) AS min_price, MAX(unit_price) AS max_price
FROM track
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_2060\4101703863.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

   min_price  max_price
0       0.99       1.99

In [42]:
result = pd.read_sql('''
SELECT MIN(invoice_date) AS earliest, MAX(invoice_date) AS last
FROM invoice
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_2060\2640364690.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

    earliest       last
0 2021-01-01 2025-12-22

## Combine Aggregate Finctions

In [43]:
result = pd.read_sql('''
SELECT 
COUNT(*) AS invoice_count,
SUM(total) AS total_revenue,
AVG(total) AS total_avg,
MIN(total) AS min_invoice
FROM invoice
''', conn)

result

C:\Users\Lighthouse\AppData\Local\Temp\ipykernel_2060\3906787147.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql('''

   invoice_count  total_revenue  total_avg  min_invoice
0            412         2328.6   5.651942         0.99