# JOIN

In [2]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('chinook.db')
cursor = conn.cursor()

## Understanding the Relationship

In [3]:
# artist table --> arist_id, name
# album table  --> album_id, title, artisr_id

## Basic INNER JOIN

In [14]:
# Combine two related rows from two tables
cursor.execute('''
SELECT albums.Title, artists.Name
FROM albums
INNER JOIN artists
ON  albums.ArtistId = artists.ArtistId

''')

result = cursor.fetchall()
result

[('For Those About To Rock We Salute You', 'AC/DC'),
 ('Balls to the Wall', 'Accept'),
 ('Restless and Wild', 'Accept'),
 ('Let There Be Rock', 'AC/DC'),
 ('Big Ones', 'Aerosmith'),
 ('Jagged Little Pill', 'Alanis Morissette'),
 ('Facelift', 'Alice In Chains'),
 ('Warner 25 Anos', 'Antônio Carlos Jobim'),
 ('Plays Metallica By Four Cellos', 'Apocalyptica'),
 ('Audioslave', 'Audioslave'),
 ('Out Of Exile', 'Audioslave'),
 ('BackBeat Soundtrack', 'BackBeat'),
 ('The Best Of Billy Cobham', 'Billy Cobham'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]', 'Black Label Society'),
 ('Alcohol Fueled Brewtality Live! [Disc 2]', 'Black Label Society'),
 ('Black Sabbath', 'Black Sabbath'),
 ('Black Sabbath Vol. 4 (Remaster)', 'Black Sabbath'),
 ('Body Count', 'Body Count'),
 ('Chemical Wedding', 'Bruce Dickinson'),
 ('The Best Of Buddy Guy - The Millenium Collection', 'Buddy Guy'),
 ('Prenda Minha', 'Caetano Veloso'),
 ('Sozinho Remix Ao Vivo', 'Caetano Veloso'),
 ('Minha Historia', 'Chico Buarque'),
 ('Afrociberdelia', 'Chico Science & Nação Zumbi'),
 ('Da Lama Ao Caos', 'Chico Science & Nação Zumbi'),
 ('Acústico MTV [Live]', 'Cidade Negra'),
 ('Cidade Negra - Hits', 'Cidade Negra'),
 ('Na Pista', 'Cláudio Zoli'),
 ('Axé Bahia 2001', 'Various Artists'),
 ('BBC Sessions [Disc 1] [Live]', 'Led Zeppelin'),
 ('Bongo Fury', 'Frank Zappa & Captain Beefheart'),
 ('Carnaval 2001', 'Various Artists'),
 ('Chill: Brazil (Disc 1)', 'Marcos Valle'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim'),
 ('Garage Inc. (Disc 1)', 'Metallica'),
 ('Greatest Hits II', 'Queen'),
 ('Greatest Kiss', 'Kiss'),
 ('Heart of the Night', 'Spyro Gyra'),
 ('International Superhits', 'Green Day'),
 ('Into The Light', 'David Coverdale'),
 ('Meus Momentos', 'Gonzaguinha'),
 ('Minha História', 'Os Mutantes'),
 ('MK III The Final Concerts [Disc 1]', 'Deep Purple'),
 ('Physical Graffiti [Disc 1]', 'Led Zeppelin'),
 ('Sambas De Enredo 2001', 'Various Artists'),
 ('Supernatural', 'Santana'),
 ('The Best of Ed Motta', 'Ed Motta'),
 ('The Essential Miles Davis [Disc 1]', 'Miles Davis'),
 ('The Essential Miles Davis [Disc 2]', 'Miles Davis'),
 ('The Final Concerts (Disc 2)', 'Deep Purple'),
 ("Up An' Atom", 'Gene Krupa'),
 ('Vinícius De Moraes - Sem Limite', 'Toquinho & Vinícius'),
 ('Vozes do MPB', 'Various Artists'),
 ('Chronicle, Vol. 1', 'Creedence Clearwater Revival'),
 ('Chronicle, Vol. 2', 'Creedence Clearwater Revival'),
 ('Cássia Eller - Coleção Sem Limite [Disc 2]', 'Cássia Eller'),
 ('Cássia Eller - Sem Limite [Disc 1]', 'Cássia Eller'),
 ('Come Taste The Band', 'Deep Purple'),
 ('Deep Purple In Rock', 'Deep Purple'),
 ('Fireball', 'Deep Purple'),
 ("Knocking at Your Back Door: The Best Of Deep Purple in the 80's",
  'Deep Purple'),
 ('Machine Head', 'Deep Purple'),
 ('Purpendicular', 'Deep Purple'),
 ('Slaves And Masters', 'Deep Purple'),
 ('Stormbringer', 'Deep Purple'),
 ('The Battle Rages On', 'Deep Purple'),
 ("Vault: Def Leppard's Greatest Hits", 'Def Leppard'),
 ('Outbreak', 'Dennis Chambers'),
 ('Djavan Ao Vivo - Vol. 02', 'Djavan'),
 ('Djavan Ao Vivo - Vol. 1', 'Djavan'),
 ('Elis Regina-Minha História', 'Elis Regina'),
 ('The Cream Of Clapton', 'Eric Clapton'),
 ('Unplugged', 'Eric Clapton'),
 ('Album Of The Year', 'Faith No More'),
 ('Angel Dust', 'Faith No More'),
 ('King For A Day Fool For A Lifetime', 'Faith No More'),
 ('The Real Thing', 'Faith No More'),
 ('Deixa Entrar', 'Falamansa'),
 ('In Your Honor [Disc 1]', 'Foo Fighters'),
 ('In Your Honor [Disc 2]', 'Foo Fighters'),
 ('One By One', 'Foo Fighters'),
 ('The Colour And The Shape', 'Foo Fighters'),
 ('My Way: The Best Of Frank Sinatra [Disc 1]', 'Frank Sinatra'),
 ('Roda De Funk', 'Funk Como Le Gusta'),
 ('As Canções de Eu Tu Eles', 'Gilberto Gil'),
 ('Quanta Gente Veio Ver (Live)', 'Gilberto Gil'),
 ('Quanta Gente Veio ver--Bônus De Carnaval', 'Gilberto Gil'),
 ('Faceless', 'Godsmack'),
 ('American Idiot', 'Green Day'),
 ('Appetite for Destruction', "Guns N' Roses"),
 ('Use Your Illusion I', "Guns N' Roses"),
 ('Use Your Illusion II', "Guns N' Roses"),
 ('Blue Moods', 'Incognito'),
 ('A Matter of Life and Death', 'Iron Maiden'),
 ('A Real Dead One', 'Iron Maiden'),
 ('A Real Live One', 'Iron Maiden'),
 ('Brave New World', 'Iron Maiden'),
 ('Dance Of Death', 'Iron Maiden'),
 ('Fear Of The Dark', 'Iron Maiden'),
 ('Iron Maiden', 'Iron Maiden'),
 ('Killers', 'Iron Maiden'),
 ('Live After Death', 'Iron Maiden'),
 ('Live At Donington 1992 (Disc 1)', 'Iron Maiden'),
 ('Live At Donington 1992 (Disc 2)', 'Iron Maiden'),
 ('No Prayer For The Dying', 'Iron Maiden'),
 ('Piece Of Mind', 'Iron Maiden'),
 ('Powerslave', 'Iron Maiden'),
 ('Rock In Rio [CD1]', 'Iron Maiden'),
 ('Rock In Rio [CD2]', 'Iron Maiden'),
 ('Seventh Son of a Seventh Son', 'Iron Maiden'),
 ('Somewhere in Time', 'Iron Maiden'),
 ('The Number of The Beast', 'Iron Maiden'),
 ('The X Factor', 'Iron Maiden'),
 ('Virtual XI', 'Iron Maiden'),
 ('Sex Machine', 'James Brown'),
 ('Emergency On Planet Earth', 'Jamiroquai'),
 ('Synkronized', 'Jamiroquai'),
 ('The Return Of The Space Cowboy', 'Jamiroquai'),
 ('Get Born', 'JET'),
 ('Are You Experienced?', 'Jimi Hendrix'),
 ('Surfing with the Alien (Remastered)', 'Joe Satriani'),
 ('Jorge Ben Jor 25 Anos', 'Jorge Ben'),
 ('Jota Quest-1995', 'Jota Quest'),
 ('Cafezinho', 'João Suplicy'),
 ('Living After Midnight', 'Judas Priest'),
 ('Unplugged [Live]', 'Kiss'),
 ('BBC Sessions [Disc 2] [Live]', 'Led Zeppelin'),
 ('Coda', 'Led Zeppelin'),
 ('Houses Of The Holy', 'Led Zeppelin'),
 ('In Through The Out Door', 'Led Zeppelin'),
 ('IV', 'Led Zeppelin'),
 ('Led Zeppelin I', 'Led Zeppelin'),
 ('Led Zeppelin II', 'Led Zeppelin'),
 ('Led Zeppelin III', 'Led Zeppelin'),
 ('Physical Graffiti [Disc 2]', 'Led Zeppelin'),
 ('Presence', 'Led Zeppelin'),
 ('The Song Remains The Same (Disc 1)', 'Led Zeppelin'),
 ('The Song Remains The Same (Disc 2)', 'Led Zeppelin'),
 ('A TempestadeTempestade Ou O Livro Dos Dias', 'Legião Urbana'),
 ('Mais Do Mesmo', 'Legião Urbana'),
 ('Greatest Hits', 'Lenny Kravitz'),
 ('Lulu Santos - RCA 100 Anos De Música - Álbum 01', 'Lulu Santos'),
 ('Lulu Santos - RCA 100 Anos De Música - Álbum 02', 'Lulu Santos'),
 ('Misplaced Childhood', 'Marillion'),
 ('Barulhinho Bom', 'Marisa Monte'),
 ('Seek And Shall Find: More Of The Best (1963-1981)', 'Marvin Gaye'),
 ('The Best Of Men At Work', 'Men At Work'),
 ('Black Album', 'Metallica'),
 ('Garage Inc. (Disc 2)', 'Metallica'),
 ("Kill 'Em All", 'Metallica'),
 ('Load', 'Metallica'),
 ('Master Of Puppets', 'Metallica'),
 ('ReLoad', 'Metallica'),
 ('Ride The Lightning', 'Metallica'),
 ('St. Anger', 'Metallica'),
 ('...And Justice For All', 'Metallica'),
 ('Miles Ahead', 'Miles Davis'),
 ('Milton Nascimento Ao Vivo', 'Milton Nascimento'),
 ('Minas', 'Milton Nascimento'),
 ('Ace Of Spades', 'Motörhead'),
 ('Demorou...', 'Mônica Marianno'),
 ('Motley Crue Greatest Hits', 'Mötley Crüe'),
 ('From The Muddy Banks Of The Wishkah [Live]', 'Nirvana'),
 ('Nevermind', 'Nirvana'),
 ('Compositores', 'O Terço'),
 ('Olodum', 'Olodum'),
 ('Acústico MTV', 'Os Paralamas Do Sucesso'),
 ('Arquivo II', 'Os Paralamas Do Sucesso'),
 ('Arquivo Os Paralamas Do Sucesso', 'Os Paralamas Do Sucesso'),
 ('Bark at the Moon (Remastered)', 'Ozzy Osbourne'),
 ('Blizzard of Ozz', 'Ozzy Osbourne'),
 ('Diary of a Madman (Remastered)', 'Ozzy Osbourne'),
 ('No More Tears (Remastered)', 'Ozzy Osbourne'),
 ('Tribute', 'Ozzy Osbourne'),
 ('Walking Into Clarksdale', 'Page & Plant'),
 ('Original Soundtracks 1', 'Passengers'),
 ('The Beast Live', "Paul D'Ianno"),
 ('Live On Two Legs [Live]', 'Pearl Jam'),
 ('Pearl Jam', 'Pearl Jam'),
 ('Riot Act', 'Pearl Jam'),
 ('Ten', 'Pearl Jam'),
 ('Vs.', 'Pearl Jam'),
 ('Dark Side Of The Moon', 'Pink Floyd'),
 ('Os Cães Ladram Mas A Caravana Não Pára', 'Planet Hemp'),
 ('Greatest Hits I', 'Queen'),
 ('News Of The World', 'Queen'),
 ('Out Of Time', 'R.E.M. Feat. Kate Pearson'),
 ('Green', 'R.E.M.'),
 ('New Adventures In Hi-Fi', 'R.E.M.'),
 ('The Best Of R.E.M.: The IRS Years', 'R.E.M.'),
 ('Cesta Básica', 'Raimundos'),
 ('Raul Seixas', 'Raul Seixas'),
 ('Blood Sugar Sex Magik', 'Red Hot Chili Peppers'),
 ('By The Way', 'Red Hot Chili Peppers'),
 ('Californication', 'Red Hot Chili Peppers'),
 ('Retrospective I (1974-1980)', 'Rush'),
 ('Santana - As Years Go By', 'Santana'),
 ('Santana Live', 'Santana'),
 ('Maquinarama', 'Skank'),
 ('O Samba Poconé', 'Skank'),
 ('Judas 0: B-Sides and Rarities', 'Smashing Pumpkins'),
 ('Rotten Apples: Greatest Hits', 'Smashing Pumpkins'),
 ('A-Sides', 'Soundgarden'),
 ('Morning Dance', 'Spyro Gyra'),
 ('In Step', 'Stevie Ray Vaughan & Double Trouble'),
 ('Core', 'Stone Temple Pilots'),
 ('Mezmerize', 'System Of A Down'),
 ('[1997] Black Light Syndrome', 'Terry Bozzio, Tony Levin & Steve Stevens'),
 ('Live [Disc 1]', 'The Black Crowes'),
 ('Live [Disc 2]', 'The Black Crowes'),
 ('The Singles', 'The Clash'),
 ('Beyond Good And Evil', 'The Cult'),
 ('Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]',
  'The Cult'),
 ('The Doors', 'The Doors'),
 ('The Police Greatest Hits', 'The Police'),
 ('Hot Rocks, 1964-1971 (Disc 1)', 'The Rolling Stones'),
 ('No Security', 'The Rolling Stones'),
 ('Voodoo Lounge', 'The Rolling Stones'),
 ('Tangents', 'The Tea Party'),
 ('Transmission', 'The Tea Party'),
 ('My Generation - The Very Best Of The Who', 'The Who'),
 ('Serie Sem Limite (Disc 1)', 'Tim Maia'),
 ('Serie Sem Limite (Disc 2)', 'Tim Maia'),
 ('Acústico', 'Titãs'),
 ('Volume Dois', 'Titãs'),
 ('Battlestar Galactica: The Story So Far', 'Battlestar Galactica'),
 ('Battlestar Galactica, Season 3', 'Battlestar Galactica'),
 ('Heroes, Season 1', 'Heroes'),
 ('Lost, Season 3', 'Lost'),
 ('Lost, Season 1', 'Lost'),
 ('Lost, Season 2', 'Lost'),
 ('Achtung Baby', 'U2'),
 ("All That You Can't Leave Behind", 'U2'),
 ('B-Sides 1980-1990', 'U2'),
 ('How To Dismantle An Atomic Bomb', 'U2'),
 ('Pop', 'U2'),
 ('Rattle And Hum', 'U2'),
 ('The Best Of 1980-1990', 'U2'),
 ('War', 'U2'),
 ('Zooropa', 'U2'),
 ('UB40 The Best Of - Volume Two [UK]', 'UB40'),
 ('Diver Down', 'Van Halen'),
 ('The Best Of Van Halen, Vol. I', 'Van Halen'),
 ('Van Halen', 'Van Halen'),
 ('Van Halen III', 'Van Halen'),
 ('Contraband', 'Velvet Revolver'),
 ('Vinicius De Moraes', 'Vinícius De Moraes'),
 ('Ao Vivo [IMPORT]', 'Zeca Pagodinho'),
 ('The Office, Season 1', 'The Office'),
 ('The Office, Season 2', 'The Office'),
 ('The Office, Season 3', 'The Office'),
 ('Un-Led-Ed', 'Dread Zeppelin'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)'),
 ('Aquaman', 'Aquaman'),
 ('Instant Karma: The Amnesty International Campaign to Save Darfur', 'U2'),
 ('Speak of the Devil', 'Ozzy Osbourne'),
 ('20th Century Masters - The Millennium Collection: The Best of Scorpions',
  'Scorpions'),
 ('House of Pain', 'House Of Pain'),
 ('Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro',
  'O Rappa'),
 ('Cake: B-Sides and Rarities', 'Cake'),
 ('LOST, Season 4', 'Lost'),
 ('Quiet Songs', 'Aisha Duo'),
 ('Muso Ko', 'Habib Koité and Bamada'),
 ('Realize', 'Karsh Kale'),
 ('Every Kind of Light', 'The Posies'),
 ('Duos II', 'Luciana Souza/Romero Lubambo'),
 ('Worlds', 'Aaron Goldberg'),
 ('The Best of Beethoven', 'Nicolaus Esterhazy Sinfonia'),
 ('Temple of the Dog', 'Temple of the Dog'),
 ('Carry On', 'Chris Cornell'),
 ('Revelations', 'Audioslave'),
 ('Adorate Deum: Gregorian Chant from the Proper of the Mass',
  'Alberto Turco & Nova Schola Gregoriana'),
 ('Allegri: Miserere',
  'Richard Marlow & The Choir of Trinity College, Cambridge'),
 ('Pachelbel: Canon & Gigue', 'English Concert & Trevor Pinnock'),
 ('Vivaldi: The Four Seasons',
  'Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker'),
 ('Bach: Violin Concertos',
  'Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer'),
 ('Bach: Goldberg Variations', 'Wilhelm Kempff'),
 ('Bach: The Cello Suites', 'Yo-Yo Ma'),
 ('Handel: The Messiah (Highlights)', 'Scholars Baroque Ensemble'),
 ('The World of Classical Favourites',
  'Academy of St. Martin in the Fields & Sir Neville Marriner'),
 ('Sir Neville Marriner: A Celebration',
  'Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner'),
 ('Mozart: Wind Concertos',
  'Berliner Philharmoniker, Claudio Abbado & Sabine Meyer'),
 ('Haydn: Symphonies 99 - 104',
  'Royal Philharmonic Orchestra & Sir Thomas Beecham'),
 ('Beethoven: Symhonies Nos. 5 & 6',
  'Orchestre Révolutionnaire et Romantique & John Eliot Gardiner'),
 ('A Soprano Inspired', 'Britten Sinfonia, Ivor Bolton & Lesley Garrett'),
 ('Great Opera Choruses',
  'Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti'),
 ('Wagner: Favourite Overtures', 'Sir Georg Solti & Wiener Philharmoniker'),
 ('Fauré: Requiem, Ravel: Pavane & Others',
  'Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair'),
 ('Tchaikovsky: The Nutcracker',
  'London Symphony Orchestra & Sir Charles Mackerras'),
 ('The Last Night of the Proms', 'Barry Wordsworth & BBC Concert Orchestra'),
 ('Puccini: Madama Butterfly - Highlights',
  'Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker'),
 ('Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies',
  'Eugene Ormandy'),
 ("Pavarotti's Opera Made Easy", 'Luciano Pavarotti'),
 ("Great Performances - Barber's Adagio and Other Romantic Favorites for Strings",
  'Leonard Bernstein & New York Philharmonic'),
 ('Carmina Burana', 'Boston Symphony Orchestra & Seiji Ozawa'),
 ('A Copland Celebration, Vol. I',
  'Aaron Copland & London Symphony Orchestra'),
 ('Bach: Toccata & Fugue in D Minor', 'Ton Koopman'),
 ('Prokofiev: Symphony No.1', 'Sergei Prokofiev & Yuri Temirkanov'),
 ('Scheherazade', 'Chicago Symphony Orchestra & Fritz Reiner'),
 ('Bach: The Brandenburg Concertos', 'Orchestra of The Age of Enlightenment'),
 ('Chopin: Piano Concertos Nos. 1 & 2',
  'Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra'),
 ('Mascagni: Cavalleria Rusticana', 'James Levine'),
 ('Sibelius: Finlandia', 'Berliner Philharmoniker & Hans Rosbaud'),
 ('Beethoven Piano Sonatas: Moonlight & Pastorale', 'Maurizio Pollini'),
 ('Great Recordings of the Century - Mahler: Das Lied von der Erde',
  'Gustav Mahler'),
 ('Elgar: Cello Concerto & Vaughan Williams: Fantasias',
  'Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos'),
 ('Adams, John: The Chairman Dances', 'Edo de Waart & San Francisco Symphony'),
 ("Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington's Victory",
  'Antal Doráti & London Symphony Orchestra'),
 ('Palestrina: Missa Papae Marcelli & Allegri: Miserere',
  'Choir Of Westminster Abbey & Simon Preston'),
 ('Prokofiev: Romeo & Juliet',
  'Michael Tilson Thomas & San Francisco Symphony'),
 ('Strauss: Waltzes', 'Eugene Ormandy'),
 ('Berlioz: Symphonie Fantastique',
  'Michael Tilson Thomas & San Francisco Symphony'),
 ('Bizet: Carmen Highlights',
  'Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker'),
 ('English Renaissance', "The King's Singers"),
 ('Handel: Music for the Royal Fireworks (Original Version 1749)',
  'English Concert & Trevor Pinnock'),
 ('Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande',
  'Berliner Philharmoniker & Herbert Von Karajan'),
 ('Mozart Gala: Famous Arias',
  'Sir Georg Solti, Sumi Jo & Wiener Philharmoniker'),
 ('SCRIABIN: Vers la flamme', "Christopher O'Riley"),
 ('Armada: Music from the Courts of England and Spain', 'Fretwork'),
 ('Mozart: Symphonies Nos. 40 & 41',
  'Berliner Philharmoniker & Herbert Von Karajan'),
 ('Back to Black', 'Amy Winehouse'),
 ('Frank', 'Amy Winehouse'),
 ('Carried to Dust (Bonus Track Version)', 'Calexico'),
 ("Beethoven: Symphony No. 6 'Pastoral' Etc.",
  'Otto Klemperer & Philharmonia Orchestra'),
 ('Bartok: Violin & Viola Concertos', 'Yehudi Menuhin'),
 ("Mendelssohn: A Midsummer Night's Dream",
  'Philharmonia Orchestra & Sir Neville Marriner'),
 ('Bach: Orchestral Suites Nos. 1 - 4',
  'Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart'),
 ('Charpentier: Divertissements, Airs & Concerts',
  'Les Arts Florissants & William Christie'),
 ('South American Getaway', 'The 12 Cellists of The Berlin Philharmonic'),
 ('Górecki: Symphony No. 3', 'Adrian Leaper & Doreen de Feis'),
 ('Purcell: The Fairy Queen', 'Roger Norrington, London Classical Players'),
 ('The Ultimate Relexation Album',
  "Charles Dutoit & L'Orchestre Symphonique de Montréal"),
 ('Purcell: Music for the Queen Mary',
  'Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir'),
 ('Weill: The Seven Deadly Sins',
  "Kent Nagano and Orchestre de l'Opéra de Lyon"),
 ('J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro',
  'Julian Bream'),
 ('Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps',
  'Berliner Philharmoniker & Herbert Von Karajan'),
 ('Szymanowski: Piano Works, Vol. 1', 'Martin Roscoe'),
 ('Nielsen: The Six Symphonies', 'Göteborgs Symfoniker & Neeme Järvi'),
 ("Great Recordings of the Century: Paganini's 24 Caprices", 'Itzhak Perlman'),
 ("Liszt - 12 Études D'Execution Transcendante", 'Michele Campanella'),
 ('Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder',
  'Gerald Moore'),
 ('Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3',
  'Mela Tenenbaum, Pro Musica Prague & Richard Kapp'),
 ('Respighi:Pines of Rome', 'Eugene Ormandy'),
 ("Schubert: The Late String Quartets & String Quintet (3 CD's)",
  'Emerson String Quartet'),
 ("Monteverdi: L'Orfeo",
  'C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu'),
 ('Mozart: Chamber Music', 'Nash Ensemble'),
 ('Koyaanisqatsi (Soundtrack from the Motion Picture)',
  'Philip Glass Ensemble')]

## Using Table Aliases

In [17]:
# Use aliases for shorter table name

cursor.execute('''
SELECT a.Title, ar.Name
FROM albums AS a
INNER JOIN artists AS ar
ON  a.ArtistId = ar.ArtistId

''')
# albums   --> a
# artistrs --> ar

result = cursor.fetchall()
result

[('For Those About To Rock We Salute You', 'AC/DC'),
 ('Balls to the Wall', 'Accept'),
 ('Restless and Wild', 'Accept'),
 ('Let There Be Rock', 'AC/DC'),
 ('Big Ones', 'Aerosmith'),
 ('Jagged Little Pill', 'Alanis Morissette'),
 ('Facelift', 'Alice In Chains'),
 ('Warner 25 Anos', 'Antônio Carlos Jobim'),
 ('Plays Metallica By Four Cellos', 'Apocalyptica'),
 ('Audioslave', 'Audioslave'),
 ('Out Of Exile', 'Audioslave'),
 ('BackBeat Soundtrack', 'BackBeat'),
 ('The Best Of Billy Cobham', 'Billy Cobham'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]', 'Black Label Society'),
 ('Alcohol Fueled Brewtality Live! [Disc 2]', 'Black Label Society'),
 ('Black Sabbath', 'Black Sabbath'),
 ('Black Sabbath Vol. 4 (Remaster)', 'Black Sabbath'),
 ('Body Count', 'Body Count'),
 ('Chemical Wedding', 'Bruce Dickinson'),
 ('The Best Of Buddy Guy - The Millenium Collection', 'Buddy Guy'),
 ('Prenda Minha', 'Caetano Veloso'),
 ('Sozinho Remix Ao Vivo', 'Caetano Veloso'),
 ('Minha Historia', 'Chico Buarque'),
 ('Afrociberdelia', 'Chico Science & Nação Zumbi'),
 ('Da Lama Ao Caos', 'Chico Science & Nação Zumbi'),
 ('Acústico MTV [Live]', 'Cidade Negra'),
 ('Cidade Negra - Hits', 'Cidade Negra'),
 ('Na Pista', 'Cláudio Zoli'),
 ('Axé Bahia 2001', 'Various Artists'),
 ('BBC Sessions [Disc 1] [Live]', 'Led Zeppelin'),
 ('Bongo Fury', 'Frank Zappa & Captain Beefheart'),
 ('Carnaval 2001', 'Various Artists'),
 ('Chill: Brazil (Disc 1)', 'Marcos Valle'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim'),
 ('Garage Inc. (Disc 1)', 'Metallica'),
 ('Greatest Hits II', 'Queen'),
 ('Greatest Kiss', 'Kiss'),
 ('Heart of the Night', 'Spyro Gyra'),
 ('International Superhits', 'Green Day'),
 ('Into The Light', 'David Coverdale'),
 ('Meus Momentos', 'Gonzaguinha'),
 ('Minha História', 'Os Mutantes'),
 ('MK III The Final Concerts [Disc 1]', 'Deep Purple'),
 ('Physical Graffiti [Disc 1]', 'Led Zeppelin'),
 ('Sambas De Enredo 2001', 'Various Artists'),
 ('Supernatural', 'Santana'),
 ('The Best of Ed Motta', 'Ed Motta'),
 ('The Essential Miles Davis [Disc 1]', 'Miles Davis'),
 ('The Essential Miles Davis [Disc 2]', 'Miles Davis'),
 ('The Final Concerts (Disc 2)', 'Deep Purple'),
 ("Up An' Atom", 'Gene Krupa'),
 ('Vinícius De Moraes - Sem Limite', 'Toquinho & Vinícius'),
 ('Vozes do MPB', 'Various Artists'),
 ('Chronicle, Vol. 1', 'Creedence Clearwater Revival'),
 ('Chronicle, Vol. 2', 'Creedence Clearwater Revival'),
 ('Cássia Eller - Coleção Sem Limite [Disc 2]', 'Cássia Eller'),
 ('Cássia Eller - Sem Limite [Disc 1]', 'Cássia Eller'),
 ('Come Taste The Band', 'Deep Purple'),
 ('Deep Purple In Rock', 'Deep Purple'),
 ('Fireball', 'Deep Purple'),
 ("Knocking at Your Back Door: The Best Of Deep Purple in the 80's",
  'Deep Purple'),
 ('Machine Head', 'Deep Purple'),
 ('Purpendicular', 'Deep Purple'),
 ('Slaves And Masters', 'Deep Purple'),
 ('Stormbringer', 'Deep Purple'),
 ('The Battle Rages On', 'Deep Purple'),
 ("Vault: Def Leppard's Greatest Hits", 'Def Leppard'),
 ('Outbreak', 'Dennis Chambers'),
 ('Djavan Ao Vivo - Vol. 02', 'Djavan'),
 ('Djavan Ao Vivo - Vol. 1', 'Djavan'),
 ('Elis Regina-Minha História', 'Elis Regina'),
 ('The Cream Of Clapton', 'Eric Clapton'),
 ('Unplugged', 'Eric Clapton'),
 ('Album Of The Year', 'Faith No More'),
 ('Angel Dust', 'Faith No More'),
 ('King For A Day Fool For A Lifetime', 'Faith No More'),
 ('The Real Thing', 'Faith No More'),
 ('Deixa Entrar', 'Falamansa'),
 ('In Your Honor [Disc 1]', 'Foo Fighters'),
 ('In Your Honor [Disc 2]', 'Foo Fighters'),
 ('One By One', 'Foo Fighters'),
 ('The Colour And The Shape', 'Foo Fighters'),
 ('My Way: The Best Of Frank Sinatra [Disc 1]', 'Frank Sinatra'),
 ('Roda De Funk', 'Funk Como Le Gusta'),
 ('As Canções de Eu Tu Eles', 'Gilberto Gil'),
 ('Quanta Gente Veio Ver (Live)', 'Gilberto Gil'),
 ('Quanta Gente Veio ver--Bônus De Carnaval', 'Gilberto Gil'),
 ('Faceless', 'Godsmack'),
 ('American Idiot', 'Green Day'),
 ('Appetite for Destruction', "Guns N' Roses"),
 ('Use Your Illusion I', "Guns N' Roses"),
 ('Use Your Illusion II', "Guns N' Roses"),
 ('Blue Moods', 'Incognito'),
 ('A Matter of Life and Death', 'Iron Maiden'),
 ('A Real Dead One', 'Iron Maiden'),
 ('A Real Live One', 'Iron Maiden'),
 ('Brave New World', 'Iron Maiden'),
 ('Dance Of Death', 'Iron Maiden'),
 ('Fear Of The Dark', 'Iron Maiden'),
 ('Iron Maiden', 'Iron Maiden'),
 ('Killers', 'Iron Maiden'),
 ('Live After Death', 'Iron Maiden'),
 ('Live At Donington 1992 (Disc 1)', 'Iron Maiden'),
 ('Live At Donington 1992 (Disc 2)', 'Iron Maiden'),
 ('No Prayer For The Dying', 'Iron Maiden'),
 ('Piece Of Mind', 'Iron Maiden'),
 ('Powerslave', 'Iron Maiden'),
 ('Rock In Rio [CD1]', 'Iron Maiden'),
 ('Rock In Rio [CD2]', 'Iron Maiden'),
 ('Seventh Son of a Seventh Son', 'Iron Maiden'),
 ('Somewhere in Time', 'Iron Maiden'),
 ('The Number of The Beast', 'Iron Maiden'),
 ('The X Factor', 'Iron Maiden'),
 ('Virtual XI', 'Iron Maiden'),
 ('Sex Machine', 'James Brown'),
 ('Emergency On Planet Earth', 'Jamiroquai'),
 ('Synkronized', 'Jamiroquai'),
 ('The Return Of The Space Cowboy', 'Jamiroquai'),
 ('Get Born', 'JET'),
 ('Are You Experienced?', 'Jimi Hendrix'),
 ('Surfing with the Alien (Remastered)', 'Joe Satriani'),
 ('Jorge Ben Jor 25 Anos', 'Jorge Ben'),
 ('Jota Quest-1995', 'Jota Quest'),
 ('Cafezinho', 'João Suplicy'),
 ('Living After Midnight', 'Judas Priest'),
 ('Unplugged [Live]', 'Kiss'),
 ('BBC Sessions [Disc 2] [Live]', 'Led Zeppelin'),
 ('Coda', 'Led Zeppelin'),
 ('Houses Of The Holy', 'Led Zeppelin'),
 ('In Through The Out Door', 'Led Zeppelin'),
 ('IV', 'Led Zeppelin'),
 ('Led Zeppelin I', 'Led Zeppelin'),
 ('Led Zeppelin II', 'Led Zeppelin'),
 ('Led Zeppelin III', 'Led Zeppelin'),
 ('Physical Graffiti [Disc 2]', 'Led Zeppelin'),
 ('Presence', 'Led Zeppelin'),
 ('The Song Remains The Same (Disc 1)', 'Led Zeppelin'),
 ('The Song Remains The Same (Disc 2)', 'Led Zeppelin'),
 ('A TempestadeTempestade Ou O Livro Dos Dias', 'Legião Urbana'),
 ('Mais Do Mesmo', 'Legião Urbana'),
 ('Greatest Hits', 'Lenny Kravitz'),
 ('Lulu Santos - RCA 100 Anos De Música - Álbum 01', 'Lulu Santos'),
 ('Lulu Santos - RCA 100 Anos De Música - Álbum 02', 'Lulu Santos'),
 ('Misplaced Childhood', 'Marillion'),
 ('Barulhinho Bom', 'Marisa Monte'),
 ('Seek And Shall Find: More Of The Best (1963-1981)', 'Marvin Gaye'),
 ('The Best Of Men At Work', 'Men At Work'),
 ('Black Album', 'Metallica'),
 ('Garage Inc. (Disc 2)', 'Metallica'),
 ("Kill 'Em All", 'Metallica'),
 ('Load', 'Metallica'),
 ('Master Of Puppets', 'Metallica'),
 ('ReLoad', 'Metallica'),
 ('Ride The Lightning', 'Metallica'),
 ('St. Anger', 'Metallica'),
 ('...And Justice For All', 'Metallica'),
 ('Miles Ahead', 'Miles Davis'),
 ('Milton Nascimento Ao Vivo', 'Milton Nascimento'),
 ('Minas', 'Milton Nascimento'),
 ('Ace Of Spades', 'Motörhead'),
 ('Demorou...', 'Mônica Marianno'),
 ('Motley Crue Greatest Hits', 'Mötley Crüe'),
 ('From The Muddy Banks Of The Wishkah [Live]', 'Nirvana'),
 ('Nevermind', 'Nirvana'),
 ('Compositores', 'O Terço'),
 ('Olodum', 'Olodum'),
 ('Acústico MTV', 'Os Paralamas Do Sucesso'),
 ('Arquivo II', 'Os Paralamas Do Sucesso'),
 ('Arquivo Os Paralamas Do Sucesso', 'Os Paralamas Do Sucesso'),
 ('Bark at the Moon (Remastered)', 'Ozzy Osbourne'),
 ('Blizzard of Ozz', 'Ozzy Osbourne'),
 ('Diary of a Madman (Remastered)', 'Ozzy Osbourne'),
 ('No More Tears (Remastered)', 'Ozzy Osbourne'),
 ('Tribute', 'Ozzy Osbourne'),
 ('Walking Into Clarksdale', 'Page & Plant'),
 ('Original Soundtracks 1', 'Passengers'),
 ('The Beast Live', "Paul D'Ianno"),
 ('Live On Two Legs [Live]', 'Pearl Jam'),
 ('Pearl Jam', 'Pearl Jam'),
 ('Riot Act', 'Pearl Jam'),
 ('Ten', 'Pearl Jam'),
 ('Vs.', 'Pearl Jam'),
 ('Dark Side Of The Moon', 'Pink Floyd'),
 ('Os Cães Ladram Mas A Caravana Não Pára', 'Planet Hemp'),
 ('Greatest Hits I', 'Queen'),
 ('News Of The World', 'Queen'),
 ('Out Of Time', 'R.E.M. Feat. Kate Pearson'),
 ('Green', 'R.E.M.'),
 ('New Adventures In Hi-Fi', 'R.E.M.'),
 ('The Best Of R.E.M.: The IRS Years', 'R.E.M.'),
 ('Cesta Básica', 'Raimundos'),
 ('Raul Seixas', 'Raul Seixas'),
 ('Blood Sugar Sex Magik', 'Red Hot Chili Peppers'),
 ('By The Way', 'Red Hot Chili Peppers'),
 ('Californication', 'Red Hot Chili Peppers'),
 ('Retrospective I (1974-1980)', 'Rush'),
 ('Santana - As Years Go By', 'Santana'),
 ('Santana Live', 'Santana'),
 ('Maquinarama', 'Skank'),
 ('O Samba Poconé', 'Skank'),
 ('Judas 0: B-Sides and Rarities', 'Smashing Pumpkins'),
 ('Rotten Apples: Greatest Hits', 'Smashing Pumpkins'),
 ('A-Sides', 'Soundgarden'),
 ('Morning Dance', 'Spyro Gyra'),
 ('In Step', 'Stevie Ray Vaughan & Double Trouble'),
 ('Core', 'Stone Temple Pilots'),
 ('Mezmerize', 'System Of A Down'),
 ('[1997] Black Light Syndrome', 'Terry Bozzio, Tony Levin & Steve Stevens'),
 ('Live [Disc 1]', 'The Black Crowes'),
 ('Live [Disc 2]', 'The Black Crowes'),
 ('The Singles', 'The Clash'),
 ('Beyond Good And Evil', 'The Cult'),
 ('Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]',
  'The Cult'),
 ('The Doors', 'The Doors'),
 ('The Police Greatest Hits', 'The Police'),
 ('Hot Rocks, 1964-1971 (Disc 1)', 'The Rolling Stones'),
 ('No Security', 'The Rolling Stones'),
 ('Voodoo Lounge', 'The Rolling Stones'),
 ('Tangents', 'The Tea Party'),
 ('Transmission', 'The Tea Party'),
 ('My Generation - The Very Best Of The Who', 'The Who'),
 ('Serie Sem Limite (Disc 1)', 'Tim Maia'),
 ('Serie Sem Limite (Disc 2)', 'Tim Maia'),
 ('Acústico', 'Titãs'),
 ('Volume Dois', 'Titãs'),
 ('Battlestar Galactica: The Story So Far', 'Battlestar Galactica'),
 ('Battlestar Galactica, Season 3', 'Battlestar Galactica'),
 ('Heroes, Season 1', 'Heroes'),
 ('Lost, Season 3', 'Lost'),
 ('Lost, Season 1', 'Lost'),
 ('Lost, Season 2', 'Lost'),
 ('Achtung Baby', 'U2'),
 ("All That You Can't Leave Behind", 'U2'),
 ('B-Sides 1980-1990', 'U2'),
 ('How To Dismantle An Atomic Bomb', 'U2'),
 ('Pop', 'U2'),
 ('Rattle And Hum', 'U2'),
 ('The Best Of 1980-1990', 'U2'),
 ('War', 'U2'),
 ('Zooropa', 'U2'),
 ('UB40 The Best Of - Volume Two [UK]', 'UB40'),
 ('Diver Down', 'Van Halen'),
 ('The Best Of Van Halen, Vol. I', 'Van Halen'),
 ('Van Halen', 'Van Halen'),
 ('Van Halen III', 'Van Halen'),
 ('Contraband', 'Velvet Revolver'),
 ('Vinicius De Moraes', 'Vinícius De Moraes'),
 ('Ao Vivo [IMPORT]', 'Zeca Pagodinho'),
 ('The Office, Season 1', 'The Office'),
 ('The Office, Season 2', 'The Office'),
 ('The Office, Season 3', 'The Office'),
 ('Un-Led-Ed', 'Dread Zeppelin'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)'),
 ('Aquaman', 'Aquaman'),
 ('Instant Karma: The Amnesty International Campaign to Save Darfur', 'U2'),
 ('Speak of the Devil', 'Ozzy Osbourne'),
 ('20th Century Masters - The Millennium Collection: The Best of Scorpions',
  'Scorpions'),
 ('House of Pain', 'House Of Pain'),
 ('Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro',
  'O Rappa'),
 ('Cake: B-Sides and Rarities', 'Cake'),
 ('LOST, Season 4', 'Lost'),
 ('Quiet Songs', 'Aisha Duo'),
 ('Muso Ko', 'Habib Koité and Bamada'),
 ('Realize', 'Karsh Kale'),
 ('Every Kind of Light', 'The Posies'),
 ('Duos II', 'Luciana Souza/Romero Lubambo'),
 ('Worlds', 'Aaron Goldberg'),
 ('The Best of Beethoven', 'Nicolaus Esterhazy Sinfonia'),
 ('Temple of the Dog', 'Temple of the Dog'),
 ('Carry On', 'Chris Cornell'),
 ('Revelations', 'Audioslave'),
 ('Adorate Deum: Gregorian Chant from the Proper of the Mass',
  'Alberto Turco & Nova Schola Gregoriana'),
 ('Allegri: Miserere',
  'Richard Marlow & The Choir of Trinity College, Cambridge'),
 ('Pachelbel: Canon & Gigue', 'English Concert & Trevor Pinnock'),
 ('Vivaldi: The Four Seasons',
  'Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker'),
 ('Bach: Violin Concertos',
  'Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer'),
 ('Bach: Goldberg Variations', 'Wilhelm Kempff'),
 ('Bach: The Cello Suites', 'Yo-Yo Ma'),
 ('Handel: The Messiah (Highlights)', 'Scholars Baroque Ensemble'),
 ('The World of Classical Favourites',
  'Academy of St. Martin in the Fields & Sir Neville Marriner'),
 ('Sir Neville Marriner: A Celebration',
  'Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner'),
 ('Mozart: Wind Concertos',
  'Berliner Philharmoniker, Claudio Abbado & Sabine Meyer'),
 ('Haydn: Symphonies 99 - 104',
  'Royal Philharmonic Orchestra & Sir Thomas Beecham'),
 ('Beethoven: Symhonies Nos. 5 & 6',
  'Orchestre Révolutionnaire et Romantique & John Eliot Gardiner'),
 ('A Soprano Inspired', 'Britten Sinfonia, Ivor Bolton & Lesley Garrett'),
 ('Great Opera Choruses',
  'Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti'),
 ('Wagner: Favourite Overtures', 'Sir Georg Solti & Wiener Philharmoniker'),
 ('Fauré: Requiem, Ravel: Pavane & Others',
  'Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair'),
 ('Tchaikovsky: The Nutcracker',
  'London Symphony Orchestra & Sir Charles Mackerras'),
 ('The Last Night of the Proms', 'Barry Wordsworth & BBC Concert Orchestra'),
 ('Puccini: Madama Butterfly - Highlights',
  'Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker'),
 ('Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies',
  'Eugene Ormandy'),
 ("Pavarotti's Opera Made Easy", 'Luciano Pavarotti'),
 ("Great Performances - Barber's Adagio and Other Romantic Favorites for Strings",
  'Leonard Bernstein & New York Philharmonic'),
 ('Carmina Burana', 'Boston Symphony Orchestra & Seiji Ozawa'),
 ('A Copland Celebration, Vol. I',
  'Aaron Copland & London Symphony Orchestra'),
 ('Bach: Toccata & Fugue in D Minor', 'Ton Koopman'),
 ('Prokofiev: Symphony No.1', 'Sergei Prokofiev & Yuri Temirkanov'),
 ('Scheherazade', 'Chicago Symphony Orchestra & Fritz Reiner'),
 ('Bach: The Brandenburg Concertos', 'Orchestra of The Age of Enlightenment'),
 ('Chopin: Piano Concertos Nos. 1 & 2',
  'Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra'),
 ('Mascagni: Cavalleria Rusticana', 'James Levine'),
 ('Sibelius: Finlandia', 'Berliner Philharmoniker & Hans Rosbaud'),
 ('Beethoven Piano Sonatas: Moonlight & Pastorale', 'Maurizio Pollini'),
 ('Great Recordings of the Century - Mahler: Das Lied von der Erde',
  'Gustav Mahler'),
 ('Elgar: Cello Concerto & Vaughan Williams: Fantasias',
  'Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos'),
 ('Adams, John: The Chairman Dances', 'Edo de Waart & San Francisco Symphony'),
 ("Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington's Victory",
  'Antal Doráti & London Symphony Orchestra'),
 ('Palestrina: Missa Papae Marcelli & Allegri: Miserere',
  'Choir Of Westminster Abbey & Simon Preston'),
 ('Prokofiev: Romeo & Juliet',
  'Michael Tilson Thomas & San Francisco Symphony'),
 ('Strauss: Waltzes', 'Eugene Ormandy'),
 ('Berlioz: Symphonie Fantastique',
  'Michael Tilson Thomas & San Francisco Symphony'),
 ('Bizet: Carmen Highlights',
  'Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker'),
 ('English Renaissance', "The King's Singers"),
 ('Handel: Music for the Royal Fireworks (Original Version 1749)',
  'English Concert & Trevor Pinnock'),
 ('Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande',
  'Berliner Philharmoniker & Herbert Von Karajan'),
 ('Mozart Gala: Famous Arias',
  'Sir Georg Solti, Sumi Jo & Wiener Philharmoniker'),
 ('SCRIABIN: Vers la flamme', "Christopher O'Riley"),
 ('Armada: Music from the Courts of England and Spain', 'Fretwork'),
 ('Mozart: Symphonies Nos. 40 & 41',
  'Berliner Philharmoniker & Herbert Von Karajan'),
 ('Back to Black', 'Amy Winehouse'),
 ('Frank', 'Amy Winehouse'),
 ('Carried to Dust (Bonus Track Version)', 'Calexico'),
 ("Beethoven: Symphony No. 6 'Pastoral' Etc.",
  'Otto Klemperer & Philharmonia Orchestra'),
 ('Bartok: Violin & Viola Concertos', 'Yehudi Menuhin'),
 ("Mendelssohn: A Midsummer Night's Dream",
  'Philharmonia Orchestra & Sir Neville Marriner'),
 ('Bach: Orchestral Suites Nos. 1 - 4',
  'Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart'),
 ('Charpentier: Divertissements, Airs & Concerts',
  'Les Arts Florissants & William Christie'),
 ('South American Getaway', 'The 12 Cellists of The Berlin Philharmonic'),
 ('Górecki: Symphony No. 3', 'Adrian Leaper & Doreen de Feis'),
 ('Purcell: The Fairy Queen', 'Roger Norrington, London Classical Players'),
 ('The Ultimate Relexation Album',
  "Charles Dutoit & L'Orchestre Symphonique de Montréal"),
 ('Purcell: Music for the Queen Mary',
  'Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir'),
 ('Weill: The Seven Deadly Sins',
  "Kent Nagano and Orchestre de l'Opéra de Lyon"),
 ('J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro',
  'Julian Bream'),
 ('Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps',
  'Berliner Philharmoniker & Herbert Von Karajan'),
 ('Szymanowski: Piano Works, Vol. 1', 'Martin Roscoe'),
 ('Nielsen: The Six Symphonies', 'Göteborgs Symfoniker & Neeme Järvi'),
 ("Great Recordings of the Century: Paganini's 24 Caprices", 'Itzhak Perlman'),
 ("Liszt - 12 Études D'Execution Transcendante", 'Michele Campanella'),
 ('Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder',
  'Gerald Moore'),
 ('Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3',
  'Mela Tenenbaum, Pro Musica Prague & Richard Kapp'),
 ('Respighi:Pines of Rome', 'Eugene Ormandy'),
 ("Schubert: The Late String Quartets & String Quintet (3 CD's)",
  'Emerson String Quartet'),
 ("Monteverdi: L'Orfeo",
  'C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu'),
 ('Mozart: Chamber Music', 'Nash Ensemble'),
 ('Koyaanisqatsi (Soundtrack from the Motion Picture)',
  'Philip Glass Ensemble')]

## JOIN with WHERE

In [19]:
# Filter joined results

cursor.execute('''
SELECT a.Title, ar.Name
FROM albums AS a
INNER JOIN artists AS ar
ON  a.ArtistId = ar.ArtistId
WHERE ar.name = 'AC/DC'
''')
# albums   --> a
# artistrs --> ar

result = cursor.fetchall()
result

[('For Those About To Rock We Salute You', 'AC/DC'),
 ('Let There Be Rock', 'AC/DC')]

## JOIN with ORDER BY

In [20]:
# Sort joined results

cursor.execute('''
SELECT a.Title, ar.Name
FROM albums AS a
INNER JOIN artists AS ar
ON  a.ArtistId = ar.ArtistId
ORDER BY ar.name
''')
# albums   --> a
# artistrs --> ar

result = cursor.fetchall()
result

[('For Those About To Rock We Salute You', 'AC/DC'),
 ('Let There Be Rock', 'AC/DC'),
 ('A Copland Celebration, Vol. I',
  'Aaron Copland & London Symphony Orchestra'),
 ('Worlds', 'Aaron Goldberg'),
 ('The World of Classical Favourites',
  'Academy of St. Martin in the Fields & Sir Neville Marriner'),
 ('Sir Neville Marriner: A Celebration',
  'Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner'),
 ('Fauré: Requiem, Ravel: Pavane & Others',
  'Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair'),
 ('Bach: Orchestral Suites Nos. 1 - 4',
  'Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart'),
 ('Balls to the Wall', 'Accept'),
 ('Restless and Wild', 'Accept'),
 ('Górecki: Symphony No. 3', 'Adrian Leaper & Doreen de Feis'),
 ('Big Ones', 'Aerosmith'),
 ('Quiet Songs', 'Aisha Duo'),
 ('Jagged Little Pill', 'Alanis Morissette'),
 ('Adorate Deum: Gregorian Chant from the Proper of the Mass',
  'Alberto Turco & Nova Schola Gregoriana'),
 ('Facelift', 'Alice In Chains'),
 ('Back to Black', 'Amy Winehouse'),
 ('Frank', 'Amy Winehouse'),
 ('Vivaldi: The Four Seasons',
  'Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker'),
 ("Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington's Victory",
  'Antal Doráti & London Symphony Orchestra'),
 ('Warner 25 Anos', 'Antônio Carlos Jobim'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim'),
 ('Plays Metallica By Four Cellos', 'Apocalyptica'),
 ('Aquaman', 'Aquaman'),
 ('Audioslave', 'Audioslave'),
 ('Out Of Exile', 'Audioslave'),
 ('Revelations', 'Audioslave'),
 ('BackBeat Soundtrack', 'BackBeat'),
 ('The Last Night of the Proms', 'Barry Wordsworth & BBC Concert Orchestra'),
 ('Battlestar Galactica: The Story So Far', 'Battlestar Galactica'),
 ('Battlestar Galactica, Season 3', 'Battlestar Galactica'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)'),
 ('Sibelius: Finlandia', 'Berliner Philharmoniker & Hans Rosbaud'),
 ('Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande',
  'Berliner Philharmoniker & Herbert Von Karajan'),
 ('Mozart: Symphonies Nos. 40 & 41',
  'Berliner Philharmoniker & Herbert Von Karajan'),
 ('Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps',
  'Berliner Philharmoniker & Herbert Von Karajan'),
 ('Mozart: Wind Concertos',
  'Berliner Philharmoniker, Claudio Abbado & Sabine Meyer'),
 ('The Best Of Billy Cobham', 'Billy Cobham'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]', 'Black Label Society'),
 ('Alcohol Fueled Brewtality Live! [Disc 2]', 'Black Label Society'),
 ('Black Sabbath', 'Black Sabbath'),
 ('Black Sabbath Vol. 4 (Remaster)', 'Black Sabbath'),
 ('Body Count', 'Body Count'),
 ('Carmina Burana', 'Boston Symphony Orchestra & Seiji Ozawa'),
 ('A Soprano Inspired', 'Britten Sinfonia, Ivor Bolton & Lesley Garrett'),
 ('Chemical Wedding', 'Bruce Dickinson'),
 ('The Best Of Buddy Guy - The Millenium Collection', 'Buddy Guy'),
 ("Monteverdi: L'Orfeo",
  'C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu'),
 ('Prenda Minha', 'Caetano Veloso'),
 ('Sozinho Remix Ao Vivo', 'Caetano Veloso'),
 ('Cake: B-Sides and Rarities', 'Cake'),
 ('Carried to Dust (Bonus Track Version)', 'Calexico'),
 ('The Ultimate Relexation Album',
  "Charles Dutoit & L'Orchestre Symphonique de Montréal"),
 ('Great Opera Choruses',
  'Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti'),
 ('Scheherazade', 'Chicago Symphony Orchestra & Fritz Reiner'),
 ('Minha Historia', 'Chico Buarque'),
 ('Afrociberdelia', 'Chico Science & Nação Zumbi'),
 ('Da Lama Ao Caos', 'Chico Science & Nação Zumbi'),
 ('Palestrina: Missa Papae Marcelli & Allegri: Miserere',
  'Choir Of Westminster Abbey & Simon Preston'),
 ('Bizet: Carmen Highlights',
  'Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker'),
 ('Carry On', 'Chris Cornell'),
 ('SCRIABIN: Vers la flamme', "Christopher O'Riley"),
 ('Acústico MTV [Live]', 'Cidade Negra'),
 ('Cidade Negra - Hits', 'Cidade Negra'),
 ('Na Pista', 'Cláudio Zoli'),
 ('Chronicle, Vol. 1', 'Creedence Clearwater Revival'),
 ('Chronicle, Vol. 2', 'Creedence Clearwater Revival'),
 ('Cássia Eller - Coleção Sem Limite [Disc 2]', 'Cássia Eller'),
 ('Cássia Eller - Sem Limite [Disc 1]', 'Cássia Eller'),
 ('Into The Light', 'David Coverdale'),
 ('MK III The Final Concerts [Disc 1]', 'Deep Purple'),
 ('The Final Concerts (Disc 2)', 'Deep Purple'),
 ('Come Taste The Band', 'Deep Purple'),
 ('Deep Purple In Rock', 'Deep Purple'),
 ('Fireball', 'Deep Purple'),
 ("Knocking at Your Back Door: The Best Of Deep Purple in the 80's",
  'Deep Purple'),
 ('Machine Head', 'Deep Purple'),
 ('Purpendicular', 'Deep Purple'),
 ('Slaves And Masters', 'Deep Purple'),
 ('Stormbringer', 'Deep Purple'),
 ('The Battle Rages On', 'Deep Purple'),
 ("Vault: Def Leppard's Greatest Hits", 'Def Leppard'),
 ('Outbreak', 'Dennis Chambers'),
 ('Djavan Ao Vivo - Vol. 02', 'Djavan'),
 ('Djavan Ao Vivo - Vol. 1', 'Djavan'),
 ('Un-Led-Ed', 'Dread Zeppelin'),
 ('The Best of Ed Motta', 'Ed Motta'),
 ('Adams, John: The Chairman Dances', 'Edo de Waart & San Francisco Symphony'),
 ('Elis Regina-Minha História', 'Elis Regina'),
 ('Chopin: Piano Concertos Nos. 1 & 2',
  'Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra'),
 ("Schubert: The Late String Quartets & String Quintet (3 CD's)",
  'Emerson String Quartet'),
 ('Pachelbel: Canon & Gigue', 'English Concert & Trevor Pinnock'),
 ('Handel: Music for the Royal Fireworks (Original Version 1749)',
  'English Concert & Trevor Pinnock'),
 ('Purcell: Music for the Queen Mary',
  'Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir'),
 ('The Cream Of Clapton', 'Eric Clapton'),
 ('Unplugged', 'Eric Clapton'),
 ('Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies',
  'Eugene Ormandy'),
 ('Strauss: Waltzes', 'Eugene Ormandy'),
 ('Respighi:Pines of Rome', 'Eugene Ormandy'),
 ('Album Of The Year', 'Faith No More'),
 ('Angel Dust', 'Faith No More'),
 ('King For A Day Fool For A Lifetime', 'Faith No More'),
 ('The Real Thing', 'Faith No More'),
 ('Deixa Entrar', 'Falamansa'),
 ('Elgar: Cello Concerto & Vaughan Williams: Fantasias',
  'Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos'),
 ('In Your Honor [Disc 1]', 'Foo Fighters'),
 ('In Your Honor [Disc 2]', 'Foo Fighters'),
 ('One By One', 'Foo Fighters'),
 ('The Colour And The Shape', 'Foo Fighters'),
 ('My Way: The Best Of Frank Sinatra [Disc 1]', 'Frank Sinatra'),
 ('Bongo Fury', 'Frank Zappa & Captain Beefheart'),
 ('Armada: Music from the Courts of England and Spain', 'Fretwork'),
 ('Roda De Funk', 'Funk Como Le Gusta'),
 ("Up An' Atom", 'Gene Krupa'),
 ('Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder',
  'Gerald Moore'),
 ('As Canções de Eu Tu Eles', 'Gilberto Gil'),
 ('Quanta Gente Veio Ver (Live)', 'Gilberto Gil'),
 ('Quanta Gente Veio ver--Bônus De Carnaval', 'Gilberto Gil'),
 ('Faceless', 'Godsmack'),
 ('Meus Momentos', 'Gonzaguinha'),
 ('International Superhits', 'Green Day'),
 ('American Idiot', 'Green Day'),
 ('Appetite for Destruction', "Guns N' Roses"),
 ('Use Your Illusion I', "Guns N' Roses"),
 ('Use Your Illusion II', "Guns N' Roses"),
 ('Great Recordings of the Century - Mahler: Das Lied von der Erde',
  'Gustav Mahler'),
 ('Nielsen: The Six Symphonies', 'Göteborgs Symfoniker & Neeme Järvi'),
 ('Muso Ko', 'Habib Koité and Bamada'),
 ('Puccini: Madama Butterfly - Highlights',
  'Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker'),
 ('Heroes, Season 1', 'Heroes'),
 ('Bach: Violin Concertos',
  'Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer'),
 ('House of Pain', 'House Of Pain'),
 ('Blue Moods', 'Incognito'),
 ('A Matter of Life and Death', 'Iron Maiden'),
 ('A Real Dead One', 'Iron Maiden'),
 ('A Real Live One', 'Iron Maiden'),
 ('Brave New World', 'Iron Maiden'),
 ('Dance Of Death', 'Iron Maiden'),
 ('Fear Of The Dark', 'Iron Maiden'),
 ('Iron Maiden', 'Iron Maiden'),
 ('Killers', 'Iron Maiden'),
 ('Live After Death', 'Iron Maiden'),
 ('Live At Donington 1992 (Disc 1)', 'Iron Maiden'),
 ('Live At Donington 1992 (Disc 2)', 'Iron Maiden'),
 ('No Prayer For The Dying', 'Iron Maiden'),
 ('Piece Of Mind', 'Iron Maiden'),
 ('Powerslave', 'Iron Maiden'),
 ('Rock In Rio [CD1]', 'Iron Maiden'),
 ('Rock In Rio [CD2]', 'Iron Maiden'),
 ('Seventh Son of a Seventh Son', 'Iron Maiden'),
 ('Somewhere in Time', 'Iron Maiden'),
 ('The Number of The Beast', 'Iron Maiden'),
 ('The X Factor', 'Iron Maiden'),
 ('Virtual XI', 'Iron Maiden'),
 ("Great Recordings of the Century: Paganini's 24 Caprices", 'Itzhak Perlman'),
 ('Get Born', 'JET'),
 ('Sex Machine', 'James Brown'),
 ('Mascagni: Cavalleria Rusticana', 'James Levine'),
 ('Emergency On Planet Earth', 'Jamiroquai'),
 ('Synkronized', 'Jamiroquai'),
 ('The Return Of The Space Cowboy', 'Jamiroquai'),
 ('Are You Experienced?', 'Jimi Hendrix'),
 ('Surfing with the Alien (Remastered)', 'Joe Satriani'),
 ('Jorge Ben Jor 25 Anos', 'Jorge Ben'),
 ('Jota Quest-1995', 'Jota Quest'),
 ('Cafezinho', 'João Suplicy'),
 ('Living After Midnight', 'Judas Priest'),
 ('J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro',
  'Julian Bream'),
 ('Realize', 'Karsh Kale'),
 ('Weill: The Seven Deadly Sins',
  "Kent Nagano and Orchestre de l'Opéra de Lyon"),
 ('Greatest Kiss', 'Kiss'),
 ('Unplugged [Live]', 'Kiss'),
 ('BBC Sessions [Disc 1] [Live]', 'Led Zeppelin'),
 ('Physical Graffiti [Disc 1]', 'Led Zeppelin'),
 ('BBC Sessions [Disc 2] [Live]', 'Led Zeppelin'),
 ('Coda', 'Led Zeppelin'),
 ('Houses Of The Holy', 'Led Zeppelin'),
 ('In Through The Out Door', 'Led Zeppelin'),
 ('IV', 'Led Zeppelin'),
 ('Led Zeppelin I', 'Led Zeppelin'),
 ('Led Zeppelin II', 'Led Zeppelin'),
 ('Led Zeppelin III', 'Led Zeppelin'),
 ('Physical Graffiti [Disc 2]', 'Led Zeppelin'),
 ('Presence', 'Led Zeppelin'),
 ('The Song Remains The Same (Disc 1)', 'Led Zeppelin'),
 ('The Song Remains The Same (Disc 2)', 'Led Zeppelin'),
 ('A TempestadeTempestade Ou O Livro Dos Dias', 'Legião Urbana'),
 ('Mais Do Mesmo', 'Legião Urbana'),
 ('Greatest Hits', 'Lenny Kravitz'),
 ("Great Performances - Barber's Adagio and Other Romantic Favorites for Strings",
  'Leonard Bernstein & New York Philharmonic'),
 ('Charpentier: Divertissements, Airs & Concerts',
  'Les Arts Florissants & William Christie'),
 ('Tchaikovsky: The Nutcracker',
  'London Symphony Orchestra & Sir Charles Mackerras'),
 ('Lost, Season 3', 'Lost'),
 ('Lost, Season 1', 'Lost'),
 ('Lost, Season 2', 'Lost'),
 ('LOST, Season 4', 'Lost'),
 ('Duos II', 'Luciana Souza/Romero Lubambo'),
 ("Pavarotti's Opera Made Easy", 'Luciano Pavarotti'),
 ('Lulu Santos - RCA 100 Anos De Música - Álbum 01', 'Lulu Santos'),
 ('Lulu Santos - RCA 100 Anos De Música - Álbum 02', 'Lulu Santos'),
 ('Chill: Brazil (Disc 1)', 'Marcos Valle'),
 ('Misplaced Childhood', 'Marillion'),
 ('Barulhinho Bom', 'Marisa Monte'),
 ('Szymanowski: Piano Works, Vol. 1', 'Martin Roscoe'),
 ('Seek And Shall Find: More Of The Best (1963-1981)', 'Marvin Gaye'),
 ('Beethoven Piano Sonatas: Moonlight & Pastorale', 'Maurizio Pollini'),
 ('Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3',
  'Mela Tenenbaum, Pro Musica Prague & Richard Kapp'),
 ('The Best Of Men At Work', 'Men At Work'),
 ('Garage Inc. (Disc 1)', 'Metallica'),
 ('Black Album', 'Metallica'),
 ('Garage Inc. (Disc 2)', 'Metallica'),
 ("Kill 'Em All", 'Metallica'),
 ('Load', 'Metallica'),
 ('Master Of Puppets', 'Metallica'),
 ('ReLoad', 'Metallica'),
 ('Ride The Lightning', 'Metallica'),
 ('St. Anger', 'Metallica'),
 ('...And Justice For All', 'Metallica'),
 ('Prokofiev: Romeo & Juliet',
  'Michael Tilson Thomas & San Francisco Symphony'),
 ('Berlioz: Symphonie Fantastique',
  'Michael Tilson Thomas & San Francisco Symphony'),
 ("Liszt - 12 Études D'Execution Transcendante", 'Michele Campanella'),
 ('The Essential Miles Davis [Disc 1]', 'Miles Davis'),
 ('The Essential Miles Davis [Disc 2]', 'Miles Davis'),
 ('Miles Ahead', 'Miles Davis'),
 ('Milton Nascimento Ao Vivo', 'Milton Nascimento'),
 ('Minas', 'Milton Nascimento'),
 ('Ace Of Spades', 'Motörhead'),
 ('Demorou...', 'Mônica Marianno'),
 ('Motley Crue Greatest Hits', 'Mötley Crüe'),
 ('Mozart: Chamber Music', 'Nash Ensemble'),
 ('The Best of Beethoven', 'Nicolaus Esterhazy Sinfonia'),
 ('From The Muddy Banks Of The Wishkah [Live]', 'Nirvana'),
 ('Nevermind', 'Nirvana'),
 ('Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro',
  'O Rappa'),
 ('Compositores', 'O Terço'),
 ('Olodum', 'Olodum'),
 ('Bach: The Brandenburg Concertos', 'Orchestra of The Age of Enlightenment'),
 ('Beethoven: Symhonies Nos. 5 & 6',
  'Orchestre Révolutionnaire et Romantique & John Eliot Gardiner'),
 ('Minha História', 'Os Mutantes'),
 ('Acústico MTV', 'Os Paralamas Do Sucesso'),
 ('Arquivo II', 'Os Paralamas Do Sucesso'),
 ('Arquivo Os Paralamas Do Sucesso', 'Os Paralamas Do Sucesso'),
 ("Beethoven: Symphony No. 6 'Pastoral' Etc.",
  'Otto Klemperer & Philharmonia Orchestra'),
 ('Bark at the Moon (Remastered)', 'Ozzy Osbourne'),
 ('Blizzard of Ozz', 'Ozzy Osbourne'),
 ('Diary of a Madman (Remastered)', 'Ozzy Osbourne'),
 ('No More Tears (Remastered)', 'Ozzy Osbourne'),
 ('Tribute', 'Ozzy Osbourne'),
 ('Speak of the Devil', 'Ozzy Osbourne'),
 ('Walking Into Clarksdale', 'Page & Plant'),
 ('Original Soundtracks 1', 'Passengers'),
 ('The Beast Live', "Paul D'Ianno"),
 ('Live On Two Legs [Live]', 'Pearl Jam'),
 ('Pearl Jam', 'Pearl Jam'),
 ('Riot Act', 'Pearl Jam'),
 ('Ten', 'Pearl Jam'),
 ('Vs.', 'Pearl Jam'),
 ("Mendelssohn: A Midsummer Night's Dream",
  'Philharmonia Orchestra & Sir Neville Marriner'),
 ('Koyaanisqatsi (Soundtrack from the Motion Picture)',
  'Philip Glass Ensemble'),
 ('Dark Side Of The Moon', 'Pink Floyd'),
 ('Os Cães Ladram Mas A Caravana Não Pára', 'Planet Hemp'),
 ('Greatest Hits II', 'Queen'),
 ('Greatest Hits I', 'Queen'),
 ('News Of The World', 'Queen'),
 ('Green', 'R.E.M.'),
 ('New Adventures In Hi-Fi', 'R.E.M.'),
 ('The Best Of R.E.M.: The IRS Years', 'R.E.M.'),
 ('Out Of Time', 'R.E.M. Feat. Kate Pearson'),
 ('Cesta Básica', 'Raimundos'),
 ('Raul Seixas', 'Raul Seixas'),
 ('Blood Sugar Sex Magik', 'Red Hot Chili Peppers'),
 ('By The Way', 'Red Hot Chili Peppers'),
 ('Californication', 'Red Hot Chili Peppers'),
 ('Allegri: Miserere',
  'Richard Marlow & The Choir of Trinity College, Cambridge'),
 ('Purcell: The Fairy Queen', 'Roger Norrington, London Classical Players'),
 ('Haydn: Symphonies 99 - 104',
  'Royal Philharmonic Orchestra & Sir Thomas Beecham'),
 ('Retrospective I (1974-1980)', 'Rush'),
 ('Supernatural', 'Santana'),
 ('Santana - As Years Go By', 'Santana'),
 ('Santana Live', 'Santana'),
 ('Handel: The Messiah (Highlights)', 'Scholars Baroque Ensemble'),
 ('20th Century Masters - The Millennium Collection: The Best of Scorpions',
  'Scorpions'),
 ('Prokofiev: Symphony No.1', 'Sergei Prokofiev & Yuri Temirkanov'),
 ('Wagner: Favourite Overtures', 'Sir Georg Solti & Wiener Philharmoniker'),
 ('Mozart Gala: Famous Arias',
  'Sir Georg Solti, Sumi Jo & Wiener Philharmoniker'),
 ('Maquinarama', 'Skank'),
 ('O Samba Poconé', 'Skank'),
 ('Judas 0: B-Sides and Rarities', 'Smashing Pumpkins'),
 ('Rotten Apples: Greatest Hits', 'Smashing Pumpkins'),
 ('A-Sides', 'Soundgarden'),
 ('Heart of the Night', 'Spyro Gyra'),
 ('Morning Dance', 'Spyro Gyra'),
 ('In Step', 'Stevie Ray Vaughan & Double Trouble'),
 ('Core', 'Stone Temple Pilots'),
 ('Mezmerize', 'System Of A Down'),
 ('Temple of the Dog', 'Temple of the Dog'),
 ('[1997] Black Light Syndrome', 'Terry Bozzio, Tony Levin & Steve Stevens'),
 ('South American Getaway', 'The 12 Cellists of The Berlin Philharmonic'),
 ('Live [Disc 1]', 'The Black Crowes'),
 ('Live [Disc 2]', 'The Black Crowes'),
 ('The Singles', 'The Clash'),
 ('Beyond Good And Evil', 'The Cult'),
 ('Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]',
  'The Cult'),
 ('The Doors', 'The Doors'),
 ('English Renaissance', "The King's Singers"),
 ('The Office, Season 1', 'The Office'),
 ('The Office, Season 2', 'The Office'),
 ('The Office, Season 3', 'The Office'),
 ('The Police Greatest Hits', 'The Police'),
 ('Every Kind of Light', 'The Posies'),
 ('Hot Rocks, 1964-1971 (Disc 1)', 'The Rolling Stones'),
 ('No Security', 'The Rolling Stones'),
 ('Voodoo Lounge', 'The Rolling Stones'),
 ('Tangents', 'The Tea Party'),
 ('Transmission', 'The Tea Party'),
 ('My Generation - The Very Best Of The Who', 'The Who'),
 ('Serie Sem Limite (Disc 1)', 'Tim Maia'),
 ('Serie Sem Limite (Disc 2)', 'Tim Maia'),
 ('Acústico', 'Titãs'),
 ('Volume Dois', 'Titãs'),
 ('Bach: Toccata & Fugue in D Minor', 'Ton Koopman'),
 ('Vinícius De Moraes - Sem Limite', 'Toquinho & Vinícius'),
 ('Achtung Baby', 'U2'),
 ("All That You Can't Leave Behind", 'U2'),
 ('B-Sides 1980-1990', 'U2'),
 ('How To Dismantle An Atomic Bomb', 'U2'),
 ('Pop', 'U2'),
 ('Rattle And Hum', 'U2'),
 ('The Best Of 1980-1990', 'U2'),
 ('War', 'U2'),
 ('Zooropa', 'U2'),
 ('Instant Karma: The Amnesty International Campaign to Save Darfur', 'U2'),
 ('UB40 The Best Of - Volume Two [UK]', 'UB40'),
 ('Diver Down', 'Van Halen'),
 ('The Best Of Van Halen, Vol. I', 'Van Halen'),
 ('Van Halen', 'Van Halen'),
 ('Van Halen III', 'Van Halen'),
 ('Axé Bahia 2001', 'Various Artists'),
 ('Carnaval 2001', 'Various Artists'),
 ('Sambas De Enredo 2001', 'Various Artists'),
 ('Vozes do MPB', 'Various Artists'),
 ('Contraband', 'Velvet Revolver'),
 ('Vinicius De Moraes', 'Vinícius De Moraes'),
 ('Bach: Goldberg Variations', 'Wilhelm Kempff'),
 ('Bartok: Violin & Viola Concertos', 'Yehudi Menuhin'),
 ('Bach: The Cello Suites', 'Yo-Yo Ma'),
 ('Ao Vivo [IMPORT]', 'Zeca Pagodinho')]

## JOIN Three Tables

In [23]:
# Join three related tables

cursor.execute('''
SELECT a.Title AS artist, ar.Name AS album, t.name AS track
FROM albums AS a
INNER JOIN artists AS ar
ON  a.ArtistId = ar.ArtistId
INNER JOIN tracks AS t
ON a.AlbumId = t.AlbumId
ORDER BY ar.name
''')
# albums   --> a
# artistrs --> ar

result = cursor.fetchall()
result

[('For Those About To Rock We Salute You',
  'AC/DC',
  'For Those About To Rock (We Salute You)'),
 ('For Those About To Rock We Salute You', 'AC/DC', 'Put The Finger On You'),
 ('For Those About To Rock We Salute You', 'AC/DC', "Let's Get It Up"),
 ('For Those About To Rock We Salute You', 'AC/DC', 'Inject The Venom'),
 ('For Those About To Rock We Salute You', 'AC/DC', 'Snowballed'),
 ('For Those About To Rock We Salute You', 'AC/DC', 'Evil Walks'),
 ('For Those About To Rock We Salute You', 'AC/DC', 'C.O.D.'),
 ('For Those About To Rock We Salute You', 'AC/DC', 'Breaking The Rules'),
 ('For Those About To Rock We Salute You',
  'AC/DC',
  'Night Of The Long Knives'),
 ('For Those About To Rock We Salute You', 'AC/DC', 'Spellbound'),
 ('Let There Be Rock', 'AC/DC', 'Go Down'),
 ('Let There Be Rock', 'AC/DC', 'Dog Eat Dog'),
 ('Let There Be Rock', 'AC/DC', 'Let There Be Rock'),
 ('Let There Be Rock', 'AC/DC', 'Bad Boy Boogie'),
 ('Let There Be Rock', 'AC/DC', 'Problem Child'),
 ('Let There Be Rock', 'AC/DC', 'Overdose'),
 ('Let There Be Rock', 'AC/DC', "Hell Ain't A Bad Place To Be"),
 ('Let There Be Rock', 'AC/DC', 'Whole Lotta Rosie'),
 ('A Copland Celebration, Vol. I',
  'Aaron Copland & London Symphony Orchestra',
  'Fanfare for the Common Man'),
 ('Worlds', 'Aaron Goldberg', "OAM's Blues"),
 ('The World of Classical Favourites',
  'Academy of St. Martin in the Fields & Sir Neville Marriner',
  'Solomon HWV 67: The Arrival of the Queen of Sheba'),
 ('The World of Classical Favourites',
  'Academy of St. Martin in the Fields & Sir Neville Marriner',
  'Fantasia On Greensleeves'),
 ('Sir Neville Marriner: A Celebration',
  'Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner',
  '"Eine Kleine Nachtmusik" Serenade In G, K. 525: I. Allegro'),
 ('Fauré: Requiem, Ravel: Pavane & Others',
  'Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair',
  'Requiem, Op.48: 4. Pie Jesu'),
 ('Bach: Orchestral Suites Nos. 1 - 4',
  'Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart',
  'Suite No. 3 in D, BWV 1068: III. Gavotte I & II'),
 ('Balls to the Wall', 'Accept', 'Balls to the Wall'),
 ('Restless and Wild', 'Accept', 'Fast As a Shark'),
 ('Restless and Wild', 'Accept', 'Restless and Wild'),
 ('Restless and Wild', 'Accept', 'Princess of the Dawn'),
 ('Górecki: Symphony No. 3',
  'Adrian Leaper & Doreen de Feis',
  'Symphony No. 3 Op. 36 for Orchestra and Soprano "Symfonia Piesni Zalosnych" \\ Lento E Largo - Tranquillissimo'),
 ('Big Ones', 'Aerosmith', 'Walk On Water'),
 ('Big Ones', 'Aerosmith', 'Love In An Elevator'),
 ('Big Ones', 'Aerosmith', 'Rag Doll'),
 ('Big Ones', 'Aerosmith', 'What It Takes'),
 ('Big Ones', 'Aerosmith', 'Dude (Looks Like A Lady)'),
 ('Big Ones', 'Aerosmith', "Janie's Got A Gun"),
 ('Big Ones', 'Aerosmith', "Cryin'"),
 ('Big Ones', 'Aerosmith', 'Amazing'),
 ('Big Ones', 'Aerosmith', 'Blind Man'),
 ('Big Ones', 'Aerosmith', 'Deuces Are Wild'),
 ('Big Ones', 'Aerosmith', 'The Other Side'),
 ('Big Ones', 'Aerosmith', 'Crazy'),
 ('Big Ones', 'Aerosmith', 'Eat The Rich'),
 ('Big Ones', 'Aerosmith', 'Angel'),
 ('Big Ones', 'Aerosmith', "Livin' On The Edge"),
 ('Quiet Songs', 'Aisha Duo', 'Amanda'),
 ('Quiet Songs', 'Aisha Duo', 'Despertar'),
 ('Jagged Little Pill', 'Alanis Morissette', 'All I Really Want'),
 ('Jagged Little Pill', 'Alanis Morissette', 'You Oughta Know'),
 ('Jagged Little Pill', 'Alanis Morissette', 'Perfect'),
 ('Jagged Little Pill', 'Alanis Morissette', 'Hand In My Pocket'),
 ('Jagged Little Pill', 'Alanis Morissette', 'Right Through You'),
 ('Jagged Little Pill', 'Alanis Morissette', 'Forgiven'),
 ('Jagged Little Pill', 'Alanis Morissette', 'You Learn'),
 ('Jagged Little Pill', 'Alanis Morissette', 'Head Over Feet'),
 ('Jagged Little Pill', 'Alanis Morissette', 'Mary Jane'),
 ('Jagged Little Pill', 'Alanis Morissette', 'Ironic'),
 ('Jagged Little Pill', 'Alanis Morissette', 'Not The Doctor'),
 ('Jagged Little Pill', 'Alanis Morissette', 'Wake Up'),
 ('Jagged Little Pill', 'Alanis Morissette', 'You Oughta Know (Alternate)'),
 ('Adorate Deum: Gregorian Chant from the Proper of the Mass',
  'Alberto Turco & Nova Schola Gregoriana',
  'Intoitus: Adorate Deum'),
 ('Facelift', 'Alice In Chains', 'We Die Young'),
 ('Facelift', 'Alice In Chains', 'Man In The Box'),
 ('Facelift', 'Alice In Chains', 'Sea Of Sorrow'),
 ('Facelift', 'Alice In Chains', 'Bleed The Freak'),
 ('Facelift', 'Alice In Chains', "I Can't Remember"),
 ('Facelift', 'Alice In Chains', 'Love, Hate, Love'),
 ('Facelift', 'Alice In Chains', "It Ain't Like That"),
 ('Facelift', 'Alice In Chains', 'Sunshine'),
 ('Facelift', 'Alice In Chains', 'Put You Down'),
 ('Facelift', 'Alice In Chains', 'Confusion'),
 ('Facelift', 'Alice In Chains', 'I Know Somethin (Bout You)'),
 ('Facelift', 'Alice In Chains', 'Real Thing'),
 ('Back to Black', 'Amy Winehouse', 'Rehab'),
 ('Back to Black', 'Amy Winehouse', "You Know I'm No Good"),
 ('Back to Black', 'Amy Winehouse', 'Me & Mr. Jones'),
 ('Back to Black', 'Amy Winehouse', 'Just Friends'),
 ('Back to Black', 'Amy Winehouse', 'Back to Black'),
 ('Back to Black', 'Amy Winehouse', 'Love Is a Losing Game'),
 ('Back to Black', 'Amy Winehouse', 'Tears Dry On Their Own'),
 ('Back to Black', 'Amy Winehouse', 'Wake Up Alone'),
 ('Back to Black', 'Amy Winehouse', 'Some Unholy War'),
 ('Back to Black', 'Amy Winehouse', 'He Can Only Hold Her'),
 ('Back to Black',
  'Amy Winehouse',
  "You Know I'm No Good (feat. Ghostface Killah)"),
 ('Back to Black', 'Amy Winehouse', 'Rehab (Hot Chip Remix)'),
 ('Frank', 'Amy Winehouse', 'Intro / Stronger Than Me'),
 ('Frank', 'Amy Winehouse', 'You Sent Me Flying / Cherry'),
 ('Frank', 'Amy Winehouse', 'F**k Me Pumps'),
 ('Frank', 'Amy Winehouse', 'I Heard Love Is Blind'),
 ('Frank', 'Amy Winehouse', '(There Is) No Greater Love (Teo Licks)'),
 ('Frank', 'Amy Winehouse', 'In My Bed'),
 ('Frank', 'Amy Winehouse', 'Take the Box'),
 ('Frank', 'Amy Winehouse', 'October Song'),
 ('Frank', 'Amy Winehouse', 'What Is It About Men'),
 ('Frank', 'Amy Winehouse', 'Help Yourself'),
 ('Frank', 'Amy Winehouse', 'Amy Amy Amy (Outro)'),
 ('Vivaldi: The Four Seasons',
  'Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker',
  'Concerto No. 1 in E Major, RV 269 "Spring": I. Allegro'),
 ("Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington's Victory",
  'Antal Doráti & London Symphony Orchestra',
  "Wellington's Victory or the Battle Symphony, Op.91: 2. Symphony of Triumph"),
 ('Warner 25 Anos', 'Antônio Carlos Jobim', 'Desafinado'),
 ('Warner 25 Anos', 'Antônio Carlos Jobim', 'Garota De Ipanema'),
 ('Warner 25 Anos',
  'Antônio Carlos Jobim',
  'Samba De Uma Nota Só (One Note Samba)'),
 ('Warner 25 Anos', 'Antônio Carlos Jobim', 'Por Causa De Você'),
 ('Warner 25 Anos', 'Antônio Carlos Jobim', 'Ligia'),
 ('Warner 25 Anos', 'Antônio Carlos Jobim', 'Fotografia'),
 ('Warner 25 Anos', 'Antônio Carlos Jobim', 'Dindi (Dindi)'),
 ('Warner 25 Anos',
  'Antônio Carlos Jobim',
  'Se Todos Fossem Iguais A Você (Instrumental)'),
 ('Warner 25 Anos', 'Antônio Carlos Jobim', 'Falando De Amor'),
 ('Warner 25 Anos', 'Antônio Carlos Jobim', 'Angela'),
 ('Warner 25 Anos',
  'Antônio Carlos Jobim',
  'Corcovado (Quiet Nights Of Quiet Stars)'),
 ('Warner 25 Anos', 'Antônio Carlos Jobim', 'Outra Vez'),
 ('Warner 25 Anos', 'Antônio Carlos Jobim', 'O Boto (Bôto)'),
 ('Warner 25 Anos', 'Antônio Carlos Jobim', 'Canta, Canta Mais'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Garota De Ipanema'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Tim Tim Por Tim Tim'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Tarde Em Itapoã'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Tanto Tempo'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Eu Vim Da Bahia - Live'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Alô Alô Marciano'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Linha Do Horizonte'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Only A Dream In Rio'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Abrir A Porta'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Alice'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Momentos Que Marcam'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Um Jantar Pra Dois'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Bumbo Da Mangueira'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Mr Funk Samba'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Santo Antonio'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim', 'Por Você'),
 ('Chill: Brazil (Disc 2)',
  'Antônio Carlos Jobim',
  'Só Tinha De Ser Com Você'),
 ('Plays Metallica By Four Cellos', 'Apocalyptica', 'Enter Sandman'),
 ('Plays Metallica By Four Cellos', 'Apocalyptica', 'Master Of Puppets'),
 ('Plays Metallica By Four Cellos', 'Apocalyptica', 'Harvester Of Sorrow'),
 ('Plays Metallica By Four Cellos', 'Apocalyptica', 'The Unforgiven'),
 ('Plays Metallica By Four Cellos', 'Apocalyptica', 'Sad But True'),
 ('Plays Metallica By Four Cellos', 'Apocalyptica', 'Creeping Death'),
 ('Plays Metallica By Four Cellos', 'Apocalyptica', 'Wherever I May Roam'),
 ('Plays Metallica By Four Cellos',
  'Apocalyptica',
  'Welcome Home (Sanitarium)'),
 ('Aquaman', 'Aquaman', 'Pilot'),
 ('Audioslave', 'Audioslave', 'Cochise'),
 ('Audioslave', 'Audioslave', 'Show Me How to Live'),
 ('Audioslave', 'Audioslave', 'Gasoline'),
 ('Audioslave', 'Audioslave', 'What You Are'),
 ('Audioslave', 'Audioslave', 'Like a Stone'),
 ('Audioslave', 'Audioslave', 'Set It Off'),
 ('Audioslave', 'Audioslave', 'Shadow on the Sun'),
 ('Audioslave', 'Audioslave', 'I am the Highway'),
 ('Audioslave', 'Audioslave', 'Exploder'),
 ('Audioslave', 'Audioslave', 'Hypnotize'),
 ('Audioslave', 'Audioslave', "Bring'em Back Alive"),
 ('Audioslave', 'Audioslave', 'Light My Way'),
 ('Audioslave', 'Audioslave', 'Getaway Car'),
 ('Audioslave', 'Audioslave', 'The Last Remaining Light'),
 ('Out Of Exile', 'Audioslave', 'Your Time Has Come'),
 ('Out Of Exile', 'Audioslave', 'Out Of Exile'),
 ('Out Of Exile', 'Audioslave', 'Be Yourself'),
 ('Out Of Exile', 'Audioslave', "Doesn't Remind Me"),
 ('Out Of Exile', 'Audioslave', 'Drown Me Slowly'),
 ('Out Of Exile', 'Audioslave', "Heaven's Dead"),
 ('Out Of Exile', 'Audioslave', 'The Worm'),
 ('Out Of Exile', 'Audioslave', 'Man Or Animal'),
 ('Out Of Exile', 'Audioslave', 'Yesterday To Tomorrow'),
 ('Out Of Exile', 'Audioslave', 'Dandelion'),
 ('Out Of Exile', 'Audioslave', '#1 Zero'),
 ('Out Of Exile', 'Audioslave', 'The Curse'),
 ('Revelations', 'Audioslave', 'Revelations'),
 ('Revelations', 'Audioslave', 'One and the Same'),
 ('Revelations', 'Audioslave', 'Sound of a Gun'),
 ('Revelations', 'Audioslave', 'Until We Fall'),
 ('Revelations', 'Audioslave', 'Original Fire'),
 ('Revelations', 'Audioslave', 'Broken City'),
 ('Revelations', 'Audioslave', 'Somedays'),
 ('Revelations', 'Audioslave', 'Shape of Things to Come'),
 ('Revelations', 'Audioslave', 'Jewel of the Summertime'),
 ('Revelations', 'Audioslave', 'Wide Awake'),
 ('Revelations', 'Audioslave', 'Nothing Left to Say But Goodbye'),
 ('Revelations', 'Audioslave', 'Moth'),
 ('Revelations',
  'Audioslave',
  'Show Me How to Live (Live at the Quart Festival)'),
 ('Revelations',
  'Audioslave',
  'Band Members Discuss Tracks from "Revelations"'),
 ('BackBeat Soundtrack', 'BackBeat', 'Money'),
 ('BackBeat Soundtrack', 'BackBeat', 'Long Tall Sally'),
 ('BackBeat Soundtrack', 'BackBeat', 'Bad Boy'),
 ('BackBeat Soundtrack', 'BackBeat', 'Twist And Shout'),
 ('BackBeat Soundtrack', 'BackBeat', 'Please Mr. Postman'),
 ('BackBeat Soundtrack', 'BackBeat', "C'Mon Everybody"),
 ('BackBeat Soundtrack', 'BackBeat', "Rock 'N' Roll Music"),
 ('BackBeat Soundtrack', 'BackBeat', 'Slow Down'),
 ('BackBeat Soundtrack', 'BackBeat', 'Roadrunner'),
 ('BackBeat Soundtrack', 'BackBeat', 'Carol'),
 ('BackBeat Soundtrack', 'BackBeat', 'Good Golly Miss Molly'),
 ('BackBeat Soundtrack', 'BackBeat', '20 Flight Rock'),
 ('The Last Night of the Proms',
  'Barry Wordsworth & BBC Concert Orchestra',
  'Nimrod (Adagio) from Variations On an Original Theme, Op. 36 "Enigma"'),
 ('Battlestar Galactica: The Story So Far',
  'Battlestar Galactica',
  'Battlestar Galactica: The Story So Far'),
 ('Battlestar Galactica, Season 3',
  'Battlestar Galactica',
  'Occupation / Precipice'),
 ('Battlestar Galactica, Season 3', 'Battlestar Galactica', 'Exodus, Pt. 1'),
 ('Battlestar Galactica, Season 3', 'Battlestar Galactica', 'Exodus, Pt. 2'),
 ('Battlestar Galactica, Season 3', 'Battlestar Galactica', 'Collaborators'),
 ('Battlestar Galactica, Season 3', 'Battlestar Galactica', 'Torn'),
 ('Battlestar Galactica, Season 3',
  'Battlestar Galactica',
  'A Measure of Salvation'),
 ('Battlestar Galactica, Season 3', 'Battlestar Galactica', 'Hero'),
 ('Battlestar Galactica, Season 3',
  'Battlestar Galactica',
  'Unfinished Business'),
 ('Battlestar Galactica, Season 3', 'Battlestar Galactica', 'The Passage'),
 ('Battlestar Galactica, Season 3',
  'Battlestar Galactica',
  'The Eye of Jupiter'),
 ('Battlestar Galactica, Season 3', 'Battlestar Galactica', 'Rapture'),
 ('Battlestar Galactica, Season 3',
  'Battlestar Galactica',
  'Taking a Break from All Your Worries'),
 ('Battlestar Galactica, Season 3', 'Battlestar Galactica', 'The Woman King'),
 ('Battlestar Galactica, Season 3',
  'Battlestar Galactica',
  'A Day In the Life'),
 ('Battlestar Galactica, Season 3', 'Battlestar Galactica', 'Dirty Hands'),
 ('Battlestar Galactica, Season 3', 'Battlestar Galactica', 'Maelstrom'),
 ('Battlestar Galactica, Season 3',
  'Battlestar Galactica',
  'The Son Also Rises'),
 ('Battlestar Galactica, Season 3',
  'Battlestar Galactica',
  'Crossroads, Pt. 1'),
 ('Battlestar Galactica, Season 3',
  'Battlestar Galactica',
  'Crossroads, Pt. 2'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'Battlestar Galactica, Pt. 1'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'Battlestar Galactica, Pt. 2'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'Battlestar Galactica, Pt. 3'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'Lost Planet of the Gods, Pt. 1'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'Lost Planet of the Gods, Pt. 2'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'The Lost Warrior'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'The Long Patrol'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'The Gun On Ice Planet Zero, Pt. 1'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'The Gun On Ice Planet Zero, Pt. 2'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'The Magnificent Warriors'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'The Young Lords'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'The Living Legend, Pt. 1'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'The Living Legend, Pt. 2'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'Fire In Space'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'War of the Gods, Pt. 1'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'War of the Gods, Pt. 2'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'The Man With Nine Lives'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'Murder On the Rising Star'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'Greetings from Earth, Pt. 1'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'Greetings from Earth, Pt. 2'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  "Baltar's Escape"),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'Experiment In Terra'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'Take the Celestra'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)',
  'The Hand of God'),
 ('Sibelius: Finlandia',
  'Berliner Philharmoniker & Hans Rosbaud',
  'Karelia Suite, Op.11: 2. Ballade (Tempo Di Menuetto)'),
 ('Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande',
  'Berliner Philharmoniker & Herbert Von Karajan',
  'Peer Gynt Suite No.1, Op.46: 1. Morning Mood'),
 ('Mozart: Symphonies Nos. 40 & 41',
  'Berliner Philharmoniker & Herbert Von Karajan',
  'Symphony No. 41 in C Major, K. 551, "Jupiter": IV. Molto allegro'),
 ('Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps',
  'Berliner Philharmoniker & Herbert Von Karajan',
  'Le Sacre Du Printemps: I.iv. Spring Rounds'),
 ('Mozart: Wind Concertos',
  'Berliner Philharmoniker, Claudio Abbado & Sabine Meyer',
  'Concerto for Clarinet in A Major, K. 622: II. Adagio'),
 ('The Best Of Billy Cobham', 'Billy Cobham', 'Quadrant'),
 ('The Best Of Billy Cobham', 'Billy Cobham', "Snoopy's search-Red baron"),
 ('The Best Of Billy Cobham',
  'Billy Cobham',
  'Spanish moss-"A sound portrait"-Spanish moss'),
 ('The Best Of Billy Cobham', 'Billy Cobham', 'Moon germs'),
 ('The Best Of Billy Cobham', 'Billy Cobham', 'Stratus'),
 ('The Best Of Billy Cobham', 'Billy Cobham', 'The pleasant pheasant'),
 ('The Best Of Billy Cobham', 'Billy Cobham', 'Solo-Panhandler'),
 ('The Best Of Billy Cobham', 'Billy Cobham', 'Do what cha wanna'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]',
  'Black Label Society',
  'Intro/ Low Down'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]',
  'Black Label Society',
  '13 Years Of Grief'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]',
  'Black Label Society',
  'Stronger Than Death'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]',
  'Black Label Society',
  'All For You'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]',
  'Black Label Society',
  'Super Terrorizer'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]',
  'Black Label Society',
  'Phoney Smile Fake Hellos'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]',
  'Black Label Society',
  'Lost My Better Half'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]',
  'Black Label Society',
  'Bored To Tears'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]',
  'Black Label Society',
  'A.N.D.R.O.T.A.Z.'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]',
  'Black Label Society',
  'Born To Booze'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]',
  'Black Label Society',
  'World Of Trouble'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]',
  'Black Label Society',
  'No More Tears'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]',
  'Black Label Society',
  'The Begining... At Last'),
 ('Alcohol Fueled Brewtality Live! [Disc 2]',
  'Black Label Society',
  'Heart Of Gold'),
 ('Alcohol Fueled Brewtality Live! [Disc 2]',
  'Black Label Society',
  'Snowblind'),
 ('Alcohol Fueled Brewtality Live! [Disc 2]',
  'Black Label Society',
  'Like A Bird'),
 ('Alcohol Fueled Brewtality Live! [Disc 2]',
  'Black Label Society',
  'Blood In The Wall'),
 ('Alcohol Fueled Brewtality Live! [Disc 2]',
  'Black Label Society',
  'The Beginning...At Last'),
 ('Black Sabbath', 'Black Sabbath', 'Black Sabbath'),
 ('Black Sabbath', 'Black Sabbath', 'The Wizard'),
 ('Black Sabbath', 'Black Sabbath', 'Behind The Wall Of Sleep'),
 ('Black Sabbath', 'Black Sabbath', 'N.I.B.'),
 ('Black Sabbath', 'Black Sabbath', 'Evil Woman'),
 ('Black Sabbath', 'Black Sabbath', 'Sleeping Village'),
 ('Black Sabbath', 'Black Sabbath', 'Warning'),

## JOINT + Pandas

In [24]:
df = pd.read_sql_query('''
SELECT a.Title AS artist, ar.Name AS album, t.name AS track
FROM albums AS a
INNER JOIN artists AS ar
ON  a.ArtistId = ar.ArtistId
INNER JOIN tracks AS t
ON a.AlbumId = t.AlbumId
ORDER BY ar.name
''', conn)

df

,artist,album,track
0,For Those About To Rock We Salute You,AC/DC,For Those About To Rock (We Salute You)
1,For Those About To Rock We Salute You,AC/DC,Put The Finger On You
2,For Those About To Rock We Salute You,AC/DC,Let's Get It Up
3,For Those About To Rock We Salute You,AC/DC,Inject The Venom
4,For Those About To Rock We Salute You,AC/DC,Snowballed
...,...,...,...
3498,Ao Vivo [IMPORT],Zeca Pagodinho,Sapopemba e Maxambomba
3499,Ao Vivo [IMPORT],Zeca Pagodinho,Minha Fé
3500,Ao Vivo [IMPORT],Zeca Pagodinho,Lua de Ogum
3501,Ao Vivo [IMPORT],Zeca Pagodinho,Samba pras moças
3502,Ao Vivo [IMPORT],Zeca Pagodinho,Verdade

## Left JOIN

In [27]:
cursor.execute('''
SELECT a.Title, ar.Name
FROM albums AS a
LEFT JOIN artists AS ar
ON  a.ArtistId = ar.ArtistId
ORDER BY ar.name
''')
result = cursor.fetchall()
result

[('For Those About To Rock We Salute You', 'AC/DC'),
 ('Let There Be Rock', 'AC/DC'),
 ('A Copland Celebration, Vol. I',
  'Aaron Copland & London Symphony Orchestra'),
 ('Worlds', 'Aaron Goldberg'),
 ('The World of Classical Favourites',
  'Academy of St. Martin in the Fields & Sir Neville Marriner'),
 ('Sir Neville Marriner: A Celebration',
  'Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner'),
 ('Fauré: Requiem, Ravel: Pavane & Others',
  'Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair'),
 ('Bach: Orchestral Suites Nos. 1 - 4',
  'Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart'),
 ('Balls to the Wall', 'Accept'),
 ('Restless and Wild', 'Accept'),
 ('Górecki: Symphony No. 3', 'Adrian Leaper & Doreen de Feis'),
 ('Big Ones', 'Aerosmith'),
 ('Quiet Songs', 'Aisha Duo'),
 ('Jagged Little Pill', 'Alanis Morissette'),
 ('Adorate Deum: Gregorian Chant from the Proper of the Mass',
  'Alberto Turco & Nova Schola Gregoriana'),
 ('Facelift', 'Alice In Chains'),
 ('Back to Black', 'Amy Winehouse'),
 ('Frank', 'Amy Winehouse'),
 ('Vivaldi: The Four Seasons',
  'Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker'),
 ("Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington's Victory",
  'Antal Doráti & London Symphony Orchestra'),
 ('Warner 25 Anos', 'Antônio Carlos Jobim'),
 ('Chill: Brazil (Disc 2)', 'Antônio Carlos Jobim'),
 ('Plays Metallica By Four Cellos', 'Apocalyptica'),
 ('Aquaman', 'Aquaman'),
 ('Audioslave', 'Audioslave'),
 ('Out Of Exile', 'Audioslave'),
 ('Revelations', 'Audioslave'),
 ('BackBeat Soundtrack', 'BackBeat'),
 ('The Last Night of the Proms', 'Barry Wordsworth & BBC Concert Orchestra'),
 ('Battlestar Galactica: The Story So Far', 'Battlestar Galactica'),
 ('Battlestar Galactica, Season 3', 'Battlestar Galactica'),
 ('Battlestar Galactica (Classic), Season 1',
  'Battlestar Galactica (Classic)'),
 ('Sibelius: Finlandia', 'Berliner Philharmoniker & Hans Rosbaud'),
 ('Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande',
  'Berliner Philharmoniker & Herbert Von Karajan'),
 ('Mozart: Symphonies Nos. 40 & 41',
  'Berliner Philharmoniker & Herbert Von Karajan'),
 ('Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps',
  'Berliner Philharmoniker & Herbert Von Karajan'),
 ('Mozart: Wind Concertos',
  'Berliner Philharmoniker, Claudio Abbado & Sabine Meyer'),
 ('The Best Of Billy Cobham', 'Billy Cobham'),
 ('Alcohol Fueled Brewtality Live! [Disc 1]', 'Black Label Society'),
 ('Alcohol Fueled Brewtality Live! [Disc 2]', 'Black Label Society'),
 ('Black Sabbath', 'Black Sabbath'),
 ('Black Sabbath Vol. 4 (Remaster)', 'Black Sabbath'),
 ('Body Count', 'Body Count'),
 ('Carmina Burana', 'Boston Symphony Orchestra & Seiji Ozawa'),
 ('A Soprano Inspired', 'Britten Sinfonia, Ivor Bolton & Lesley Garrett'),
 ('Chemical Wedding', 'Bruce Dickinson'),
 ('The Best Of Buddy Guy - The Millenium Collection', 'Buddy Guy'),
 ("Monteverdi: L'Orfeo",
  'C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu'),
 ('Prenda Minha', 'Caetano Veloso'),
 ('Sozinho Remix Ao Vivo', 'Caetano Veloso'),
 ('Cake: B-Sides and Rarities', 'Cake'),
 ('Carried to Dust (Bonus Track Version)', 'Calexico'),
 ('The Ultimate Relexation Album',
  "Charles Dutoit & L'Orchestre Symphonique de Montréal"),
 ('Great Opera Choruses',
  'Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti'),
 ('Scheherazade', 'Chicago Symphony Orchestra & Fritz Reiner'),
 ('Minha Historia', 'Chico Buarque'),
 ('Afrociberdelia', 'Chico Science & Nação Zumbi'),
 ('Da Lama Ao Caos', 'Chico Science & Nação Zumbi'),
 ('Palestrina: Missa Papae Marcelli & Allegri: Miserere',
  'Choir Of Westminster Abbey & Simon Preston'),
 ('Bizet: Carmen Highlights',
  'Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker'),
 ('Carry On', 'Chris Cornell'),
 ('SCRIABIN: Vers la flamme', "Christopher O'Riley"),
 ('Acústico MTV [Live]', 'Cidade Negra'),
 ('Cidade Negra - Hits', 'Cidade Negra'),
 ('Na Pista', 'Cláudio Zoli'),
 ('Chronicle, Vol. 1', 'Creedence Clearwater Revival'),
 ('Chronicle, Vol. 2', 'Creedence Clearwater Revival'),
 ('Cássia Eller - Coleção Sem Limite [Disc 2]', 'Cássia Eller'),
 ('Cássia Eller - Sem Limite [Disc 1]', 'Cássia Eller'),
 ('Into The Light', 'David Coverdale'),
 ('MK III The Final Concerts [Disc 1]', 'Deep Purple'),
 ('The Final Concerts (Disc 2)', 'Deep Purple'),
 ('Come Taste The Band', 'Deep Purple'),
 ('Deep Purple In Rock', 'Deep Purple'),
 ('Fireball', 'Deep Purple'),
 ("Knocking at Your Back Door: The Best Of Deep Purple in the 80's",
  'Deep Purple'),
 ('Machine Head', 'Deep Purple'),
 ('Purpendicular', 'Deep Purple'),
 ('Slaves And Masters', 'Deep Purple'),
 ('Stormbringer', 'Deep Purple'),
 ('The Battle Rages On', 'Deep Purple'),
 ("Vault: Def Leppard's Greatest Hits", 'Def Leppard'),
 ('Outbreak', 'Dennis Chambers'),
 ('Djavan Ao Vivo - Vol. 02', 'Djavan'),
 ('Djavan Ao Vivo - Vol. 1', 'Djavan'),
 ('Un-Led-Ed', 'Dread Zeppelin'),
 ('The Best of Ed Motta', 'Ed Motta'),
 ('Adams, John: The Chairman Dances', 'Edo de Waart & San Francisco Symphony'),
 ('Elis Regina-Minha História', 'Elis Regina'),
 ('Chopin: Piano Concertos Nos. 1 & 2',
  'Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra'),
 ("Schubert: The Late String Quartets & String Quintet (3 CD's)",
  'Emerson String Quartet'),
 ('Pachelbel: Canon & Gigue', 'English Concert & Trevor Pinnock'),
 ('Handel: Music for the Royal Fireworks (Original Version 1749)',
  'English Concert & Trevor Pinnock'),
 ('Purcell: Music for the Queen Mary',
  'Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir'),
 ('The Cream Of Clapton', 'Eric Clapton'),
 ('Unplugged', 'Eric Clapton'),
 ('Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies',
  'Eugene Ormandy'),
 ('Strauss: Waltzes', 'Eugene Ormandy'),
 ('Respighi:Pines of Rome', 'Eugene Ormandy'),
 ('Album Of The Year', 'Faith No More'),
 ('Angel Dust', 'Faith No More'),
 ('King For A Day Fool For A Lifetime', 'Faith No More'),
 ('The Real Thing', 'Faith No More'),
 ('Deixa Entrar', 'Falamansa'),
 ('Elgar: Cello Concerto & Vaughan Williams: Fantasias',
  'Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos'),
 ('In Your Honor [Disc 1]', 'Foo Fighters'),
 ('In Your Honor [Disc 2]', 'Foo Fighters'),
 ('One By One', 'Foo Fighters'),
 ('The Colour And The Shape', 'Foo Fighters'),
 ('My Way: The Best Of Frank Sinatra [Disc 1]', 'Frank Sinatra'),
 ('Bongo Fury', 'Frank Zappa & Captain Beefheart'),
 ('Armada: Music from the Courts of England and Spain', 'Fretwork'),
 ('Roda De Funk', 'Funk Como Le Gusta'),
 ("Up An' Atom", 'Gene Krupa'),
 ('Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder',
  'Gerald Moore'),
 ('As Canções de Eu Tu Eles', 'Gilberto Gil'),
 ('Quanta Gente Veio Ver (Live)', 'Gilberto Gil'),
 ('Quanta Gente Veio ver--Bônus De Carnaval', 'Gilberto Gil'),
 ('Faceless', 'Godsmack'),
 ('Meus Momentos', 'Gonzaguinha'),
 ('International Superhits', 'Green Day'),
 ('American Idiot', 'Green Day'),
 ('Appetite for Destruction', "Guns N' Roses"),
 ('Use Your Illusion I', "Guns N' Roses"),
 ('Use Your Illusion II', "Guns N' Roses"),
 ('Great Recordings of the Century - Mahler: Das Lied von der Erde',
  'Gustav Mahler'),
 ('Nielsen: The Six Symphonies', 'Göteborgs Symfoniker & Neeme Järvi'),
 ('Muso Ko', 'Habib Koité and Bamada'),
 ('Puccini: Madama Butterfly - Highlights',
  'Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker'),
 ('Heroes, Season 1', 'Heroes'),
 ('Bach: Violin Concertos',
  'Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer'),
 ('House of Pain', 'House Of Pain'),
 ('Blue Moods', 'Incognito'),
 ('A Matter of Life and Death', 'Iron Maiden'),
 ('A Real Dead One', 'Iron Maiden'),
 ('A Real Live One', 'Iron Maiden'),
 ('Brave New World', 'Iron Maiden'),
 ('Dance Of Death', 'Iron Maiden'),
 ('Fear Of The Dark', 'Iron Maiden'),
 ('Iron Maiden', 'Iron Maiden'),
 ('Killers', 'Iron Maiden'),
 ('Live After Death', 'Iron Maiden'),
 ('Live At Donington 1992 (Disc 1)', 'Iron Maiden'),
 ('Live At Donington 1992 (Disc 2)', 'Iron Maiden'),
 ('No Prayer For The Dying', 'Iron Maiden'),
 ('Piece Of Mind', 'Iron Maiden'),
 ('Powerslave', 'Iron Maiden'),
 ('Rock In Rio [CD1]', 'Iron Maiden'),
 ('Rock In Rio [CD2]', 'Iron Maiden'),
 ('Seventh Son of a Seventh Son', 'Iron Maiden'),
 ('Somewhere in Time', 'Iron Maiden'),
 ('The Number of The Beast', 'Iron Maiden'),
 ('The X Factor', 'Iron Maiden'),
 ('Virtual XI', 'Iron Maiden'),
 ("Great Recordings of the Century: Paganini's 24 Caprices", 'Itzhak Perlman'),
 ('Get Born', 'JET'),
 ('Sex Machine', 'James Brown'),
 ('Mascagni: Cavalleria Rusticana', 'James Levine'),
 ('Emergency On Planet Earth', 'Jamiroquai'),
 ('Synkronized', 'Jamiroquai'),
 ('The Return Of The Space Cowboy', 'Jamiroquai'),
 ('Are You Experienced?', 'Jimi Hendrix'),
 ('Surfing with the Alien (Remastered)', 'Joe Satriani'),
 ('Jorge Ben Jor 25 Anos', 'Jorge Ben'),
 ('Jota Quest-1995', 'Jota Quest'),
 ('Cafezinho', 'João Suplicy'),
 ('Living After Midnight', 'Judas Priest'),
 ('J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro',
  'Julian Bream'),
 ('Realize', 'Karsh Kale'),
 ('Weill: The Seven Deadly Sins',
  "Kent Nagano and Orchestre de l'Opéra de Lyon"),
 ('Greatest Kiss', 'Kiss'),
 ('Unplugged [Live]', 'Kiss'),
 ('BBC Sessions [Disc 1] [Live]', 'Led Zeppelin'),
 ('Physical Graffiti [Disc 1]', 'Led Zeppelin'),
 ('BBC Sessions [Disc 2] [Live]', 'Led Zeppelin'),
 ('Coda', 'Led Zeppelin'),
 ('Houses Of The Holy', 'Led Zeppelin'),
 ('In Through The Out Door', 'Led Zeppelin'),
 ('IV', 'Led Zeppelin'),
 ('Led Zeppelin I', 'Led Zeppelin'),
 ('Led Zeppelin II', 'Led Zeppelin'),
 ('Led Zeppelin III', 'Led Zeppelin'),
 ('Physical Graffiti [Disc 2]', 'Led Zeppelin'),
 ('Presence', 'Led Zeppelin'),
 ('The Song Remains The Same (Disc 1)', 'Led Zeppelin'),
 ('The Song Remains The Same (Disc 2)', 'Led Zeppelin'),
 ('A TempestadeTempestade Ou O Livro Dos Dias', 'Legião Urbana'),
 ('Mais Do Mesmo', 'Legião Urbana'),
 ('Greatest Hits', 'Lenny Kravitz'),
 ("Great Performances - Barber's Adagio and Other Romantic Favorites for Strings",
  'Leonard Bernstein & New York Philharmonic'),
 ('Charpentier: Divertissements, Airs & Concerts',
  'Les Arts Florissants & William Christie'),
 ('Tchaikovsky: The Nutcracker',
  'London Symphony Orchestra & Sir Charles Mackerras'),
 ('Lost, Season 3', 'Lost'),
 ('Lost, Season 1', 'Lost'),
 ('Lost, Season 2', 'Lost'),
 ('LOST, Season 4', 'Lost'),
 ('Duos II', 'Luciana Souza/Romero Lubambo'),
 ("Pavarotti's Opera Made Easy", 'Luciano Pavarotti'),
 ('Lulu Santos - RCA 100 Anos De Música - Álbum 01', 'Lulu Santos'),
 ('Lulu Santos - RCA 100 Anos De Música - Álbum 02', 'Lulu Santos'),
 ('Chill: Brazil (Disc 1)', 'Marcos Valle'),
 ('Misplaced Childhood', 'Marillion'),
 ('Barulhinho Bom', 'Marisa Monte'),
 ('Szymanowski: Piano Works, Vol. 1', 'Martin Roscoe'),
 ('Seek And Shall Find: More Of The Best (1963-1981)', 'Marvin Gaye'),
 ('Beethoven Piano Sonatas: Moonlight & Pastorale', 'Maurizio Pollini'),
 ('Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3',
  'Mela Tenenbaum, Pro Musica Prague & Richard Kapp'),
 ('The Best Of Men At Work', 'Men At Work'),
 ('Garage Inc. (Disc 1)', 'Metallica'),
 ('Black Album', 'Metallica'),
 ('Garage Inc. (Disc 2)', 'Metallica'),
 ("Kill 'Em All", 'Metallica'),
 ('Load', 'Metallica'),
 ('Master Of Puppets', 'Metallica'),
 ('ReLoad', 'Metallica'),
 ('Ride The Lightning', 'Metallica'),
 ('St. Anger', 'Metallica'),
 ('...And Justice For All', 'Metallica'),
 ('Prokofiev: Romeo & Juliet',
  'Michael Tilson Thomas & San Francisco Symphony'),
 ('Berlioz: Symphonie Fantastique',
  'Michael Tilson Thomas & San Francisco Symphony'),
 ("Liszt - 12 Études D'Execution Transcendante", 'Michele Campanella'),
 ('The Essential Miles Davis [Disc 1]', 'Miles Davis'),
 ('The Essential Miles Davis [Disc 2]', 'Miles Davis'),
 ('Miles Ahead', 'Miles Davis'),
 ('Milton Nascimento Ao Vivo', 'Milton Nascimento'),
 ('Minas', 'Milton Nascimento'),
 ('Ace Of Spades', 'Motörhead'),
 ('Demorou...', 'Mônica Marianno'),
 ('Motley Crue Greatest Hits', 'Mötley Crüe'),
 ('Mozart: Chamber Music', 'Nash Ensemble'),
 ('The Best of Beethoven', 'Nicolaus Esterhazy Sinfonia'),
 ('From The Muddy Banks Of The Wishkah [Live]', 'Nirvana'),
 ('Nevermind', 'Nirvana'),
 ('Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro',
  'O Rappa'),
 ('Compositores', 'O Terço'),
 ('Olodum', 'Olodum'),
 ('Bach: The Brandenburg Concertos', 'Orchestra of The Age of Enlightenment'),
 ('Beethoven: Symhonies Nos. 5 & 6',
  'Orchestre Révolutionnaire et Romantique & John Eliot Gardiner'),
 ('Minha História', 'Os Mutantes'),
 ('Acústico MTV', 'Os Paralamas Do Sucesso'),
 ('Arquivo II', 'Os Paralamas Do Sucesso'),
 ('Arquivo Os Paralamas Do Sucesso', 'Os Paralamas Do Sucesso'),
 ("Beethoven: Symphony No. 6 'Pastoral' Etc.",
  'Otto Klemperer & Philharmonia Orchestra'),
 ('Bark at the Moon (Remastered)', 'Ozzy Osbourne'),
 ('Blizzard of Ozz', 'Ozzy Osbourne'),
 ('Diary of a Madman (Remastered)', 'Ozzy Osbourne'),
 ('No More Tears (Remastered)', 'Ozzy Osbourne'),
 ('Tribute', 'Ozzy Osbourne'),
 ('Speak of the Devil', 'Ozzy Osbourne'),
 ('Walking Into Clarksdale', 'Page & Plant'),
 ('Original Soundtracks 1', 'Passengers'),
 ('The Beast Live', "Paul D'Ianno"),
 ('Live On Two Legs [Live]', 'Pearl Jam'),
 ('Pearl Jam', 'Pearl Jam'),
 ('Riot Act', 'Pearl Jam'),
 ('Ten', 'Pearl Jam'),
 ('Vs.', 'Pearl Jam'),
 ("Mendelssohn: A Midsummer Night's Dream",
  'Philharmonia Orchestra & Sir Neville Marriner'),
 ('Koyaanisqatsi (Soundtrack from the Motion Picture)',
  'Philip Glass Ensemble'),
 ('Dark Side Of The Moon', 'Pink Floyd'),
 ('Os Cães Ladram Mas A Caravana Não Pára', 'Planet Hemp'),
 ('Greatest Hits II', 'Queen'),
 ('Greatest Hits I', 'Queen'),
 ('News Of The World', 'Queen'),
 ('Green', 'R.E.M.'),
 ('New Adventures In Hi-Fi', 'R.E.M.'),
 ('The Best Of R.E.M.: The IRS Years', 'R.E.M.'),
 ('Out Of Time', 'R.E.M. Feat. Kate Pearson'),
 ('Cesta Básica', 'Raimundos'),
 ('Raul Seixas', 'Raul Seixas'),
 ('Blood Sugar Sex Magik', 'Red Hot Chili Peppers'),
 ('By The Way', 'Red Hot Chili Peppers'),
 ('Californication', 'Red Hot Chili Peppers'),
 ('Allegri: Miserere',
  'Richard Marlow & The Choir of Trinity College, Cambridge'),
 ('Purcell: The Fairy Queen', 'Roger Norrington, London Classical Players'),
 ('Haydn: Symphonies 99 - 104',
  'Royal Philharmonic Orchestra & Sir Thomas Beecham'),
 ('Retrospective I (1974-1980)', 'Rush'),
 ('Supernatural', 'Santana'),
 ('Santana - As Years Go By', 'Santana'),
 ('Santana Live', 'Santana'),
 ('Handel: The Messiah (Highlights)', 'Scholars Baroque Ensemble'),
 ('20th Century Masters - The Millennium Collection: The Best of Scorpions',
  'Scorpions'),
 ('Prokofiev: Symphony No.1', 'Sergei Prokofiev & Yuri Temirkanov'),
 ('Wagner: Favourite Overtures', 'Sir Georg Solti & Wiener Philharmoniker'),
 ('Mozart Gala: Famous Arias',
  'Sir Georg Solti, Sumi Jo & Wiener Philharmoniker'),
 ('Maquinarama', 'Skank'),
 ('O Samba Poconé', 'Skank'),
 ('Judas 0: B-Sides and Rarities', 'Smashing Pumpkins'),
 ('Rotten Apples: Greatest Hits', 'Smashing Pumpkins'),
 ('A-Sides', 'Soundgarden'),
 ('Heart of the Night', 'Spyro Gyra'),
 ('Morning Dance', 'Spyro Gyra'),
 ('In Step', 'Stevie Ray Vaughan & Double Trouble'),
 ('Core', 'Stone Temple Pilots'),
 ('Mezmerize', 'System Of A Down'),
 ('Temple of the Dog', 'Temple of the Dog'),
 ('[1997] Black Light Syndrome', 'Terry Bozzio, Tony Levin & Steve Stevens'),
 ('South American Getaway', 'The 12 Cellists of The Berlin Philharmonic'),
 ('Live [Disc 1]', 'The Black Crowes'),
 ('Live [Disc 2]', 'The Black Crowes'),
 ('The Singles', 'The Clash'),
 ('Beyond Good And Evil', 'The Cult'),
 ('Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]',
  'The Cult'),
 ('The Doors', 'The Doors'),
 ('English Renaissance', "The King's Singers"),
 ('The Office, Season 1', 'The Office'),
 ('The Office, Season 2', 'The Office'),
 ('The Office, Season 3', 'The Office'),
 ('The Police Greatest Hits', 'The Police'),
 ('Every Kind of Light', 'The Posies'),
 ('Hot Rocks, 1964-1971 (Disc 1)', 'The Rolling Stones'),
 ('No Security', 'The Rolling Stones'),
 ('Voodoo Lounge', 'The Rolling Stones'),
 ('Tangents', 'The Tea Party'),
 ('Transmission', 'The Tea Party'),
 ('My Generation - The Very Best Of The Who', 'The Who'),
 ('Serie Sem Limite (Disc 1)', 'Tim Maia'),
 ('Serie Sem Limite (Disc 2)', 'Tim Maia'),
 ('Acústico', 'Titãs'),
 ('Volume Dois', 'Titãs'),
 ('Bach: Toccata & Fugue in D Minor', 'Ton Koopman'),
 ('Vinícius De Moraes - Sem Limite', 'Toquinho & Vinícius'),
 ('Achtung Baby', 'U2'),
 ("All That You Can't Leave Behind", 'U2'),
 ('B-Sides 1980-1990', 'U2'),
 ('How To Dismantle An Atomic Bomb', 'U2'),
 ('Pop', 'U2'),
 ('Rattle And Hum', 'U2'),
 ('The Best Of 1980-1990', 'U2'),
 ('War', 'U2'),
 ('Zooropa', 'U2'),
 ('Instant Karma: The Amnesty International Campaign to Save Darfur', 'U2'),
 ('UB40 The Best Of - Volume Two [UK]', 'UB40'),
 ('Diver Down', 'Van Halen'),
 ('The Best Of Van Halen, Vol. I', 'Van Halen'),
 ('Van Halen', 'Van Halen'),
 ('Van Halen III', 'Van Halen'),
 ('Axé Bahia 2001', 'Various Artists'),
 ('Carnaval 2001', 'Various Artists'),
 ('Sambas De Enredo 2001', 'Various Artists'),
 ('Vozes do MPB', 'Various Artists'),
 ('Contraband', 'Velvet Revolver'),
 ('Vinicius De Moraes', 'Vinícius De Moraes'),
 ('Bach: Goldberg Variations', 'Wilhelm Kempff'),
 ('Bartok: Violin & Viola Concertos', 'Yehudi Menuhin'),
 ('Bach: The Cello Suites', 'Yo-Yo Ma'),
 ('Ao Vivo [IMPORT]', 'Zeca Pagodinho')]

## JOIN + GROUP BY

In [30]:
cursor.execute('''
SELECT ar.Name AS artist, COUNT(a.AlbumId) AS album_count
FROM artists AS ar
LEFT JOIN albums AS a
ON  a.ArtistId = ar.ArtistId
GROUP BY ar.ArtistId, ar.Name
ORDER BY album_count DESC
''')
result = cursor.fetchall()
result

[('Iron Maiden', 21),
 ('Led Zeppelin', 14),
 ('Deep Purple', 11),
 ('Metallica', 10),
 ('U2', 10),
 ('Ozzy Osbourne', 6),
 ('Pearl Jam', 5),
 ('Various Artists', 4),
 ('Faith No More', 4),
 ('Foo Fighters', 4),
 ('Lost', 4),
 ('Van Halen', 4),
 ('Audioslave', 3),
 ('Gilberto Gil', 3),
 ('Queen', 3),
 ('Santana', 3),
 ('Miles Davis', 3),
 ("Guns N' Roses", 3),
 ('Jamiroquai', 3),
 ('Os Paralamas Do Sucesso', 3),
 ('R.E.M.', 3),
 ('Red Hot Chili Peppers', 3),
 ('The Rolling Stones', 3),
 ('The Office', 3),
 ('Eugene Ormandy', 3),
 ('Berliner Philharmoniker & Herbert Von Karajan', 3),
 ('AC/DC', 2),
 ('Accept', 2),
 ('Antônio Carlos Jobim', 2),
 ('Black Label Society', 2),
 ('Black Sabbath', 2),
 ('Caetano Veloso', 2),
 ('Chico Science & Nação Zumbi', 2),
 ('Cidade Negra', 2),
 ('Milton Nascimento', 2),
 ('Kiss', 2),
 ('Spyro Gyra', 2),
 ('Green Day', 2),
 ('Creedence Clearwater Revival', 2),
 ('Cássia Eller', 2),
 ('Djavan', 2),
 ('Eric Clapton', 2),
 ('Legião Urbana', 2),
 ('Lulu Santos', 2),
 ('Nirvana', 2),
 ('Skank', 2),
 ('Smashing Pumpkins', 2),
 ('The Black Crowes', 2),
 ('The Cult', 2),
 ('The Tea Party', 2),
 ('Tim Maia', 2),
 ('Titãs', 2),
 ('Battlestar Galactica', 2),
 ('English Concert & Trevor Pinnock', 2),
 ('Michael Tilson Thomas & San Francisco Symphony', 2),
 ('Amy Winehouse', 2),
 ('Aerosmith', 1),
 ('Alanis Morissette', 1),
 ('Alice In Chains', 1),
 ('Apocalyptica', 1),
 ('BackBeat', 1),
 ('Billy Cobham', 1),
 ('Body Count', 1),
 ('Bruce Dickinson', 1),
 ('Buddy Guy', 1),
 ('Chico Buarque', 1),
 ('Cláudio Zoli', 1),
 ('Frank Zappa & Captain Beefheart', 1),
 ('Marcos Valle', 1),
 ('O Rappa', 1),
 ('Ed Motta', 1),
 ('Elis Regina', 1),
 ('Jorge Ben', 1),
 ('David Coverdale', 1),
 ('Gonzaguinha', 1),
 ('Os Mutantes', 1),
 ('Gene Krupa', 1),
 ('Toquinho & Vinícius', 1),
 ('Vinícius De Moraes', 1),
 ('Def Leppard', 1),
 ('Dennis Chambers', 1),
 ('Falamansa', 1),
 ('Frank Sinatra', 1),
 ('Funk Como Le Gusta', 1),
 ('Godsmack', 1),
 ('Incognito', 1),
 ('James Brown', 1),
 ('JET', 1),
 ('Jimi Hendrix', 1),
 ('Joe Satriani', 1),
 ('Jota Quest', 1),
 ('João Suplicy', 1),
 ('Judas Priest', 1),
 ('Lenny Kravitz', 1),
 ('Marillion', 1),
 ('Marisa Monte', 1),
 ('Marvin Gaye', 1),
 ('Men At Work', 1),
 ('Motörhead', 1),
 ('Mônica Marianno', 1),
 ('Mötley Crüe', 1),
 ('O Terço', 1),
 ('Olodum', 1),
 ('Page & Plant', 1),
 ('Passengers', 1),
 ("Paul D'Ianno", 1),
 ('Pink Floyd', 1),
 ('Planet Hemp', 1),
 ('R.E.M. Feat. Kate Pearson', 1),
 ('Raimundos', 1),
 ('Raul Seixas', 1),
 ('Rush', 1),
 ('Soundgarden', 1),
 ('Stevie Ray Vaughan & Double Trouble', 1),
 ('Stone Temple Pilots', 1),
 ('System Of A Down', 1),
 ('Terry Bozzio, Tony Levin & Steve Stevens', 1),
 ('The Clash', 1),
 ('The Doors', 1),
 ('The Police', 1),
 ('The Who', 1),
 ('Heroes', 1),
 ('UB40', 1),
 ('Velvet Revolver', 1),
 ('Zeca Pagodinho', 1),
 ('Dread Zeppelin', 1),
 ('Battlestar Galactica (Classic)', 1),
 ('Aquaman', 1),
 ('Scorpions', 1),
 ('House Of Pain', 1),
 ('Cake', 1),
 ('Aisha Duo', 1),
 ('Habib Koité and Bamada', 1),
 ('Karsh Kale', 1),
 ('The Posies', 1),
 ('Luciana Souza/Romero Lubambo', 1),
 ('Aaron Goldberg', 1),
 ('Nicolaus Esterhazy Sinfonia', 1),
 ('Temple of the Dog', 1),
 ('Chris Cornell', 1),
 ('Alberto Turco & Nova Schola Gregoriana', 1),
 ('Richard Marlow & The Choir of Trinity College, Cambridge', 1),
 ('Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker', 1),
 ('Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer',
  1),
 ('Wilhelm Kempff', 1),
 ('Yo-Yo Ma', 1),
 ('Scholars Baroque Ensemble', 1),
 ('Academy of St. Martin in the Fields & Sir Neville Marriner', 1),
 ('Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner',
  1),
 ('Berliner Philharmoniker, Claudio Abbado & Sabine Meyer', 1),
 ('Royal Philharmonic Orchestra & Sir Thomas Beecham', 1),
 ('Orchestre Révolutionnaire et Romantique & John Eliot Gardiner', 1),
 ('Britten Sinfonia, Ivor Bolton & Lesley Garrett', 1),
 ('Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti', 1),
 ('Sir Georg Solti & Wiener Philharmoniker', 1),
 ('Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair',
  1),
 ('London Symphony Orchestra & Sir Charles Mackerras', 1),
 ('Barry Wordsworth & BBC Concert Orchestra', 1),
 ('Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker', 1),
 ('Luciano Pavarotti', 1),
 ('Leonard Bernstein & New York Philharmonic', 1),
 ('Boston Symphony Orchestra & Seiji Ozawa', 1),
 ('Aaron Copland & London Symphony Orchestra', 1),
 ('Ton Koopman', 1),
 ('Sergei Prokofiev & Yuri Temirkanov', 1),
 ('Chicago Symphony Orchestra & Fritz Reiner', 1),
 ('Orchestra of The Age of Enlightenment', 1),
 ('Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra', 1),
 ('James Levine', 1),
 ('Berliner Philharmoniker & Hans Rosbaud', 1),
 ('Maurizio Pollini', 1),
 ('Gustav Mahler', 1),
 ('Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos', 1),
 ('Edo de Waart & San Francisco Symphony', 1),
 ('Antal Doráti & London Symphony Orchestra', 1),
 ('Choir Of Westminster Abbey & Simon Preston', 1),
 ('Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker',
  1),
 ("The King's Singers", 1),
 ('Sir Georg Solti, Sumi Jo & Wiener Philharmoniker', 1),
 ("Christopher O'Riley", 1),
 ('Fretwork', 1),
 ('Calexico', 1),
 ('Otto Klemperer & Philharmonia Orchestra', 1),
 ('Yehudi Menuhin', 1),
 ('Philharmonia Orchestra & Sir Neville Marriner', 1),
 ('Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart',
  1),
 ('Les Arts Florissants & William Christie', 1),
 ('The 12 Cellists of The Berlin Philharmonic', 1),
 ('Adrian Leaper & Doreen de Feis', 1),
 ('Roger Norrington, London Classical Players', 1),
 ("Charles Dutoit & L'Orchestre Symphonique de Montréal", 1),
 ('Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir',
  1),
 ("Kent Nagano and Orchestre de l'Opéra de Lyon", 1),
 ('Julian Bream', 1),
 ('Martin Roscoe', 1),
 ('Göteborgs Symfoniker & Neeme Järvi', 1),
 ('Itzhak Perlman', 1),
 ('Michele Campanella', 1),
 ('Gerald Moore', 1),
 ('Mela Tenenbaum, Pro Musica Prague & Richard Kapp', 1),
 ('Emerson String Quartet', 1),
 ('C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu',
  1),
 ('Nash Ensemble', 1),
 ('Philip Glass Ensemble', 1),
 ('Milton Nascimento & Bebeto', 0),
 ('Azymuth', 0),
 ('João Gilberto', 0),
 ('Bebel Gilberto', 0),
 ('Jorge Vercilo', 0),
 ('Baby Consuelo', 0),
 ('Ney Matogrosso', 0),
 ('Luiz Melodia', 0),
 ('Nando Reis', 0),
 ('Pedro Luís & A Parede', 0),
 ('Banda Black Rio', 0),
 ('Fernanda Porto', 0),
 ('Os Cariocas', 0),
 ('A Cor Do Som', 0),
 ('Kid Abelha', 0),
 ('Sandra De Sá', 0),
 ('Hermeto Pascoal', 0),
 ('Barão Vermelho', 0),
 ('Edson, DJ Marky & DJ Patife Featuring Fernanda Porto', 0),
 ('Santana Feat. Dave Matthews', 0),
 ('Santana Feat. Everlast', 0),
 ('Santana Feat. Rob Thomas', 0),
 ('Santana Feat. Lauryn Hill & Cee-Lo', 0),
 ('Santana Feat. The Project G&B', 0),
 ('Santana Feat. Maná', 0),
 ('Santana Feat. Eagle-Eye Cherry', 0),
 ('Santana Feat. Eric Clapton', 0),
 ('Vinícius De Moraes & Baden Powell', 0),
 ('Vinícius E Qurteto Em Cy', 0),
 ('Vinícius E Odette Lara', 0),
 ('Vinicius, Toquinho & Quarteto Em Cy', 0),
 ('Motörhead & Girlschool', 0),
 ('Peter Tosh', 0),
 ('R.E.M. Feat. KRS-One', 0),
 ('Simply Red', 0),
 ('Whitesnake', 0),
 ('Christina Aguilera featuring BigElf', 0),
 ("Aerosmith & Sierra Leone's Refugee Allstars", 0),
 ('Los Lonely Boys', 0),
 ('Corinne Bailey Rae', 0),
 ('Dhani Harrison & Jakob Dylan', 0),
 ('Jackson Browne', 0),
 ('Avril Lavigne', 0),
 ('Big & Rich', 0),
 ("Youssou N'Dour", 0),
 ('Black Eyed Peas', 0),
 ('Jack Johnson', 0),
 ('Ben Harper', 0),
 ('Snow Patrol', 0),
 ('Matisyahu', 0),
 ('The Postal Service', 0),
 ('Jaguares', 0),
 ('The Flaming Lips', 0),
 ("Jack's Mannequin & Mick Fleetwood", 0),
 ('Regina Spektor', 0),
 ('Xis', 0),
 ('Nega Gizza', 0),
 ('Gustavo & Andres Veiga & Salazar', 0),
 ('Rodox', 0),
 ('Charlie Brown Jr.', 0),
 ('Pedro Luís E A Parede', 0),
 ('Los Hermanos', 0),
 ('Mundo Livre S/A', 0),
 ('Otto', 0),
 ('Instituto', 0),
 ('Nação Zumbi', 0),
 ('DJ Dolores & Orchestra Santa Massa', 0),
 ('Seu Jorge', 0),
 ('Sabotage E Instituto', 0),
 ('Stereo Maracana', 0),
 ('Academy of St. Martin in the Fields, Sir Neville Marriner & William Bennett',
  0)]

In [32]:
df = pd.read_sql_query('''
SELECT ar.Name AS artist, COUNT(a.AlbumId) AS album_count
FROM artists AS ar
LEFT JOIN albums AS a
ON  a.ArtistId = ar.ArtistId
GROUP BY ar.ArtistId, ar.Name
ORDER BY album_count DESC
''', conn)

df.head(40)

                                           artist  album_count
0                                     Iron Maiden           21
1                                    Led Zeppelin           14
2                                     Deep Purple           11
3                                       Metallica           10
4                                              U2           10
5                                   Ozzy Osbourne            6
6                                       Pearl Jam            5
7                                 Various Artists            4
8                                   Faith No More            4
9                                    Foo Fighters            4
10                                           Lost            4
11                                      Van Halen            4
12                                     Audioslave            3
13                                   Gilberto Gil            3
14                                          Queen            3
15                                        Santana            3
16                                    Miles Davis            3
17                                  Guns N' Roses            3
18                                     Jamiroquai            3
19                        Os Paralamas Do Sucesso            3
20                                         R.E.M.            3
21                          Red Hot Chili Peppers            3
22                             The Rolling Stones            3
23                                     The Office            3
24                                 Eugene Ormandy            3
25  Berliner Philharmoniker & Herbert Von Karajan            3
26                                          AC/DC            2
27                                         Accept            2
28                           Antônio Carlos Jobim            2
29                            Black Label Society            2
30                                  Black Sabbath            2
31                                 Caetano Veloso            2
32                    Chico Science & Nação Zumbi            2
33                                   Cidade Negra            2
34                              Milton Nascimento            2
35                                           Kiss            2
36                                     Spyro Gyra            2
37                                      Green Day            2
38                   Creedence Clearwater Revival            2
39                                   Cássia Eller            2