In [1]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('chinook.db')
cursor = conn.cursor()

## INSERT - Add New Data

In [2]:
pd.read_sql('''
SELECT *
FROM artists
ORDER BY ArtistId DESC
LIMIT 5
''', conn)

   ArtistId           Name
0       288  Test Artist 4
1       287  Test Artist 3
2       286  Test Artist 2
3       285    Test Artist
4       284  Test Artist 4

## INSERT a New Artist

In [3]:
cursor.execute('''
INSERT INTO artists (name)
VALUES (?)
''', ('Test Artist', ))

conn.commit()

## Verify INSERT

In [4]:
pd.read_sql('''
SELECT *
FROM artists
ORDER BY ArtistId DESC
LIMIT 5
''', conn)

   ArtistId           Name
0       289    Test Artist
1       288  Test Artist 4
2       287  Test Artist 3
3       286  Test Artist 2
4       285    Test Artist

## INSERT Multipe Rows

In [5]:
artist_name = [('Test Artist 2',),('Test Artist 3',),('Test Artist 4',)]

cursor.executemany('''
INSERT INTO artists (name)
VALUES (?)
''', artist_name)

conn.commit()

In [6]:
pd.read_sql('''
SELECT *
FROM artists
ORDER BY ArtistId DESC
LIMIT 10
''', conn)

   ArtistId           Name
0       292  Test Artist 4
1       291  Test Artist 3
2       290  Test Artist 2
3       289    Test Artist
4       288  Test Artist 4
5       287  Test Artist 3
6       286  Test Artist 2
7       285    Test Artist
8       284  Test Artist 4
9       283  Test Artist 3

## Update - Modify Existing Data

In [10]:
cursor.execute("""
UPDATE artists
SET name = ?
WHERE name = ?
""", ("Updated Artist", "Test Artist"))

conn.commit()

In [11]:
pd.read_sql('''
SELECT *
FROM artists
ORDER BY ArtistId DESC
LIMIT 10
''', conn)

   ArtistId            Name
0       292   Test Artist 4
1       291   Test Artist 3
2       290   Test Artist 2
3       289  Updated Artist
4       288   Test Artist 4
5       287   Test Artist 3
6       286   Test Artist 2
7       285  Updated Artist
8       284   Test Artist 4
9       283   Test Artist 3

## DELETE - Remove Data

In [12]:
cursor.execute("""
DELETE FROM artists
WHERE name = ?
""", ("Updated Artist",))

conn.commit()

In [13]:
pd.read_sql('''
SELECT *
FROM artists
ORDER BY ArtistId DESC
LIMIT 10
''', conn)

   ArtistId           Name
0       292  Test Artist 4
1       291  Test Artist 3
2       290  Test Artist 2
3       288  Test Artist 4
4       287  Test Artist 3
5       286  Test Artist 2
6       284  Test Artist 4
7       283  Test Artist 3
8       282  Test Artist 2
9       280  Test Artist 4

## DELETE Multiple Rows

In [14]:
cursor.execute("""
DELETE FROM artists
WHERE name LIKE 'Test Artist%'
""")

conn.commit()

In [15]:
pd.read_sql('''
SELECT *
FROM artists
ORDER BY ArtistId DESC
LIMIT 10
''', conn)

   ArtistId                                               Name
0       275                              Philip Glass Ensemble
1       274                                      Nash Ensemble
2       273  C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...
3       272                             Emerson String Quartet
4       271   Mela Tenenbaum, Pro Musica Prague & Richard Kapp
5       270                                       Gerald Moore
6       269                                 Michele Campanella
7       268                                     Itzhak Perlman
8       267                 Göteborgs Symfoniker & Neeme Järvi
9       266                                      Martin Roscoe

## Rollback

In [22]:
cursor.executemany('''
INSERT INTO artists (name)
VALUES (?)
''', artist_name)

In [23]:
pd.read_sql('''
SELECT *
FROM artists
ORDER BY ArtistId DESC
LIMIT 10
''', conn)

   ArtistId                                               Name
0       295                                      Test Artist 4
1       294                                      Test Artist 3
2       293                                      Test Artist 2
3       275                              Philip Glass Ensemble
4       274                                      Nash Ensemble
5       273  C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...
6       272                             Emerson String Quartet
7       271   Mela Tenenbaum, Pro Musica Prague & Richard Kapp
8       270                                       Gerald Moore
9       269                                 Michele Campanella

In [24]:
cursor.executemany('''
INSERT INTO artists (name)
VALUES (?)
''', artist_name)

conn.rollback()

In [25]:
pd.read_sql('''
SELECT *
FROM artists
ORDER BY ArtistId DESC
LIMIT 10
''', conn)

   ArtistId                                               Name
0       275                              Philip Glass Ensemble
1       274                                      Nash Ensemble
2       273  C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...
3       272                             Emerson String Quartet
4       271   Mela Tenenbaum, Pro Musica Prague & Richard Kapp
5       270                                       Gerald Moore
6       269                                 Michele Campanella
7       268                                     Itzhak Perlman
8       267                 Göteborgs Symfoniker & Neeme Järvi
9       266                                      Martin Roscoe

## Safe Modifiction Workflow

In [26]:
# Step 1 - Check

# Step 2 - Modify

# Step 3 - Verify

# Step 4 - Commit