# CREATE Table & Database Structure

In [1]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('chinook.db')
cursor = conn.cursor()

## Inspect Existing Tables

In [2]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type = 'table'
ORDER BY name
""", conn)

               name
0            albums
1           artists
2           courses
3         customers
4        department
5       departments
6         employees
7            genres
8     invoice_items
9          invoices
10      media_types
11   playlist_track
12        playlists
13    practice_data
14         products
15  sqlite_sequence
16     sqlite_stat1
17         students
18            tasks
19           tracks
20            users

## CREATE TABLE

In [3]:
cursor.execute('''
CREATE TABLE practice_data(
id INTEGER,
name TEXT,
age INTEGER
)
''')

OperationalError: table practice_data already exists

## Check the New Table

In [4]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type = 'table'
ORDER BY name
""", conn)

               name
0            albums
1           artists
2           courses
3         customers
4        department
5       departments
6         employees
7            genres
8     invoice_items
9          invoices
10      media_types
11   playlist_track
12        playlists
13    practice_data
14         products
15  sqlite_sequence
16     sqlite_stat1
17         students
18            tasks
19           tracks
20            users

## SQLite Data Types

In [5]:
# INTEGER --> int
# REAL    --> float
# TEXT    --> str
# BLOB    --> 0 & 1
# NULL    --> empty

## PRIMARY KEY

In [6]:
cursor.execute('''
CREATE TABLE students(
studant_id INTEGER PRIMARY KEY,
name TEXT,
score REAL
)
''')

OperationalError: table students already exists

In [7]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type = 'table'
ORDER BY name
""", conn)

               name
0            albums
1           artists
2           courses
3         customers
4        department
5       departments
6         employees
7            genres
8     invoice_items
9          invoices
10      media_types
11   playlist_track
12        playlists
13    practice_data
14         products
15  sqlite_sequence
16     sqlite_stat1
17         students
18            tasks
19           tracks
20            users

## AUTOINCREMENT

In [8]:
# No need to add id!

In [9]:
cursor.execute('''
CREATE TABLE courses (
course_id INTEGER PRIMARY KEY AUTOINCREMENT,
course_name TEXT,
duration INTEGER
)
''')

OperationalError: table courses already exists

In [10]:
cursor.execute('''
INSERT INTO courses (course_name, duration)
VALUES (?, ?)
''', ('Pathon',40 ))

In [11]:
pd.read_sql('''
SELECT *
FROM courses
''', conn)

   course_id course_name  duration
0          1      Pathon        40
1          2      Pathon        40

## NOT NULL

In [12]:
cursor.execute('''
CREATE TABLE products(
product_id INTEGER PRIMARY KEY,
product_name TEXT NOT NULL,
price REAL NOT NULL
)
''')

OperationalError: table products already exists

## UNIQUE

In [13]:
cursor.execute('''
CREATE TABLE users(
user_id INTEGER PRIMARY KEY,
username TEXT UNIQE
)
''')

OperationalError: table users already exists

In [14]:
cursor.execute('''
INSERT INTO users (username)
VALUES (?)
''', ('mostafa',))

conn.commit()

In [15]:
cursor.execute('''
INSERT INTO users (username)
VALUES (?)
''', ('mostafa',))
conn.commit()

## DEFAULT

In [16]:
cursor.execute('''
CREATE TABLE tasks (
task_id INTEGER PRIMARY KEY,
yask_name TEXT NOT NULL,
status TEXT DEFAULT 'Pending'
)
''')

conn.commit()

OperationalError: table tasks already exists

In [17]:
cursor.execute('''
INSERT INTO tasks (yask_name)
VALUES(?)
''', ('LEARN',))
conn.commit()

In [18]:
pd.read_sql('''
SELECT *
FROM tasks
''', conn)

   task_id yask_name   status
0        1     LEARN  Pending
1        2     LEARN  Pending

## Foreign Key

In [19]:
cursor.execute('''
CREATE TABLE departments (
dep_id INTEGER PRIMARY KEY,
dep_name TEXT
)
''')

cursor.execute('''
CREATE TABLE employee (
em_id INTEGER PRIMARY KEY,
em(name TEXT NUT NOLL,
dep_id INTEGER,
FOREIGN KEY (dep_id)
REFRENCES (dep_id)
)
''')

conn.commit()

OperationalError: table departments already exists

## Inspect Table Structure

In [20]:
pd.read_sql('''
PRAGMA table_info(artist)
''', conn)

Empty DataFrame
Columns: [cid, name, type, notnull, dflt_value, pk]
Index: []

## DROP TABLE

In [23]:
cursor.execute('DROP TABLE practice_data')
cursor.execute('DROP TABLE students')
cursor.execute('DROP TABLE courses')
cursor.execute('DROP TABLE products')
cursor.execute('DROP TABLE users')
cursor.execute('DROP TABLE tasks')
cursor.execute('DROP TABLE employees')
cursor.execute('DROP TABLE departments')

conn.commit()

OperationalError: no such table: practice_data

In [24]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type = 'table'
ORDER BY name
""", conn)

               name
0            albums
1           artists
2         customers
3        department
4       departments
5         employees
6            genres
7     invoice_items
8          invoices
9       media_types
10   playlist_track
11        playlists
12  sqlite_sequence
13     sqlite_stat1
14           tracks